### DISCUSSION TITLE
integrate custom s3 storage (self hosted)

### DISCUSSION THREAD

**Discussion by lukkaempf** [supabase/supabase#10634] [Questions] [answered]
How to set custom S3 endpoint url? For example Wasabi, MinIO    (self hosted)

**Comment by morandalex** [comment]
yeah I am interested , how to do it?

**Comment by pkdash** [comment]
I am also interested in how to integrate custom storage (e.g. MinIO).

**Comment by lukkaempf** [comment, marked as answer]
you can set the "globalS3Endpoint" parameter in the docker compose under the storage container configuration


Example for MinIo:
```
environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      GLOBALS3ENDPOINT: https://localhost:9000
      STORAGE_BACKEND: s3
      TENANT_ID: test
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://imgproxy:5001
```

For the credentials you can use the AWS S3 file. ([AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html))
The file should be at  "~/.aws/credentials" with the following lines in the Container. 
```
[default]
aws_access_key_id = YOUR_AWS_ACCESS_KEY_ID
aws_secret_access_key = YOUR_AWS_SECRET_ACCESS_KEY
```

It should also be possible to set the credentials via the env file. ([AWS docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html))
```
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```


both aws credentials ways didn't work for me. that's why I stored the access data in the source code.
