### DISCUSSION TITLE
Self hosted supabase realtime server isnt working as it should.

### DISCUSSION THREAD

**Discussion by jameswong3388** [supabase/supabase#11313] [Questions] [answered]
![image](https://user-images.githubusercontent.com/87692325/209778636-884a830a-a1df-49c9-a92a-4968ea77fba9.png)

As you can see, we joined the room, but there was no real-time event received from the client. I don't know what's the problem now. Auth and other services work perfectly fine. I even tried with the hosted supabase and its works as well.

I am using caddy to do the reverse proxy etc.

Caddyfile
```
https://example.com {
        reverse_proxy /rest/v1/* localhost:8000
        reverse_proxy /auth/v1/* localhost:8000
        reverse_proxy /realtime/v1/* localhost:8000
        reverse_proxy /storage/v1/* localhost:8000
        reverse_proxy /pg/v1/* localhost:8000
        reverse_proxy * localhost:3000

        basicauth / {
                name $yourhashedpassword
        }

        header {
                Content-Security-Policy "upgrade-insecure-requests"
        }

        log {
                output file /var/log/access.log {
                        roll_size 1gb
                        roll_keep 5
                        roll_keep_for 720h
                }
        }
}
```

docker-compose.yml
```
  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v0.25.1
    depends_on:
      db: # Disable this if you are using an external Postgres database
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"
```

Any help would be appreciated ~
