### DISCUSSION TITLE
Can't connect after upgrading to realtime 2.X.X

### DISCUSSION THREAD

**Discussion by rokk4** [supabase/supabase#11923] [Questions]
I have deployed supabase via docker and and an nginx reverse proxy for TLS infront.
Everything was working fine, but now I tried updating to the current version, Realtime is not working anymore. 

In my flutter frontend (client_sdk 1.3.3) I get the following error:
```
WebSocketException: Connection to 'https://mydomain.tld.:0/realtime/v1/websocket?apikey={API-KEY-REMOVED}&vsn=1.0.0#' was not upgraded to websocket
E/flutter (18947): #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
E/flutter (18947): #1      WebSocket.connect (dart:_http/websocket.dart:320:22)
E/flutter (18947): #2      new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80:28)
E/flutter (18947): #3      createWebSocketClient (package:realtime_client/src/websocket/websocket_io.dart:8:29)
E/flutter (18947): #4      RealtimeClient.connect (package:realtime_client/src/realtime_client.dart:119:23)
E/flutter (18947): #5      RealtimeClient.channel (package:realtime_client/src/realtime_client.dart:238:7)
E/flutter (18947): #6      SupabaseClient.channel (package:supabase/src/supabase_client.dart:129:21)
E/flutter (18947): #7      SyncService._addSubscriptions (package:therapy_lift/database/sync_service/sync_service.dart:345:30)
E/flutter (18947): #8      SyncService.startSync.<anonymous closure> (package:therapy_lift/database/sync_service/sync_service.dart:86:11)
```

And I also can see this error in the kong logs:
```
supabase-kong  | 2023/01/25 16:59:45 [error] 23#0: *13654 [lua] balancer.lua:1123: execute(): DNS resolution failed: dns server error: 3 name error. Tried: ["(short)realtime-dev.supabase-realtime:(na) - cache-miss","realtime-dev.supabase-realtime:1 - cache-hit/dns server error: 3 name error","realtime-dev.supabase-realtime:5 - cache-hit/dns server error: 3 name error"], client: 172.18.0.1, server: kong, request: "GET /realtime/v1/websocket?apikey=XXX&vsn=1.0.0 HTTP/1.1", host: "testing.therapy-lift.net"
supabase-kong  | 172.18.0.1 - - [25/Jan/2023:16:59:45 +0000] "GET /realtime/v1/websocket?apikey=XXX&vsn=1.0.0 HTTP/1.1" 503 36 "-" "Dart/2.18 (dart:io)"
```

I adjusted to kong config, like in the example, e.g. changed the url of realtime in kong.yaml.
```
  ## Secure Realtime routes
  - name: realtime-v1
    _comment: "Realtime: /realtime/v1/* -> ws://realtime:4000/socket/*"
    url: http://realtime-dev.supabase-realtime:4000/socket/
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
            - anon
```

What am I missing? Everything was working fine before updating.
