### DISCUSSION TITLE
Environment variables for DB functions

### DISCUSSION THREAD

**Discussion by yngwi** [supabase/supabase#12813] [Feature Requests]
### Update: [it's on our roadmap](https://github.com/orgs/supabase/discussions/12813#discussioncomment-7128188)

---

Hi, I'm currently working through the User Management on React Tutorial and in the [Storage Management](https://supabase.com/docs/guides/getting-started/tutorials/with-react#storage-management) section code example, the project URL and service role key are shown to be hardcoded into a database function:
```
project_url varchar := '<YOURPROJECTURL>';
service_role_key varchar := '<YOURSERVICEROLEKEY>'; --  full access needed
```
I see two problems with this:
1. The values are different for local development environments and the hosted server
2. If used on a local dev server, the values will also become part of migrations and are possibly committed to a code repository

I've had some discussions on the Discord but while some partial solutions have come up, there doesn't seem to be a way to avoid this kind of hardcoding completely. Is this correct or is there another way?

Anyways, my feature request is that it would be very convenient to be able to set environment variables that can be used inside postgres. One alternative could be setting the `PGOPTIONS` parameter on the postgres docker container startup?

Thank you!
Daniel

**Comment by actraiser** [comment]
I second that. I was looking at programmatically deleting storage objects via a pg_cron and had some good pointers in https://github.com/orgs/supabase/discussions/3124#discussioncomment-4824231  

However, storing the service_role_key hardcoded in the functions does not work for the reasons @yngwi  mentioned => a) different Environments require different keys AND b) db migrations are stored in the repository and would have the service_role_key hard-coded into them - not an option.

Adding Environment Variables in the Supabase UI would be the solution imho. 

Greets
-act

**Comment by vickkhera** [comment]
It is possible to set your own variables in the Postgres config file. If the postgresql.auto.conf file (or some other file included by reference into postgresql.conf) were writable, one could append to the end of it something like `supabase.PROJECTURL='https://foo.com'` then query it from within Postgres with the function `current_config('supabase.PROJECTURL')`.

The values can be reloaded into the database using `select pg_reload_conf();` if one wanted to change them on the fly by editing the file or using `ALTER SYSTEM SET supabase.PROJECTURL TO 'new value';`

I think at minimum the self URL should be exposed into Postgres this way, and possibly some other variable indicating if I designate this instance of supabase as production or staging or whatever.

**Comment by devidevio** [comment]
I found a practical solution for me (Self Hosted).

1. Define your Docker Compose Teplate (yml).
2. For the Database Container (image `supabase/postgres`) set the `command` as following:
```
 command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # Prevents Realtime polling queries from appearing in logs
      - -c
      - 'my_application.SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}'
      - -c
      - 'my_application.KONG_URL=${KONG_URL}'
      - -c
      - 'my_application.SITE_URL=${SITE_URL}'
```

The dot notation is explicit required.

Afterwards everywhere in your SQL code you can retrieve the value of the variables like following:
```
SELECT current_setting('my_application.SERVICE_ROLE_KEY');
SELECT current_setting('my_application.KONG_URL');
SELECT current_setting('my_application.SITE_URL');
```

The whole container configuration could look like following:
```
  db:
    container_name: supabase-db
    hostname: db
    image: supabase/postgres:15.1.0.73
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # Prevents Realtime polling queries from appearing in logs
      - -c
      - 'my_application.SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}'
      - -c
      - 'my_application.KONG_URL=${KONG_URL}'
      - -c
      - 'my_application.SITE_URL=${SITE_URL}'
    restart: unless-stopped
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - [YOUR VOLUMES HERE]
```

Note that you have to set the used docker variables in the docker compose environment.

**Reply by yngwi** [reply]
Yes, that is what I would do if I would self-host. Thank you for writing it down!

**Comment by apotheque** [comment]
Managing storage within postgres on different envs is supahard without this feature.

**Comment by ChuckJonas** [comment]
It's honestly hard to believe that such a fundamental feature is missing.  The lack of this feature promotes insecure & fragile coding practices (creating functions which have secrets & environment specific values hard-coded in them).  Especially since the [docs themselves encourage these poor practices](https://supabase.com/docs/guides/functions/schedule-functions)!

1. There should be SQL access for the core supabase "Project Settings" (`Reference ID`, `Project URL`, `API keys`).

2. There should be SQL access for the Edge Function ENV (values set via `supabase secrets set --env-file .env`).  To my surprise, these do not currently show up in the `vault.secrets` as you would expect.

Would love to see this get on the roadmap ASAP!

**Reply by silentworks** [reply]
This is definitely something that is on our roadmap, it is something we have even discussed recently in the team as we too use Supabase for our own projects and have ran into this issue. There are still some security concerns around how some of this work which we are still working on, but this is something we have on our roadmap for sure.

**Reply by UrbanChrisy** [reply]
Hey @silentworks keen for this to be an early q1 item. Also, is GitHub the best place to keep track of this roadmap item?

**Reply by sleakyo** [reply]
@silentworks is this released yet, or are there any additional updates on this? 

We are working with Supabase branching and need this to configure seperate endpoints in the DB functions of our production and development branches.

**Reply by logemann** [reply]
@silentworks +1. Without this, the webhooks feature too is pretty unusable because we cant hardcode the endpoint URL when dealing with different environments like localdev/prod. Of course there are workarounds like  mentioned [here](https://goulet.dev/posts/supabase-webhook-local/) but man, this is a lot of coding just to support local dev.

**Reply by GaryAustin1** [reply]
Silentworks is no longer an employee.  I had heard it was in the works in a discussion with them about the same timeframe, but have seen nothing yet.  Vault is still the best answer when you can select for your variables.

**Reply by lougeo** [reply]
+1 to this feature request. Is there an open ticket we can follow?

**Reply by tecoad** [reply]
I cannot belive that supabase has not figured out this and has just came out of BETA. How can?

**Reply by adamlamaa** [reply]
+1 I am also looking for a way to access the env variables configured for edge functions in my database functions.

**Reply by sweatybridge** [reply]
We now support declaring vault secrets in `config.toml` so you can reference them directly in migration or seed file when applying with `supabase db push --include-seed`. For eg.

- in `.env.local`
```.env
MY_PROJECT_REF="abc"
MY_ANON_KEY="def"
```

- in `supabase/config.toml`
```toml
[db.vault]
my_project_ref = "env(MY_PROJECT_REF)"
my_anon_key = "env(MY_ANON_KEY)"
```

- in `supabase/seed.sql`
```sql
select
  cron.schedule(
    'invoke-function-every-minute',
    '* * * * *', -- every minute
    $$
    select
      net.http_post(
          url:='https://' || (select decrypted_secret from vault.decrypted_secrets where name = 'my_project_ref') || '.supabase.co/functions/v1/function-name',
          headers:=jsonb_build_object(
            'Content-type', 'application/json',
            'Authorization', 'Bearer: ' || (select decrypted_secret from vault.decrypted_secrets where name = 'my_anon_key')
          ),
          body:=concat('{"time": "', now(), '"}')::jsonb
      ) as request_id;
    $$
  );
```

Since these variables are read from vault at runtime, they will not show up in `cron.job` table in plain text.
