### DISCUSSION TITLE
Is it possible to use the realtime server without supabase client?

### DISCUSSION THREAD

**Discussion by smac89** [supabase/supabase#12925] [Questions]
Hey guys, I just want to use supabase for a chat application. I'm basically looking to use a single postgres table to store all chat messages. I already have other tables in my database which are used to manage users, as well as using fusionauth to do authentication.

On my local machine, I've added the docker-compose entry for `realtime`, and I've set it to use my existing database. It starts up with no problem and I'm able to access the frontend at `localhost:4000`:

```yaml
realtime-server:
  depends_on:
    - postgresql
  image: supabase/realtime:v2.6.0
  ports:
    - "4000:4000"
  networks:
    - intranet
  environment:
    PORT: 4000
    DB_HOST: postgresql
    DB_PORT: 5432
    DB_USER: supabase
    DB_PASSWORD: supabase
    DB_NAME: appdb
    DB_ENC_KEY: supabaserealtime
    API_JWT_SECRET: dc447559-996d-4761-a306-f47a5eab1623
    FLY_ALLOC_ID: fly123
    FLY_APP_NAME: realtime
    SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
    ERL_AFLAGS: -proto_dist inet_tcp
    ENABLE_TAILSCALE: "false"
    DNS_NODES: "''"
```

Inside my database I have created a schema called `_realtime` and inside this schema I have a few tables:
![chat_db_diagram](https://user-images.githubusercontent.com/8305511/224133663-74f58e23-6179-4d0c-b991-93bded9fda63.png)

Now that I have those setup, what can I expect to be able to do with this realtime server? Specifically, how do I instruct this server to listen for and publish changes to the `chat_messages` table? And how do I subscribe to those changes? I'm assuming websockets? This is all just to test what is possible.

Thanks for your time.

P.S. my project is written in Go.
