### DISCUSSION TITLE
Unencrypted connection error when locally developing using GoTrue with InBucket

### DISCUSSION THREAD

**Discussion by Nikola-Milovic** [supabase/supabase#13629] [Questions]
Hello everyone, when I try to use docker-compose to develop Supabase locally. When I try to sign up, the signup confirmation email fails as the with the following error

```
{"auth_event":{"action":"user_confirmation_requested","actor_id":"083d388c-351a-4427-81b8-3340608a53de","actor_username":"your_email@gmail.com","log_type":"user","traits":{"provider":"email"}},"component":"api","error":"Error sending confirmation email: unencrypted connection","level":"error","method":"POST","msg":"500: Error sending confirmation mail","path":"/signup","referer":"","remote_addr":"172.20.0.1","time":"2023-04-12T05:54:28Z","timestamp":"2023-04-12T05:54:28Z"}
```

Since this is in development, is there any way to tell the GOTRUE that the TLS is not required? There seem to be no option to set this

```
SMTP_HOST=mail
SMTP_PORT=2500
SMTP_USER=USER
SMTP_PASS=PASSWORD
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@email.com
SMTP_SENDER_NAME=fake_sender_name
```

The `GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED` is not documented but from reading the code, it does not do what I need

```
  mail:
    image: inbucket/inbucket:3.0.3
    ports:
      - 2500:2500  # SMTP
      - 9000:9000  # web interface
      - 1100:1100  # POP3
    networks:
      - default
      
        auth:
    image: supabase/gotrue:v2.47.0
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
      MFA_ENABLED: ${MFA_ENABLED}
    networks:
      - default
```
