### DISCUSSION TITLE
How to connect to postgres database started with `supabase start?`

### DISCUSSION THREAD

**Discussion by michael-land** [supabase/supabase#13945] [Questions]
I would like to start a local 'hasura' service with `docker-compose up -d`, what database host name should i use?

I tried `localhost`, `0.0.0.0`, `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' pg-service`, none of them work.

any help is appreciated 

```yml
version: '3.8'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.23.0
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@localhost:54322/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@localhost:54322/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
```
<img width="1570" alt="CleanShot 2023-04-24 at 22 36 00@2x" src="https://user-images.githubusercontent.com/33362998/234168591-aa0b9c90-c025-4149-b0db-59f4384f1374.png">
