### DISCUSSION TITLE
Disable providers in auth-ui

### DISCUSSION THREAD

**Discussion by kdesimini** [supabase/supabase#14953] [Questions] [answered]
Is there a way to disable providers entirely in the auth-ui library and just use email/password?

**Comment by kdesimini** [comment]
Well, it's hacky but I did it with css. First converted the social layout to horizontal and then targeted on that. (also disabled the providers in supabase)

```css
.supabase-auth-ui_ui-container[direction="horizontal"] {
    display: none !important;
}

.supabase-auth-ui_ui-divider {
    display: none !important;
}
```

![image](https://github.com/supabase/supabase/assets/34429274/961d9f18-92a4-46ac-8c6b-0070e1175a69)
