### DISCUSSION TITLE
Cant't use auth locally with Kakao

### DISCUSSION THREAD

**Discussion by moonkii** [supabase/supabase#16010] [Questions]
Hi!

I wonder if Kakao Login is not yet supported as an external OAuth provider locally?

I wrote the `config.toml` file as follows

```toml
[auth.external.kakao]
enabled = true
client_id = "$SUPABASE_AUTH_KAKAO_CLIENT_ID"
secret = "$SUPABASE_AUTH_KAKAO_SECRET"
redirect_uri = "http://localhost:54321/auth/v1/callback"
```
But when I tried logging in from the browser, I got the following message "Unsupported provider: Provider kakao could not be found"

Even in the description of the configuration file, kakao is missing from the list of external OAuth providers.

```toml
# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
```
