### DISCUSSION TITLE
Flutterflow intergration with self-hosted Supabase

### DISCUSSION THREAD

**Discussion by itseliev** [supabase/supabase#17348] [Questions] [answered]
Hello! Could you please help to connect Flutterflow project to self-hosted Supabase instance?

I have an instance with Supabase and when I try GET link-of-my-supabase.com/rest/v1/ I got an answer 200 with all my tables. All works fine.

But when I try to connect to it from Flutterflow I got nothing. So when I checking logs of supabase and trying get /rest/v1/ I see logs with my requests from my ip. When I trying to connect Flutterflow to my Supabase - no logs. 
Firewall disabled. Tryed aws and gcp and DO - all the same.

Flutterflow's support guys checked it and didn't see any errors from their side.

Maybe you can help me to realize it?

You can try to connect Flutterflow to Supabase with Settings and integrations - scroll down to Intergrations - select Supabase. Then provide link to API and ANON key and push GET SCHEMA button. 

Thank you!

**Comment by itseliev** [comment, marked as answer]
Solved. Flutterflow needs a secure connection to the supabase. So you need setup ssl cert for kong service. Config example:

```
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      KONG_SSL: "on"                                                          # turn on ssl for kong
      KONG_SSL_CERT: /certs/fullchain.pem                       # provide a ssl cert path
      KONG_SSL_CERT_KEY: /certs/privkey.pem                  # provide a ssl private key path
    volumes:
      # https://github.com/supabase/supabase/issues/12661
      - ./volumes/api/kong.yml:/home/kong/temp.yml:ro
      - ./volumes/api/fullchain.pem:/certs/fullchain.pem:ro   # mount a cert to /certs/ in docker container
      - ./volumes/api/privkey.pem:/certs/privkey.pem:ro       # mount a private key 
```

TIP - do not forget chmod 644 for certs
