### DISCUSSION TITLE
resend() does not send an email to Inbucket

### DISCUSSION THREAD

**Discussion by igorlanko** [supabase/supabase#18446] [Questions] [answered]
### Issue
Using `supabase-js` `auth.resend({ type: 'email_change', email: newEmail })` emails are not sent to Inbucket. No visible errors on the client or in Supabase Studio API logs.

### What I have
Added my own behavior for the email change confirmation link with this template `email-change.html`:
```html
<html>
  <body>
      <p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
      <p>
        <a href="{{ .SiteURL }}/auth/verify-otp?token_hash={{ .TokenHash }}&type=email_change">
        Confirm your email
        </a>
    </p>
  </body>
</html>
```

In `config.toml`:
```toml
[auth.email.template.email_change]
subject = "Verify your new Collecta email"
content_path = "./supabase/templates/email-change.html"
```

Then in `+page.server.ts` have this form action to resend:
```ts
const { error: resendEmailConfirmationError } =
  await supabase.auth.resend({
    type: 'email_change',
    email: newEmail
})
```

No errors whatsoever on the SvelteKit side or in Supabase logs. The request returns `200`, but `Inbucket` is just empty. How can I better debug this? Tried restarting docker, supabase instance, it's all the same. Sign up confirmation emails work fine, but specifically the email change with `resend()` just don't work.
