### DISCUSSION TITLE
I can't use SMS(MessageBird) authentication because of `AuthUnknownError`.

### DISCUSSION THREAD

**Discussion by yukiueda0101** [supabase/supabase#18524] [Questions]
In local expo(react native) environment, I tried to use `signInWithOtp` like below, but receive an error.
```javascript
# ref: https://supabase.com/docs/guides/auth/phone-login/messagebird#using-otp-as-a-passwordless-sign-in-mechanism
const { user, error } = await supabase.auth.signInWithOtp({
  phone: '+xxx',
})
```

I receive this error.
```
AuthUnknownError: JSON Parse error: Unexpected character: <
```

I modified `config.toml` to set up MessageBird authentication.
```toml
# ref: https://supabase.com/docs/guides/cli/config
[auth.phone]
enable_signup = true

[auth.sms.messagebird]
enabled = true
originator = "xxx"
access_key = "xxx"
```

Please tell me why I receive this error.

- packages
```javascript
"@supabase/supabase-js": "^2.26.0"
"expo": "^49.0.0"
```
