### DISCUSSION TITLE
Possible to change color on Auth component?

### DISCUSSION THREAD

**Discussion by ashiva** [supabase/supabase#1917] [Questions] [answered]
What's the best way to override the color of the buttons/links in the Supabase Auth component?

I tried attaching a class name and trying to target it with css 

`.supabase > a { color: red; } `

but it didn't work.

**Comment by lokesh-coder** [comment, marked as answer]
This worked for me.

```css
.sbui-auth button {
    background: red;
}
.sbui-auth a{
   color:red;
}
```

It would have been better if theme colors are set with css variables. so that overriding accent color in focus outline, checkbox, hover might becomes easier.
