### DISCUSSION TITLE
Is it possible to cache supabase docker images for supabase/setup-cli?

### DISCUSSION THREAD

**Discussion by caiquecastro** [supabase/supabase#20081] [Feature Requests]
Everytime I run my workflow with the action from supabase/setup-cli It downloads all the images again. Should we add an option to cache the images? Github actions does not have an easy way to do it, but it's possible with some docker save and docker load.

**Comment by MaximusMcCann** [comment]
Pretty please 🙏

**Comment by Sillyvan** [comment]
Would be super useful!

does anyone got a working example?

**Comment by sweatybridge** [comment]
> but it's possible with some docker save and docker load

Question is where is docker save writing to? GHA runners don't support custom persistent disks so we cannot prepare a disk with cached docker images prior to starting the runner. We explored [writing to actions cache](https://github.com/supabase/setup-cli/issues/88#issuecomment-1370519155) before but that turns out to be slower than downloading straight from GHCR.

The other alternative is to self-host your GHA runner with custom volume.

**Comment by riderx** [comment]
This is still taking 50% of my action time, could the action embed already the images?

**Comment by quememo** [comment]
This would be great

**Comment by carlosfarfangalindoNL222** [comment]
Please create an cache option!

**Comment by msmanek** [comment]
bumping this! please do create a cache option :)

**Comment by abdulrabbani00** [comment]
The people have spoken! 

Maybe have a slim image for CI at least just for the DB?

**Comment by gwhitelaw** [comment]
Turns out you can do this in a few tasks with Github Actions. However the data transfer for the cache seems about equal to just running supabase start directly so no real time saved!

```
 # Cache Supabase Docker images
      - name: Cache Supabase Docker images
        id: cache-supabase
        uses: actions/cache@v3
        with:
          path: /tmp/supabase-docker-cache
          key: supabase-docker-${{ runner.os }}-${{ hashFiles('supabase/**') }}
          restore-keys: |
            supabase-docker-${{ runner.os }}-

      # Load Docker images if they were cached
      - name: Load cached Docker images
        if: steps.cache-supabase.outputs.cache-hit == 'true'
        run: |
          for img in /tmp/supabase-docker-cache/*.tar; do
            docker load < $img
          done
          docker images

      # Start Supabase - only pull images if not cached
      - name: Start Supabase
        run: supabase start -x studio,postgres-meta,imgproxy

      # Save Docker images for future runs if not already cached
      - name: Save Docker images to cache
        if: steps.cache-supabase.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/supabase-docker-cache
          docker images | grep supabase | awk '{print $1":"$2}' | xargs -I {} sh -c 'docker save {} > /tmp/supabase-docker-cache/$(echo {} | tr "/" "_" | tr ":" "_").tar'
          ls -la /tmp/supabase-docker-cache/
          ```
