### DISCUSSION TITLE
Failed to link project

### DISCUSSION THREAD

**Discussion by snowmead** [supabase/supabase#20179] [Questions] [answered]
I tried to link my project and push my schema changes but it fails to find the cargo.toml when linking the project.

```
Run supabase link --project-ref $PROJECT_ID
Error: Missing config: open supabase/config.toml: no such file or directory
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

My project is structured by default using the `supabase init` command. So I have the `root-of-project/supabase/cargo.toml` file.

```yaml
name: Push schema changes
on:
  push:
    branches:
        - main

env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    PROJECT_ID: yvnvnxykfjrzbgiavdab

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: supabase/setup-cli@v1
          - run: supabase link --project-ref $PROJECT_ID
          - run: supabase db push
```
