### DISCUSSION TITLE
Configure 'Twilio Verify' SMS provider on self-hosted Supabase instance

### DISCUSSION THREAD

**Discussion by fbele** [supabase/supabase#20557] [Questions]
Hi there,

I have a self-deployed Supabase instance, where I want to to configure "Twilio Verify" SMS provider, but according to Supabase's GoTrue documentation, only "Twilio" can be set as SMS provider:

SMS_PROVIDER - string

Available options are: twilio, messagebird, textlocal, and vonage

Then you can use your twilio credentials:

    SMS_TWILIO_ACCOUNT_SID
    SMS_TWILIO_AUTH_TOKEN
    SMS_TWILIO_MESSAGE_SERVICE_SID - can be set to your twilio sender mobile number

However, if I use Supabase in cloud, I can configure "Twilio Verify" service:

![Twilio Verify](https://github.com/supabase/supabase/assets/33025896/22aaa54d-a7aa-40c0-a502-ccbd46f953f5)

Is it possible to configure "Twilio Verify" SMS provider also in self-hosted instance of Supabase?

Thanks.

**Comment by fbele** [comment]
Fortunately, Supabase is open source and I could find an answer to my question by myself.
If anybody else is wondering how to use Twilio Verify as an SMS provider in a self-hosted instance, you do it by using `twilio_verify` as a value to `GOTRUE_SMS_PROVIDER` environment variable.
You also need to populate the following environment variables with your respective values:
```
      GOTRUE_SMS_TWILIO_VERIFY_ACCOUNT_SID=
      GOTRUE_SMS_TWILIO_VERIFY_AUTH_TOKEN=
      GOTRUE_SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID=
```

This is not documented in official docs of Supabase's GoTrue.

**Reply by crrrr30** [reply]
For me, removing `VERIFY_` from the final three env var names you mentioned worked.

**Reply by Wilson13** [reply]
This is what I had to add to make this work:

```yaml
GOTRUE_SMS_PROVIDER: ${SMS_PROVIDER}
GOTRUE_SMS_TWILIO_VERIFY_ACCOUNT_SID: ${SMS_TWILIO_VERIFY_ACCOUNT_SID}
GOTRUE_SMS_TWILIO_VERIFY_AUTH_TOKEN: ${SMS_TWILIO_VERIFY_AUTH_TOKEN}
GOTRUE_SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID: ${SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID}
```

**Comment by mac-lisowski** [comment]
I'll leave the message here for other folks looking for this information, that for self hosted supabase auth version `supabase/gotrue:v2.173.0` I had to set env variables below:

For **messaging service**
```yaml
GOTRUE_SMS_PROVIDER: ${SMS_PROVIDER} # set: twilio
GOTRUE_SMS_TWILIO_ACCOUNT_SID: ${SMS_TWILIO_ACCOUNT_SID}
GOTRUE_SMS_TWILIO_AUTH_TOKEN: ${SMS_TWILIO_AUTH_TOKEN}
GOTRUE_SMS_TWILIO_MESSAGE_SERVICE_SID: ${SMS_TWILIO_MESSAGE_SERVICE_SID}
```

For **verify service**
```yaml
GOTRUE_SMS_PROVIDER: ${SMS_PROVIDER} # set: twilio_verify
GOTRUE_SMS_TWILIO_VERIFY_ACCOUNT_SID: ${SMS_TWILIO_VERIFY_ACCOUNT_SID}
GOTRUE_SMS_TWILIO_VERIFY_AUTH_TOKEN: ${SMS_TWILIO_VERIFY_AUTH_TOKEN}
GOTRUE_SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID: ${SMS_TWILIO_VERIFY_MESSAGE_SERVICE_SID}
```
