### DISCUSSION TITLE
Any way to localize email templates on a self-hosted (docker) supabase instance?

### DISCUSSION THREAD

**Discussion by sergeykorablin** [supabase/supabase#20673] [Questions] [answered]
Hi!
Is there a way to change email templates, such as verification, invitation, magic link, etc., on a self-hosted Supabase instance? 
I found in this article (https://dev.to/chronsyn/self-hosting-with-supabase-1aii) that GoTrue can use some environment variables (GOTRUE_MAILER_TEMPLATES_INVITE, GOTRUE_MAILER_TEMPLATES_CONFIRMATION) that point to URLs with templates. 
However, in my case, they don't seem to work.

**Comment by JLAcostaEC** [comment]
Where do the template addresses point? They can only be valid URLs, they cannot be the template itself and if you are hosting the template using a Supabase Bucket you have to correctly reference the instance within docker.

**Reply by sergeykorablin** [reply, marked as answer]
Thank for your reply. I double-checked my settings and templates, and now it works! 😰️😂️

For those who are facing the same problem, here are the changes I made:
`docker-compose.yml`
```yaml
  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.132.3

    environment:

      # Email templates 
      GOTRUE_MAILER_TEMPLATES_INVITE: ${MAILER_TEMPLATES_INVITE}
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: ${MAILER_TEMPLATES_CONFIRMATION}
      GOTRUE_MAILER_TEMPLATES_RECOVERY: ${MAILER_TEMPLATES_RECOVERY}
      GOTRUE_MAILER_TEMPLATES_MAGIC_LINK: ${MAILER_TEMPLATES_MAGIC_LINK}
      GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE: ${MAILER_TEMPLATES_EMAIL_CHANGE}

      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: ${MAILER_SUBJECTS_CONFIRMATION}
      GOTRUE_MAILER_SUBJECTS_RECOVERY: ${MAILER_SUBJECTS_RECOVERY}
      GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: ${MAILER_SUBJECTS_MAGIC_LINK}
      GOTRUE_MAILER_SUBJECTS_EMAIL_CHANGE: ${MAILER_SUBJECTS_EMAIL_CHANGE}
      GOTRUE_MAILER_SUBJECTS_INVITE: ${MAILER_SUBJECTS_INVITE}

```
`.env`
```env
MAILER_TEMPLATES_INVITE="https://example.com/templates/invite.html"
MAILER_TEMPLATES_CONFIRMATION="https://example.com/templates/confirm.html"
MAILER_TEMPLATES_RECOVERY="https://example.com/templates/recovery.html"
MAILER_TEMPLATES_MAGIC_LINK="https://example.com/templates/magic-link.html"
MAILER_TEMPLATES_EMAIL_CHANGE="https://example.com/templates/email-change.html"

MAILER_SUBJECTS_INVITE="..."
MAILER_SUBJECTS_CONFIRMATION="..."
MAILER_SUBJECTS_RECOVERY="..."
MAILER_SUBJECTS_MAGIC_LINK="..."
MAILER_SUBJECTS_EMAIL_CHANGE="..."
```

**Reply by glendell03** [reply]
@sergeykorablin Hi, I tried `GOTRUE_MAILER_TEMPLATES_MAGIC_LINK: ${MAILER_TEMPLATES_MAGIC_LINK}` but it's not working for me I am receiving the default email template.

**Reply by sergeykorablin** [reply]
@glendell03 make sure you have provided MAILER_TEMPLATES_MAGIC_LINK with a working link in your `.env` file

**Comment by AntonOfTheWoods** [comment]
So that would mean that you would need an instance of auth per language???

**Reply by sergeykorablin** [reply]
Maybe it's better to use https://supabase.com/docs/guides/auth/auth-hooks/send-email-hook

**Comment by fpaupier** [comment]
I faced the same challenge and added a small sidecar nginx container to serve my own mail templates.

In my supabase `docker-compose.yml`

```yaml
  email-template-server:
    image: nginx:alpine
    volumes:
      - ./templates:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
```
I have in my `/templates` dir my `invite.txt`  and in my `.env` I added the following lines

In the existing supabase, `auth` service I added the two env vars you suggested @sergeykorablin, thanks.
```yml
      # Email templates
      GOTRUE_MAILER_TEMPLATES_INVITE: ${MAILER_TEMPLATES_INVITE}
      GOTRUE_MAILER_SUBJECTS_INVITE: ${MAILER_SUBJECTS_INVITE}
```

and in my env I define the url to the template

```env
MAILER_TEMPLATES_INVITE="http://email-template-server:80/invite.txt"
MAILER_SUBJECTS_INVITE="You're invited to join MyOrg"
```

quite cumbersome since the `auth` service expect URL,  but it works.
