### DISCUSSION TITLE
Customizing emails - followed docs but its not working

### DISCUSSION THREAD

**Discussion by magick93** [supabase/supabase#20753] [Questions]
Hello

I"m following the guides on https://supabase.com/docs/guides/cli/customizing-email-templates.
I'm trying to customize the email confirmation email. 

I've added the following to the `config.toml`:
```
[auth.email.template.confirmation]
subject = "Confirm you email address"
content_path = "./supabase/templates/confirmation-email.html"
```

There seems to be a file check - if I modify the `content_path` from what is above, I get a nice error, eg:
```
failed to read file info: stat ./supabase/templates/confirmation-email.html-test: no such file or directory
```

So I'm _somewhat_ confident that supabase is finding my email template. 

However, the customized email is never sent. 

Any help is appreciated.

**Comment by stursby** [comment]
@magick93 Same here. I built a custom confirmation email, and it lives in my Git Repo at `./supabase/templates/confirm.html` with the following (same as yours) TOML config:

```toml
# Uncomment to customize email template
[auth.email.template.confirmation]
subject = "[CUSTOM TEST] Confirm"
content_path = "./supabase/templates/confirm.html"
```

I've also connected my Supabase project to the GitHub repo so it should, in theory, be able to find those files 🤷‍♂️

Did you end up solving it?

**Reply by sp88011** [reply]
Same Problem here. Anyone have any luck?

**Reply by muhammad-bilal-ali-khokhar** [reply]
having same issue

**Comment by magick93** [comment]
I was able to resolve this by running `supabase stop` then `supabase start`.

**Reply by sp88011** [reply]
Thank you, this solves it for me too.

**Comment by jonathanlal** [comment]
damn this is annoying... Those files are only relevant for local right? Since you edit the email templates through the dashboard.... Stopping supabase locally seemed to help but why? Don't want to have to stop it everytime i push something

**Comment by icopp** [comment]
Same problem here. `supabase stop && supabase start` doesn't help. I know the docker image can see the files as they show up as valid binds on the `supabase_kong_(projectname)` container and I can see the mounted files inside the container's file structure. There are no error logs or anything else to indicate why it's not working.

**Comment by denizkenan** [comment]
Same issue.
I can see that my config picks up subject correctly but ignores template content_path.

**Comment by denizkenan** [comment]
if template has any issues (typo, unsupported tag etc..), it falls back to the default template.

use a minimal template such as:
`confirmation.html`:
``` 
<h2>Sign up confirmation</h2>

<p>Thank you for signing up! To complete the registration process and gain access to our platform, please click the link below to confirm your account:</p>

<p><a href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=email">Confirm your email address</a></p>
```

to test the config first.

**Reply by Amirulmuuminin** [reply]
really helpfull explaination. i tested and it works

**Comment by marius-se** [comment]
We tested @denizkenan 's solution (using a minimal html template), but for us it still renders the default template.

**Comment by wodndb** [comment]
I used wrong template config `[auth.email.template.invite]` because it is default in `config.toml`.
Please check your email template config in config.toml if you didn't change `auth.email.template.invite` to `auth.email.template.confirmation`.

1. change template config to `auth.email.template.confirmation` in `config.toml`
```toml
# Default template config was `auth.email.template.invite`
[auth.email.template.confirmation]
subject = "You have been invited"
content_path = "./supabase/templates/confirmation.html"
```
2. Add template file to `./supabase/templates/confirmation.toml`
```html
<html>
  <body>
    <p>Follow this link to confirm your user:</p>
    <p>
      <a
        href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=email"
        >Confirm your email</a
      >
    </p>
  </body>
</html>
```
3. Restart supabase cli
```bash
supabase stop
supabase start
```

**Comment by dhananroy** [comment]
# Supabase Custom Email Templates Setup Guide

This guide shows how to set up custom email templates for Supabase GoTrue authentication emails using Docker Compose.

## Problem Solved
By default, Supabase uses basic email templates for authentication emails (magic links, password reset, etc.). This solution allows you to use custom HTML templates with your own branding and styling.

## Solution Overview
- Use nginx to serve template files locally within Docker network
- Configure GoTrue to fetch templates from the nginx service
- Support for all email types: magic link, confirmation, recovery, invite, email change

## File Structure
```
your-project/
├── docker/
│   └── docker-compose.yml
├── supabase/
│   └── templates/
│       ├── magic_link.html
│       ├── confirmation.html
│       ├── recovery.html
│       ├── invite.html
│       └── email_change.html
└── .env
```

## Docker Compose Configuration

### Add Template Server Service
```yaml
services:
  # Template server to serve email templates
  template-server:
    image: nginx:alpine
    container_name: supabase-templates
    volumes:
      - ../supabase/templates:/usr/share/nginx/html:ro
    networks:
      - default
    restart: unless-stopped

  # Update your existing auth service
  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.177.0
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9999/health"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
      template-server:  # Add dependency on template server
        condition: service_started
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      
      # Email template URLs (GOTRUE_ prefix is required)
      GOTRUE_MAILER_TEMPLATES_MAGIC_LINK: "http://template-server/magic_link.html"
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: "http://template-server/confirmation.html"
      GOTRUE_MAILER_TEMPLATES_RECOVERY: "http://template-server/recovery.html"
      GOTRUE_MAILER_TEMPLATES_INVITE: "http://template-server/invite.html"
      GOTRUE_MAILER_TEMPLATES_EMAIL_CHANGE: "http://template-server/email_change.html"
      
      # Optional: Enable debug logging
      GOTRUE_LOG_LEVEL: "debug"
      
      # Your existing SMTP and other settings...
```

## Email Template Examples

### Magic Link Template (`magic_link.html`)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Magic Link</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .title {
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        .content {
            color: #666;
            line-height: 1.6;
            margin-bottom: 30px;
        }
        .cta-button {
            display: inline-block;
            background-color: #4CAF50;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
            margin: 20px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">Your App Name</div>
        </div>
        
        <h1 class="title">Welcome back!</h1>
        
        <div class="content">
            <p>Hello,</p>
            <p>Click the button below to securely log into your account:</p>
            
            <div style="text-align: center;">
                <a href="{{ .ConfirmationURL }}" class="cta-button">
                    Log In to My Account
                </a>
            </div>
            
            <p>Or copy and paste this link into your browser:</p>
            <p style="word-break: break-all; background: #f8f9fa; padding: 10px; border-radius: 4px;">
                {{ .ConfirmationURL }}
            </p>
            
            <p>This link will expire in a few minutes for security reasons.</p>
            <p>If you didn't request this login link, please ignore this email.</p>
        </div>
        
        <div class="footer">
            <p>This email was sent to {{ .Email }} from {{ .SiteURL }}</p>
        </div>
    </div>
</body>
</html>
```

### Password Recovery Template (`recovery.html`)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Your Password</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .title {
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        .content {
            color: #666;
            line-height: 1.6;
            margin-bottom: 30px;
        }
        .cta-button {
            display: inline-block;
            background-color: #ff6b6b;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
            margin: 20px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">Your App Name</div>
        </div>
        
        <h1 class="title">Reset Your Password</h1>
        
        <div class="content">
            <p>Hello,</p>
            <p>We received a request to reset the password for your account.</p>
            
            <div style="text-align: center;">
                <a href="{{ .ConfirmationURL }}" class="cta-button">
                    Reset Password
                </a>
            </div>
            
            <p>Or copy and paste this link into your browser:</p>
            <p style="word-break: break-all; background: #f8f9fa; padding: 10px; border-radius: 4px;">
                {{ .ConfirmationURL }}
            </p>
            
            <p>This link will expire in 24 hours for security reasons.</p>
            <p>If you didn't request a password reset, please ignore this email and your password will remain unchanged.</p>
        </div>
        
        <div class="footer">
            <p>This email was sent to {{ .Email }} from {{ .SiteURL }}</p>
        </div>
    </div>
</body>
</html>
```

### Email Confirmation Template (`confirmation.html`)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Email</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: white;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }
        .title {
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        .content {
            color: #666;
            line-height: 1.6;
            margin-bottom: 30px;
        }
        .cta-button {
            display: inline-block;
            background-color: #007bff;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
            margin: 20px 0;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            color: #999;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo">Your App Name</div>
        </div>
        
        <h1 class="title">Welcome! Please confirm your email</h1>
        
        <div class="content">
            <p>Hello,</p>
            <p>Thanks for signing up! Please click the button below to confirm your email address and activate your account:</p>
            
            <div style="text-align: center;">
                <a href="{{ .ConfirmationURL }}" class="cta-button">
                    Confirm Email Address
                </a>
            </div>
            
            <p>Or copy and paste this link into your browser:</p>
            <p style="word-break: break-all; background: #f8f9fa; padding: 10px; border-radius: 4px;">
                {{ .ConfirmationURL }}
            </p>
            
            <p>If you didn't create an account, please ignore this email.</p>
        </div>
        
        <div class="footer">
            <p>This email was sent to {{ .Email }} from {{ .SiteURL }}</p>
        </div>
    </div>
</body>
</html>
```

## Available Template Variables

All templates have access to these variables:

- `{{ .SiteURL }}` - Your application's site URL
- `{{ .Email }}` - The user's email address
- `{{ .ConfirmationURL }}` - The action URL (magic link, confirmation, etc.)
- `{{ .NewEmail }}` - New email address (only in email change templates)

## Deployment Steps

1. **Create the directory structure**:
   ```bash
   mkdir -p supabase/templates
   ```

2. **Add your custom HTML templates** to `supabase/templates/`

3. **Update your docker-compose.yml** with the template-server service and environment variables

4. **Deploy the changes**:
   ```bash
   docker-compose down
   docker-compose up -d
   ```

5. **Verify templates are working**:
   ```bash
   # Check if template server is accessible
   docker-compose exec auth wget -O- http://template-server/magic_link.html
   
   # Check environment variables
   docker-compose exec auth env | grep MAILER
   
   # Monitor logs during email sending
   docker-compose logs auth -f
   ```

## Troubleshooting

### Templates not loading
- Ensure `GOTRUE_` prefix is used for environment variables
- Check that template-server service is running
- Verify template files exist in the correct directory
- Check container logs for template loading errors

### Template variables not working
- Use double curly braces: `{{ .VariableName }}`
- Ensure proper HTML escaping
- Check template syntax is valid

### Styling issues
- Use inline CSS for better email client compatibility
- Test templates in multiple email clients
- Keep CSS simple and avoid complex layouts

## Key Learnings

1. **GoTrue expects URLs, not file paths** - Templates must be served via HTTP
2. **GOTRUE_ prefix is required** for environment variables in newer versions
3. **nginx approach is reliable** for serving templates within Docker network
4. **Template variables use Go template syntax** with double curly braces
5. **Debug logging helps** troubleshoot template loading issues

This setup provides a maintainable way to customize all Supabase authentication emails with your own branding and styling.
