### DISCUSSION TITLE
Github action: supabase link with ipv6 enabled issue

### DISCUSSION THREAD

**Discussion by henrik-web3** [supabase/supabase#20955] [Questions] [answered]
So recently it seems our organisation was upgraded to ipv6 over ipv4.
As a consequence our Github Action which runs a supabase link & pushes migrations to our remote Supabase instance stopped working with:

`Error: failed to connect to host=db.***.supabase.co user=postgres database=postgres: dial error (dial tcp [2a05:d014:1c06:5f04:b7e1:419f:b9b7:fa39]:6543: connect: network is unreachable)
 `
Since this was working fine with ipv4, we know what the issue is and even have some resolution suggestions as per https://supabase.com/blog/ipv6

However, none of this seems to address how we can fix this from the remote connection point of view while running in Github actions.
We've tried to add some environment variables to address the problem, but so far without luck.

Our Github action looks like this:

```
name: Deploy Supabase Migrations to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      SUPABASE_AUTH_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_GOOGLE_CLIENT_ID }}
      SUPABASE_AUTH_GOOGLE_SECRET: ${{ secrets.SUPABASE_AUTH_GOOGLE_SECRET }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PRODUCTION_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}
      SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.28.3

      - name: Link action run DB to Supabase prod and push new migrations
        run: |
          supabase link --project-ref $SUPABASE_PRODUCTION_PROJECT_ID
          supabase db push
        env:
          SUPABASE_URL: postgres://postgres.$SUPABASE_PRODUCTION_PROJECT_ID@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
          SUPABASE_USE_CONNECTION_POOLING: true
```

The last two env options have been added to try and resolve the issues, but they did not improve the situation.

Has anyone else seen this same issue and found a resolution?

**Comment by GaryAustin1** [comment, marked as answer]
From here:  https://github.com/orgs/supabase/discussions/17817

'Do I need to make any changes if I am using the CLI?'

`If you are using a version before 1.136.3, please upgrade to a later version of the CLI and run supabase link. If you haven’t run supabase link since 1st January 2024, please run it again after upgrading. This will enable the CLI to communicate to the database from IPv4 only environments because the communication happens via Supavisor. This change is required if you are using from the CLI from an environment without IPv6 support, like Github actions or possibly from your home network.`

There are also mentions of fixes/issues there with github actions.
Sorry if that is repeating something you tried as I don't use this myself.

**Reply by henrik-web3** [reply]
I can confirm that upgrading to the version mentioned (1.136.3) worked!
Thanks Gary, for the speedy resolution!

**Comment by venku122** [comment]
I am getting this same error using `1.153.4`
Has there been a regression?

```
name: Deploy Migrations to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          # Supabase CLI version should match package.json
          version: 1.153.4

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
```

```
Run supabase link --project-ref $SUPABASE_PROJECT_ID
  supabase link --project-ref $SUPABASE_PROJECT_ID
  shell: /usr/bin/bash -e {0}
  env:
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
    SUPABASE_PROJECT_ID: ***
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [[2](https://github.com/cedar-build/cedar-build/actions/runs/8693326817/job/23839866761#step:4:2)600:1f1c:f9:4d0c:f148:d217:11c:cf75]:5432: connect: network is unreachable)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```
