### DISCUSSION TITLE
Local development, session is null after successful auth with github

### DISCUSSION THREAD

**Discussion by adngdb** [supabase/supabase#21144] [Questions] [answered]
Hi,

I have a problem with auth on my local setup: the session returned by supabase is always `null`, even though the authentication process seems to be working fine. It works fine in the production build. I'm using the supabase CLI, the supabase.js library, and svelte kit but with ssr disabled. I use github as my auth provider.

As far as I can tell, the auth process works fine: github tells me that I logged in, the supabase auth docker container logs shows that I logged in. There are no errors anywhere in my console or in logs. However, calls to `supabase.auth.getSession()` always return `null`, and thus my user is never logged in in my app. `onAuthStateChange` never receives a `SIGN_IN` event, only the `INITIAL_SESSION` event. 

[Edit] Versions are:
@supabase/supabase-js: 2.39.3
Supabase CLI: 1.142.2

Here's what I believe is relevant code and config.

`config.toml`
```toml
[auth]
enabled = true
site_url = "http://localhost:5173/"
additional_redirect_urls = ["http://localhost:5173/"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_manual_linking = false

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
```

Client creation:
```ts
import { createClient } from '@supabase/supabase-js';
import type { Database } from '$lib/database.types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export default createClient<Database>(supabaseUrl, supabaseAnonKey);
```

Sign in function:
```ts
    async function signIn() {
        let { data, error } = await db.auth.signInWithOAuth({
            provider: 'github',
        });
    }
```

`+layout.svelte`
```svelte
<script lang="ts">
    db.auth.onAuthStateChange(async (_event, _session) => {
        console.debug(_event); // Only ever shows `INITIAL_SESSION`
        console.debug(_session); // Always shows `null`
    });
</script>
```

I've been reading docs and forums, trying everything I could think off, for the last two days and I just don't get it. Please help! :pray:
