### DISCUSSION TITLE
Customizing Emails by Language

### DISCUSSION THREAD

**Discussion by TheOtherBrian1** [supabase/supabase#21227] [Troubleshooting]
_This is a copy of a troubleshooting article on Supabase's docs site. It may be missing some details from the original. View the [original article](https://supabase.com/docs/guides/troubleshooting/customizing-emails-by-language-KZ_38Q)._

When you register a user, you can create meta-data about them.

Creating meta-data with the JS-Client's [signUp function](https://supabase.com/docs/reference/javascript/auth-signup?example=sign-up-with-additional-user-metadata)

```javascript
const { data, error } = await supabase.auth.signUp({
  email: 'email@some_[email.com](http://email.com/)',
  password: 'example-password',
  options: {
    data: {
      first_name: 'John',
      last_name: 'Doe',
      age: 27,
    },
  },
})
```

The above example creates a user entry that includes information about their name and age. The data is stored in the auth.users table in the `auth.raw_user_meta_data` column. You can view it in the auth schema with the [SQL Editor](https://supabase.com/dashboard/project/_/editor).

It can be accessed in a project's [Email Templates](https://supabase.com/dashboard/project/_/auth/templates). Below is an example:

```html
<h2>Hello, {{ .Data.first_name }} {{ .Data.last_name }}!</h2>

<p>Follow this link to confirm your account:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm your account</a></p>
```

If you need to update a user's meta-data, you can do so with the [`updateUser`](https://supabase.com/docs/reference/javascript/auth-updateuser?example=update-the-users-metadata) function.

The meta-data can be used to store a user's language preferences. You could then use "if statements" in the email template to set the response for a specific language:

```html
{{if eq .Data.language "en" }}
<h1>Welcome!</h1>
{{ else if eq .Data.language "pl" }}
<h1>Witamy!</h1>
{{ else }}
<h1>chuS'ugh, tera' je (Klingon)</h1>
{{end}}
```

Supabase uses the [Go Templating Language](https://pkg.go.dev/text/template) to render emails. It has advanced features for conditions that you may want to [explore](https://gohugo.io/templates/introduction/). For more examples, there is a [GitHub discussion](https://github.com/supabase/gotrue/issues/80#issuecomment-1552264148) that discusses advanced language templates.

**Comment by ropez** [comment]
Does this also work for email subject heading?

**Reply by AvaPL** [reply]
Yes, it does. Example from my `config.toml`:

```toml
[auth.email.template.confirmation]
subject = "{{if eq .Data.language \"pl\"}}Potwierdź swój e-mail{{else}}Confirm your email{{end}}"
content_path = "./supabase/templates/confirmation.html"
```

**Comment by spacecharly** [comment]
There's a small typo, it could be .Data.language instead of .Data.langauge
> 
> ```
> {{if eq .Data.language "en" }}
>      <h1>Welcome!</h1>
> {{ else if eq .Data.language "pl" }}
>      <h1>Witamy!</h1>
> {{ else }}
>      <h1>chuS'ugh, tera' je (Klingon)</h1>
> {{end}}
> ```

For those used to Handlebars, keep in mind that Supabase uses the Go template syntax, without # in front of the if statement.

**Comment by AvaPL** [comment]
Thank you for preparing this page! Could you also add an information about subject templating, please? For example (sorry for no Klingon):
```toml
[auth.email.template.confirmation]
subject = "{{if eq .Data.language \"pl\"}}Potwierdź swój e-mail{{else}}Confirm your email{{end}}"
content_path = "./supabase/templates/confirmation.html"
```

Also, two nitpicks:
1. Why is the email used in the example so weird? `email@some_[email.com](http://email.com/)` Could it be simplified?
2. Suggesting that `age` should be persisted in the metadata is suboptimal. Nobody wants to run a cronjob every user's birthday to increment the age 😉 Maybe just put the `language` here instead?
