### DISCUSSION TITLE
Enable Connection Pooler in local dev environment

### DISCUSSION THREAD

**Discussion by sp88011** [supabase/supabase#21264] [Questions]
After a while, I'm getting this error in my local environment which I believe is related to there being too many open connections. When I restart Docker, everything works fine.

`PostgresError: remaining connection slots are reserved for non-replication superuser connections
    at Socket.emit (node:events:519:28)`

How can I enable connection pooling locally? Or is there another solution to my problem?

I followed the steps here to set up my local environment (https://supabase.com/docs/guides/cli/local-development) - but nowhere does it mention anything about connection pooling locally...

I found a docker imagine for supavisor, but honestly I don't know much about docker and how I would integrate this file into my current "stack" of docker images that are running once I do `supabase init`

**Comment by silentworks** [comment]
Are you using the Supabase CLI? if you are there should be a section for `db.pooler` in the `config.toml` file.
![image](https://github.com/supabase/supabase/assets/79497/fa76b249-d8b9-4cd6-9457-fb932faab7af)

**Reply by shawnmclean** [reply]
`PostgresError: Tenant or user not found`

Any idea what else I need to do to connect to the db via the pooler?

My conn string looks like this: `POSTGRES_URL="postgresql://postgres:postgres@localhost:54329/postgres"`

All I did was swap the port. Is that correct?

**Reply by silentworks** [reply]
Yes that should do it. By any chance are you using Prisma or something like that?

**Reply by shawnmclean** [reply]
Drizzle ORM, thats throwing the PGError.

**Reply by m-shaka** [reply]
I used `psql` cli but got the same error: `Tenant or user not found`.
```bash
psql -h 0.0.0.0 -p 54329 -U postgres -W postgres
```

Here is my config
```toml
[db.pooler]
enabled = true
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100
```
