### DISCUSSION TITLE
Supabase Terraform with github actions and branching

### DISCUSSION THREAD

**Discussion by owain-stratton** [supabase/supabase#21971] [Questions] [answered]
Hi There, I've been setting up supabase branching via the example in this repo https://github.com/supabase/supabase-action-example/tree/main. When the actions run on PR in the project I get the following error: 

```
  with supabase_branch.new[0],
  on branches.tf line 23, in resource "supabase_branch" "new":
  23: resource "supabase_branch" "new" {

Unable to enable branching, got status 406: {"message":"Failed to retrieve
project integration"}
```
The error message is descriptive and correct, the current supabase project does not have branching enabled 😅 

I'm a little confused from the branching setup in the UI. It states that, one requires a `supabase` directory in the repo, however, we have ours inside a package of a monorepo, and two when setting up branching in the supbase UI it requires github connection in order to track branches. 

I would like to understand if it's possible to disable the default behaviour of supabase branching and use the actions from the example with terraform. Trying to understand how to get that example working for us but I need some guidance please.

**Comment by sweatybridge** [comment]
> when setting up branching in the supbase UI it requires github connection in order to track branches

Sorry to hear that. This was accidentally disabled by our platform api a few weeks ago. We will release a patch so that branches can be enabled by terraform provider directly.

> It states that, one requires a supabase directory in the repo, however, we have ours inside a package of a monorepo

Currently the path to `supabase` directory is only configurable via github connection. But I can look into adding supporting that via terraform early next week.

**Reply by owain-stratton** [reply]
@sweatybridge thanks for your response and it's great to hear we'll be able to use terraform as per the example repo soon! I noticed you created this [issue](https://github.com/supabase/terraform-provider-supabase/issues/52), let me know if there is any way I can assist 👍

**Reply by sweatybridge** [reply, marked as answer]
Actually on second thought, monorepo should be possible without any provider changes. This is because branches are created from GitHub action instead of the Supabase integration. There are few changes you need to make to the example action.

1. Replace any reference to [supabase/remotes](https://github.com/supabase/supabase-action-example/blob/main/.github/workflows/preview.yaml#L24) directory with the path to your subdirectory, for eg. `nested/supabase/remotes`
2. Pass `--workdir nested` flag to invocation of [supabase command](https://github.com/supabase/supabase-action-example/blob/main/.github/workflows/preview.yaml#L70), for e.g. `supabase link --workdir nested --project-ref ${{ needs.apply.outputs.ref }}`

Let me know if you run into any other issues configuring it.

**Reply by owain-stratton** [reply]
@sweatybridge In my gh actions workflow I was already referencing the subdirectory where the terraform remotes exist, however the error I get is from the `apply` step in the action. See output

```
Error: Client Error

  with supabase_branch.new[0],
  on branches.tf line 23, in resource "supabase_branch" "new":
  23: resource "supabase_branch" "new" {

Unable to enable branching, got status 500: {"message":"Failed to get GitHub
branch","errorEventId":"6bc4d6[68](https://github.com/hybridity-ai/hybridity/actions/runs/8536531993/job/23385225962?pr=9#step:5:69)b69a4913abf8b34571c18acb"}
Error: Process completed with exit code 1.
```

We're using turborepo and have stored the terraform configs in `packages/terraform/supabase/remotes` and I'll add the workflow below

```yaml
name: DB Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main
      - develop

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      TF_VAR_linked_project: ${{ secrets.PRODUCTION_PROJECT_ID }}
      TF_VAR_git_branch: ${{ github.head_ref }}
      TF_CLI_ARGS_apply: -target=supabase_settings.preview
    defaults:
      run:
        working-directory: packages/terraform/supabase/remotes
    outputs:
      db_user: ${{ steps.branch.outputs.user }}
      db_pass: ${{ steps.branch.outputs.password }}
      db_host: ${{ steps.branch.outputs.host }}
      db_port: ${{ steps.branch.outputs.port }}
      jwt_secret: ${{ steps.branch.outputs.jwt_secret }}
      ref: ${{ steps.branch.outputs.id }}
      status: ${{ steps.branch.outputs.status }}
      version: ${{ steps.branch.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
      - id: branch
        run: |
          terraform output -json branch_database \
          | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" \
          >> "$GITHUB_OUTPUT"

      - if: github.event.action == 'closed'
        run: terraform apply -auto-approve -no-color -destroy

  migrate:
    needs: apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/app-db
    if: github.event.action != 'closed'
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ needs.apply.outputs.db_pass }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          max_attempts: 10
          command: supabase link --workdir packages/app-db --project-ref ${{ needs.apply.outputs.ref }}

      - name: Supabase DB Reset
        run: supabase db reset --linked
```

I hope this helps 😅
