### DISCUSSION TITLE
Where to find supabase keys for local development

### DISCUSSION THREAD

**Discussion by thiagodebastos** [supabase/supabase#2231] [Questions] [answered]
I've managed to initialise a local development instance via `supabase init`. However, I have lost the credentials initially printed out at the end of the script. How can I get those credentials again?

**Comment by thiagodebastos** [comment, marked as answer]
Apologies, I've not used these discussions on gh much, I think I found a similar question that may point to a solution (https://github.com/supabase/supabase/discussions/1029).

SOLUTION:
The anon and service keys can be found in `.supabase/kong/kong.yml`. Scroll down to the end of the file and the keys are under:
```yml
consumers:
  - username: 'private-key'
    keyauth_credentials:
      - key: ANON_KEY
      - key: SERVICE_KEY
```
