### DISCUSSION TITLE
How do I get custom auth hook to execute in the local development environment

### DISCUSSION THREAD

**Discussion by VimVoyager** [supabase/supabase#22600] [Questions]
I am working on an app with Supabase and Svelte and currently working on Role Based Access Control. I used the guide in the Supabase docs to implement it. (https://supabase.com/docs/guides/auth/custom-claims-and-role-based-access-control-rbac). 

I managed to get it working on the remote supabase project, but not on the local development environment. I have configured the hook to the `config.toml` here:

```toml
# https://supabase.com/docs/guides/auth/auth-hooks#local-development
# This hook runs before a token is issued and allows you to add additional claims based on the authentication method used.
[auth.hook.custom_access_token]
enabled = true
uri = "pg-functions://postgres/public/custom_access_token_hook"
```

But the hook is not executing, Is there anything I have missed when working in the local development environment that I need to set up for this to work, because RBAC is really important in this project and if I cannot get it to work in the local development environment I will need to switch to a different tech stack away from supabase. I am using supabase CLI version 1.153.4.
