### DISCUSSION TITLE
`supabase db push` in GitHub Action prompting for input and exiting successfully

### DISCUSSION THREAD

**Discussion by maxbeatty** [supabase/supabase#26366] [Questions]
We want to push our migrations to the remote database automatically in a GitHub Action: 

```yaml
- name: Database migrations
  run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            supabase db push
          else
            supabase db push --dry-run
          fi
  env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
```

The action appears successful:

```sh
Run supabase link --project-ref $SUPABASE_PROJECT_ID
Connecting to remote database...
Failed to save database password: failed to set credentials: The name org.freedesktop.secrets was not provided by any .service files
Finished supabase link.
Connecting to remote database...
Do you want to push these migrations to the remote database?

 • 20240510163628_my_cool_migration.sql

 [Y/n] Applying migration 20240510163628_my_cool_migration.sql...
Finished supabase db push.
```

But the migration was not applied 😿 

1. Is prompting for confirmation expected in a CI environment? 
2. If so, how can we not prompt and just assume 'yes'?
3. Why did this exit successfully when the migration was not applied?
