### DISCUSSION TITLE
How to deploy edge functions to docker hosted runtime?

### DISCUSSION THREAD

**Discussion by crackedbeefcake** [supabase/supabase#27009] [Questions]
Hi,
I have a selfhosted docker compose setup with all the supabase database, auth, etc. services running on an ubuntu instance.
I already have the edge runtime up and running.

but how do i deploy to it? 
- do I need to build the docker image `supabase/edge-runtime` with the functions copied into it OR do i send the functions in once that image is running?

and how do i setup my cli to target that instance more broadly?

all the best, help is appreciated.
Finn

```
  functions:
    container_name: supabase-edge-functions
    image: supabase/edge-runtime:v1.32.0
    restart: unless-stopped
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_DB_URL: postgresql://#{POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      # TODO: Allow configuring VERIFY_JWT per function. This PR might help: https://github.com/supabase/cli/pull/786
      VERIFY_JWT: "${FUNCTIONS_VERIFY_JWT}"
    volumes:
      - ./volumes/functions:/home/deno/functions:Z
    command:
      - start
      - --main-service
      - /home/deno/functions/main
    networks:
      - supabase
```

**Comment by ryseek** [comment]
Hey 👋 
I am in similar situation having the supabase running on VPS  and looking into using edge functions.

> * do I need to build the docker image `supabase/edge-runtime` with the functions copied into it OR do i send the functions in once that image is running?

I think both will work, but building the container each time might be too much of a work. Once you mounted volume to `/home/deno/functions` you can place the functions there and runtime service will pick them up by directory name. 

I've done some experiments and edge runtime worker seems to be caching the function for a short period of time, so that it's actually acceptable to just place/move/edit those files of functions even while they are being used. 

Would be cool if there will be some cli or something for 1 line deploy tho.

**Comment by crackedbeefcake** [comment]
hey, 
good to know I am not the only one running into this.

```
#docker compose.yml
  functions:
    image: supabase/edge-runtime:v1.32.0
    volumes:
      - ./volumes/functions:/home/deno/functions:Z
```
so, what you're doing is writing your functions to `./volumes/functions`?
how do you handle dev and prod? 

> Would be cool if there will be some cli or something for 1 line deploy tho.

yes. I am surprised this isnt the default.
