### DISCUSSION TITLE
Supabase Preview Failing - fails to run chroot

### DISCUSSION THREAD

**Discussion by beaux-riel** [supabase/supabase#27211] [Questions] [answered]
Hi everyone,

I've been setting up my CD/CI workflow with GitHub Actions and now that things are a little more structured I keep running into an issue where the Supabase Preview fails, despite all my tests running and passing.

I currently develop against a local Supabase instance. When I push my changes to my staging branch GHAs then push my changes to the Supabase staging project without issue.

When I create a pull request to merge these changes into production however, I'm faced with the following:

<img width="930" alt="Screenshot 2024-06-12 at 8 07 32 AM" src="https://github.com/supabase/supabase/assets/34432201/5ec5c7c4-41d1-4a9f-94a8-334b4ff26ff1">

<img width="1728" alt="Screenshot 2024-06-12 at 8 07 47 AM" src="https://github.com/supabase/supabase/assets/34432201/86aeae62-4a0b-4e8f-b465-fb19a4a273d9">

Here are my 'supabase services' in case I have a conflict here:

<img width="463" alt="Screenshot 2024-06-12 at 8 08 03 AM" src="https://github.com/supabase/supabase/assets/34432201/9ec5fcbf-f3c1-438a-be64-923235c04c8a">

Has anyone faced this issue before? What am I doing wrong? My env variables all appear correct in GitHub. Am I overlooking something obvious?

Any help would be most appreciated.

**Comment by kurtguenther** [comment]
I'm getting this as well on my first Supabase Preview.

```
failed to run chroot /tmp/c4ae819b67c2ccfc/[project-name]-hrD35U: 1
```

**Comment by kurtguenther** [comment]
This is in one of my migrations. If I comment it out, everything will work.

```
CREATE TRIGGER push_notifications AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('http://host.docker.internal:54321/functions/v1/push', 'POST', '{"Content-type":"application/json"}', '{}', '1000');
```

I noticed this because on the new branch preview, if I navigate to `Database > Webhooks` it seems that Webhooks are not enabled for these new previews. Is there something in my config.toml that should be enabling that by default?

Maybe there's an issue with web hook creation via migrations in branch previews?

**Comment by kurtguenther** [comment]
Is this what is going on here? https://github.com/orgs/supabase/discussions/18937#discussioncomment-8027791

**Reply by beaux-riel** [reply]
I believe it is. 

It appears that the Supabase team are aware of the issue and that it only occurs in non-interactive instances that are run as part of GitHub integrations and/or GitHub Actions; specifically the Supabase Preview. Enabling webhooks by default, or allowing us to configure this behaviour from our config.toml or GHA *.yml files, would save so many hours of work in the future. It would also likely address a number of the issues raised by users regarding Supabase troubleshooting.

**Comment by johnCbogil** [comment]
I'm seeing the same issue but we're not using webhooks. Any idea what the root issue might be? or any other clues I can start from?

**Comment by jorge-menjivar** [comment]
Do you have any updates on this issue? We are not using webhooks either, but we are constantly running into this issue.

**Reply by johnCbogil** [reply]
I received this reply from Supabase support team:

`We've seen this issue pop up before and we're currently working on a fix. To unblock you for now though, you should be able to close and reopen your PR to get past this error.
`

**Reply by jorge-menjivar** [reply]
Thank you, however the temp fix would not work for us. The supabase preview on the pull request completes just fine. The issue arises once the pull request is merged into our "production" branch (No worries, it is just a development database) , where we see the chroot error.

**Reply by reghope** [reply]
> Thank you, however the temp fix would not work for us. The supabase preview on the pull request completes just fine. The issue arises once the pull request is merged into our "production" branch (No worries, it is just a development database) , where we see the chroot error.

Same exact thing happening to me

**Reply by adlrwbr** [reply]
Same here

**Reply by benadamsky** [reply]
Dealing with the same issue on our end, will be watching closely for a fix so we can re-enable Supabase branching

**Reply by jventura7** [reply]
same. everything works fine on preview but when merging to production we see the chroot error.

**Comment by zolotokrylin** [comment]
I have same problem :(

**Reply by zolotokrylin** [reply]
What helped me was the CLOSE and REOPEN of the pull request. And then it works.

**Comment by jorge-menjivar** [comment]
Since Supabase Branching is still not working for us, we've been implementing migrations manually through github workflows as follows.

On each pull request or push to main we run the following to check that the migrations are valid:
```yaml
name: Test Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-server:
    name: Test Migrations
    timeout-minutes: 20
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    # Skip the tests if the actor is dependabot and it's a pull request
    if: ${{ !(github.actor == 'dependabot[bot]' && github.event_name == 'pull_request') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Start Supabase to verify that migrations are valid
      - name: Start Supabase
        run: supabase start
```

When ready to apply the migration changes to our production database, we create a new tag:
```yaml
name: Upload Migrations

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Update Production Migrations
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROJECT_ID: <project-id>

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Project
        run: supabase link --project-ref $PROJECT_ID

      # Start Supabase to verify that migrations are valid
      - name: Start Supabase
        run: supabase start

      - name: Push Migrations
        run: supabase db push --include-all
```
