### DISCUSSION TITLE
Can I config supabase CLI to store docker volumes relative to the working dir?

### DISCUSSION THREAD

**Discussion by grndctrl** [supabase/supabase#27284] [Questions]
I would like to config supabase db and storage volume to use a relative path to the working dir, as if I would setup a docker compose like:
```yml
storage:
  volumes:
    - ./local_storage:/var/lib/storage
```
