### DISCUSSION TITLE
Can't upload image attachments to Supabase storage with Rails

### DISCUSSION THREAD

**Discussion by Will-Butler** [supabase/supabase#27547] [Questions] [answered]
Hello! I am working on a personal React/Rails project hosted on Render.com (https://unifounders.onrender.com/) that I just connected to a Supabase project since Render's free storage options are more limited. I've been spending a while trying to figure out how to upload images as ActiveStorage Attachments to my Supabase bucket with no luck. I'm fairly new to all the tools involved, so it's possible I'm missing something simple, but I've exhausted the existing resources and am hoping one of you can help me!

# What I Have
In my database.yml I have:
```
production:
  <<: *default
  database: postgres
  user: postgres.[SOME_KEY]
  password: <%= ENV['SUPABASE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
  port: 6543
```
 I believe this is irrelevant though, since I have my DATABASE_URL environment variable set in my Render project, and I read that takes precedence. Either way, my database configuration seems to work fine since I can update text attributes in the production rails console and see their changes in the Supabase online interface...

In my storage.yml I have:
```
supabase:
  service: S3
  endpoint: <%= ENV['SUPABASE_STORAGE_ENDPOINT'] %>
  region: us-east-1
  bucket: unifounders
  access_key_id: <%= ENV['SUPABASE_KEY'] %>
  secret_access_key: <%= ENV['SUPABASE_KEY_SECRET'] %>
```
And in production.rb:
`  config.active_storage.service = :supabase`

# Error in Rails Console
The error I'm dealing with comes when trying to attach an image to one of my records. Running this:
` c.cover_photo.attach( io: File.open(Rails.root.join('public/UniFounders-Logo2.png')), filename: 'UniFounders-Logo1.png') `
gives me this error:
```
S3 Storage (2225.9ms) Uploaded file to key: [SOME_KEY] (checksum: [SOME_KEY])
/[PATH]/raise_response_errors.rb:17:in `call': Encountered a` SocketError` while attempting to connect to: (Aws::Errors::NoSuchEndpointError)   
https://unifounders.[MY_SUPABASE_STORAGE_ENDPOINT]/[SOME_KEY]

    This is typically the result of an invalid `:region` option or a
    poorly formatted `:endpoint` option.
...
```
- I confirmed my region on Render is us-east-1 (”Virginia (US East)”)
- That endpoint doesn't match what I have for the environment variable used in my storage.yml
    - It seemed to automatically add the 'unifounders' prefix and [SOME_KEY] suffix
    - I noticed the error also suggests avoiding direct configuration of the endpoint but if I remove the endpoint config I get another error message that says missing endpoint
- Running “ActiveStorage::Attachment.all” in rails production console shows the attachment is there, but the file won't show in my Supabase project storage bucket
- The network tab of developer tools shows the following when trying to upload the image:
<img width="850" alt="Screen Shot 2024-06-25 at 4 39 05 PM" src="https://github.com/supabase/supabase/assets/75643017/d47d9607-6fcd-402c-90a7-a356b43eb70c">

# Error in Render Project Console
After trying to debug this for a while with no luck, I tried to upload files directly using my sites user interface and got a 500 error code in the web developer tools network response along with the following error in my Render project console logs:
```
S3 Storage (2165.1ms) Uploaded file to key: [SOME_KEY] (checksum: [SOME_KEY])
…Completed 500 Internal Server Error in 2285ms (ActiveRecord: 92.2ms | Allocations: 9812)
…FATAL
…Seahorse::Client::NetworkingError (Failed to open TCP connection to unifounders.[MY_SUPABASE_PROJECT_URL]:443 (getaddrinfo: Name or service not known)):
```
- this one similarly added a prefix and suffix to my configured variable, although I'm curious as to why this error involves my Supabase project URL (which is also in my Render environment variables) instead of the project endpoint like the other error had?

I greatly appreciate any support provided in resolving this issue!!

Quick note: AWS CLI and the Supabase online interface both let me upload images directly and these images show in my Supabase storage bucket, but I'm not sure how to use either of these tools to attach an image.

**Comment by gmanninglive** [comment, marked as answer]
Hey I've had a look into this as I wanted to try supabase with Rails also. You must use the `force_path_style: true` option to disable prepending the bucket name to the endpoint.

It's documented in the [AWS sdk docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method).

>  :force_path_style (Boolean) — default: false — When set to true, the bucket name is always left in the request URI and never moved to the host as a sub-domain.

So your configuration would look like so:

```
supabase:
  service: S3
  endpoint: <%= ENV['SUPABASE_STORAGE_ENDPOINT'] %>
  region: us-east-1
  bucket: unifounders
  access_key_id: <%= ENV['SUPABASE_KEY'] %>
  secret_access_key: <%= ENV['SUPABASE_KEY_SECRET'] %>
  force_path_style: true
```
