### DISCUSSION TITLE
Trouble Accessing Images in Supabase Storage Bucket

### DISCUSSION THREAD

**Discussion by Will-Butler** [supabase/supabase#28049] [Questions]
# The Problem
Hi! I've been troubleshooting this issue for a while now and can't come up with a solution. I have PNG image files in my Supabase storage bucket, but my website (React/Rails hosted on Vercel) can't access the images. In Safari, the headers tab in the inspect element tool shows a request to one URL:

_https://[SITE_URL]//rails/active_storage/blobs/redirect/[SOME_HASH]/[IMAGE_NAME].png_

which has a 302 Found status and gets redirected to a second URL (where the image is stored in an AWS S3 bucket in Supabase):

_https://[PROJECT_REFERENCE_ID].supabase.co/storage/v1/s3/unifounders/..._

The response of this URL has a 403 Forbidden Status. The credential used later on in this URL is the S3 access key listed under my Supabase storage settings.

# CORS Related?
I tried using Chrome developer tools to see if I could learn anything more/different and the response status for the 2nd URL there was:

`(failed) net::ERR_BLOCKED_BY_ORB
`

so I thought it might be CORS related, but I changed my cors.rb to allow all origins, resources, and headers, and still no luck:
```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
    allow do
      origins '*' #'https://unifounders.onrender.com'
      resource '*',
               headers: :any,
               methods: [:get, :post, :put, :patch, :delete, :options, :head],
               expose: ['Authorization']
    end
  end
```

Based on both responses, I'm assuming the issue has something to do with permissions/policies...

# Question
 The [Supabase blog post](https://supabase.com/blog/s3-compatible-storage) announcing S3 compatibility mentioned 2 options for authenticating with Supabase.

### Standard Credentials
The 1st, which I believe is what I initially tried, was using the standard access_key and secret_key credentials. I had my Supabase project connection pooler set to transaction mode for this and the following configurations in my repo:
**storage.yml**
```
supabase:
  service: S3
  endpoint: https://[PROJECT_REFERENCE_ID].supabase.co/storage/v1/s3
  region: us-east-1
  bucket: unifounders
  access_key_id: <%= ENV['SUPABASE_KEY'] %>
  secret_access_key: <%= ENV['SUPABASE_KEY_SECRET'] %>
  force_path_style: true
```
**database.yml**
```
production:
  <<: *default
  url: [DATABASE_URL]
  prepared_statements: false
  advisory_locks: false
```
**production.rb**
`  config.active_storage.service = :supabase
`

### User-Scoped Credentials with Row Level Security (RLS)
For this option, I enabled RLS in my Supabase project and switched the connection pooler to session mode. I also tried creating policies through the Supabase interface that allows read access to my bucket for all users, with similar policies under storage.objects and storage.buckets. Unfortunately, I was seeing the same network responses in the browser after this. Do I even need to worry about authentication if these are files I want all users (public) to have access to?

**Any and all help resolving this issue would be greatly appreciated. Thank you in advance!**
