### DISCUSSION TITLE
Supavisor behind Traefik TCP with SSL/TLS

### DISCUSSION THREAD

**Discussion by k3rnL** [supabase/supabase#28155] [Questions]
Hello,

I'm trying to setup traefik to handle the secured connection to supavisor, I wanted to let traefik handle the certificate generation. 
So far it does not work, I get this response from psql `psql: error: connection to server at "****" (****), port 5432 failed: received invalid response to SSL negotiation: H`.
I'm not sure what could be wrong, if I disable TLS on traefik, everything works fine.

There is nothing in the documentation about SSL/TLS. Does someone has a clue of what to do ?

I've tried to put passthrough to true and also to change the HostSNI to the actual domain. But the problem persisted.

I share here my docker-compose.

```yml
version: "3"

services:
  db:
    image: supabase/postgres:15.1.1.77
    container_name: supavisor-db
    expose:
      - 5432
    networks:
      supavisor:
        aliases:
          - supavisor_db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: "***"

  supavisor:
    image: supabase/supavisor:1.1.67
    container_name: supavisor
#    ports:
#      - 127.0.0.1:4000:4000
    expose:
      - 5432
      - 6543
    networks:
      - supavisor
      - supabase_tenants_db
      - traefik_proxy
    environment:
      PORT: 4000
      PROXY_PORT_SESSION: 5432
      PROXY_PORT_TRANSACTION: 6543
      DATABASE_URL: "ecto://postgres:***@supavisor_db:5432/postgres"
      CLUSTER_POSTGRES: "false"
      SECRET_KEY_BASE: "***"
      VAULT_ENC_KEY: "***"
      API_JWT_SECRET: "***"
      METRICS_JWT_SECRET: "***"
      REGION: "local"
      ERL_AFLAGS: -proto_dist inet_tcp
    command:  sh -c "/app/bin/migrate && /app/bin/server"
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.tcp.routers.supavisor-main.entrypoints: postgres
      traefik.tcp.routers.supavisor-main.rule: "HostSNI(`*`)"
      traefik.tcp.routers.supavisor-main.tls: true
      traefik.tcp.routers.supavisor-main.tls.passthrough: false
      traefik.tcp.routers.supavisor-main.tls.certresolver: myresolver
      traefik.tcp.routers.supavisor-main.service: supavisor-main
      traefik.tcp.services.supavisor-main.loadbalancer.server.port: 5432
      traefik.tcp.routers.supavisor-bouncer.entrypoints: postgres-bouncer
      traefik.tcp.routers.supavisor-bouncer.rule: "HostSNI(`*`)"
      traefik.tcp.routers.supavisor-bouncer.tls: true
      traefik.tcp.routers.supavisor-bouncer.tls.passthrough: false
      traefik.tcp.routers.supavisor-bouncer.tls.certresolver: myresolver
      traefik.tcp.routers.supavisor-bouncer.service: supavisor-bouncer
      traefik.tcp.services.supavisor-bouncer.loadbalancer.server.port: 6543

networks:
  supavisor:
  supabase_tenants_db:
    external: true
  traefik_proxy:
    external: true
```
