### DISCUSSION TITLE
Local Development - Social Login

### DISCUSSION THREAD

**Discussion by KoltonG** [supabase/supabase#2818] [Questions] [answered]
Wondering if there is a way to setup social logins when developing locally with Supabase?

Currently when hitting a social login provider it brings me to
`http://localhost:8000/auth/v1/authorize?provider=google`
with the following error message
```
{"code":400,"msg":"Unsupported provider: Provider is not enabled"}
```

**Comment by inian** [comment]
Hi @KoltonG,

Can you set `GOTRUE_EXTERNAL_GOOGLE_ENABLED` env var to true for your gotrue config [here](https://github.com/supabase/supabase/blob/1ec181222b881b85e5392da5fa5b76b3e63f7465/docker/docker-compose.yml#L21-L45)? 

The docs for all the env variables supported are [here](https://github.com/supabase/gotrue)

**Reply by ydennisy** [reply]
@inian @KoltonG Hello!

How would a user of the supabase CLI perform this step? I tried GOTRUE_EXTERNAL_GOOGLE_ENABLED=true supabase start but this did not seem to have any effect.

**Reply by rickywid** [reply]
> @inian @KoltonG Hello!
> 
> How would a user of the supabase CLI perform this step? I tried GOTRUE_EXTERNAL_GOOGLE_ENABLED=true supabase start but this did not seem to have any effect.

Did you figure out how to get it to work?

**Reply by naripok** [reply]
@rickywid @ydennisy  Hey!

I got it working by following @inian's tip.

The thing is, you can't just set the env var and call `supabase start` as it seems to ignore it.
Instead, I've cloned the repo as described [here](https://supabase.com/docs/guides/hosting/docker#get-the-code), set the env vars in the [`supabase/docker/docker-componse.yml`](https://github.com/supabase/supabase/blob/1ec181222b881b85e5392da5fa5b76b3e63f7465/docker/docker-compose.yml#L21-L45) like described [here](https://github.com/supabase/gotrue#external-authentication-providers), changed some ports in the `.env` and called `docker-compose up`.
It will spawn a local supabase stack just like `supabase start`, but with the google auth enabled.
Also, you need to set the redirect path in gcloud `OAuth Client` and in the `GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI` var as `http://localhost:54321/auth/v1/callback`, considering you've changed `KONG_HTTP_PORT` to `54321` in `.env`

**Reply by elliottetzkorn** [reply]
This advice is out of date. You don't need to clone the repo. All you need to do after running "supabase init" is to modify the created "config.toml" file inside the supabase directory in the application. At the bottom there is some commented code explaining how to describe your auth providers. I didn't find this documented anywhere strangely.. but it works!

**Reply by naripok** [reply]
@eetzkorn That is much better!
Thanks for the tip!

**Reply by oiojin831** [reply]
@eetzkorn should I still set the `OAuth Client` and `GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI`?
I am having trouble to set gcp's OAuth client to `http://localhost:54321/auth/v1/callback`
since it is not a top level domain.

**Reply by Feel-ix-343** [reply]
Set the domain in the credentials settings, not the consent screen settings

**Comment by chekdotdev** [comment]
You can add custom providers in the `supabase/config.toml` file generated by [`supabase init`](https://supabase.com/docs/reference/cli/usage#supabase-init). It is generated with `auth.external.apple` in the file (but disabled) but it outlines how one might add others:

```toml
# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `twitch`, `twitter`, `slack`, `spotify`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
```

After making those changes, you'll need to run `supabase stop` and `supabase start`.

Be sure to update any `redirect_uri` allowlists and authorized domains with the provider (like https://console.cloud.google.com, in our case). 

See this info in the Supabase [docs](https://supabase.com/docs/guides/getting-started/local-development#use-auth-locally).

**Reply by sellenth** [reply]
I like this. I had some confusion about the redirect_uri but I found that using the API url reported after you run `supabase start` was what I needed. 

Looks like the default API port is 54321 so my redirect URI looks like `http://localhost:54321/auth/v1/callback` which I put in [auth.external.X] and the [auth] additional_redirect_urls in config.toml

Then in my external oauth config (in this case github) I put the callback url to be the same thing, `http://localhost:54321/auth/v1/callback` 

Finally, I had to do `supabase stop` and `supabase start` again to get the new info in the config to take.

**Reply by thorwebdev** [reply]
To make this more secure you can specify your secrets in a `.env` file at the root of your project and use these env vars in your config.toml:

.env file:
```
GITHUB_CLIENT_ID="something"
GITHUB_SECRET="some_secret_here"
```
config.toml
```
[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
```

We're working on adding this to the docs.

**Reply by sonnyvesali** [reply]
So I was struggling with this, and I'd like to add the context that I was missing and what I was missing, so in my case I am developing a flutter app and I was trying to get google oauth working, the thing that held me up first was something that was stupidly simple:

1. Make sure in your project you are using your api url as your url in your supabase instantiation, NOT your db url so it should be `http://localhost:54321` NOT your db url, so make sure that's correct.
2. Set the `site_url` and the `additional_redirect_urls` to the same values as in your production supabase dashboard, so it should be your bundle id like this for `site_url="com.example.app"` and `additional_redirect_urls=["com.example.app://login-callback"]` (remember no underscores in the bundleId use camelCase).
3. In your oauth provider dashboard, in my case this was Google Cloud Platform, make sure to add your development url to the authorized urls
4. Double check when you load in your envs that you close your parentheses, so I made the mistake of `secret="env(GOOGLE_SECRET"`

Hope this helps someone :)

**Reply by ebouther** [reply]
@sonnyvesali I'm still struggling with android emulator and google provider.
I have to use `10.0.2.2:54321` instead of localhost to access supabase, however GCP doesn't allow ip address in "allowed URIs".
Not sure what to do, I've also tried to change android scheme to something like `http://my-app.com/login-callback` so that GCP accepts it but chrome on the emulator failed to open my app.

**Reply by tgirotto** [reply]
I found this useful: https://youtu.be/vojHmGUGUGc?t=1277

**Reply by samthedataman** [reply]
> I like this. I had some confusion about the redirect_uri but I found that using the API url reported after you run `supabase start` was what I needed.
> 
> Looks like the default API port is 54321 so my redirect URI looks like `http://localhost:54321/auth/v1/callback` which I put in [auth.external.X] and the [auth] additional_redirect_urls in config.toml
> 
> Then in my external oauth config (in this case github) I put the callback url to be the same thing, `http://localhost:54321/auth/v1/callback`
> 
> Finally, I had to do `supabase stop` and `supabase start` again to get the new info in the config to take.

this helped and work immensly grateful @supabase-automated-user horrible user experience 2 years later cmon now

**Comment by saltcod** [comment]
@GaryAustin1 could you mark this as the new answer for this one? 

https://github.com/supabase/supabase/discussions/2818#discussioncomment-4019776

We should also note that supabase stop and supabase start is required too somehow.

**Reply by edoecohen** [reply]
Maybe this can be detailed in Supabase's [local development guide](https://supabase.com/docs/guides/cli/local-development)?

**Reply by saltcod** [reply]
Great idea! Coming soon:
https://github.com/supabase/supabase/pull/13937/files#diff-6899d423d14ba6bd70d4cdf4c9efac7d26e49215ca7e02c5dc700e8de7a06609R414

**Comment by LunatiqueCoder** [comment]
Hello!

What about phone auth? How can we enable that on localhost?

**Reply by software-trizzey** [reply]
Curious about this as well.

**Comment by thorwebdev** [comment, marked as answer]
Documentation for this has been added here: https://supabase.com/docs/guides/cli/using-environment-variables-in-config

**Reply by LunatiqueCoder** [reply]
Looks very incomplete at the time of writing.

**Reply by chekdotdev** [reply]
I am also not sure that this documentation covers the scope of the original question. 

The article topic is centered around the use of environment variables, while this question is explicitly asking how to enable social auth locally (as covered very briefly [here](https://supabase.com/docs/guides/getting-started/local-development#use-auth-locally)).

**Reply by software-trizzey** [reply]
Agreed, that more in-depth examples could be provided. For instance, I don't know how to use the local SMS login with the env variables. Is this even possible? A comprehensive list of the variables would be awesome.

**Reply by blexo** [reply]
This link is a 404

**Reply by ethanfox** [reply]
404 Link

**Comment by hevar** [comment]
Just to make it abundantly clear:

Start by following: https://supabase.com/docs/guides/cli/local-development#use-auth-locally

You should have a `config.toml` in your supabase folder, make sure it looks something like this:

```toml
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "YOUR-PROJECT-ID"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000", "http://localhost:54321/auth/v1/callback"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 36000
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = false
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.google]
enabled = true
client_id = "<YOUR-CLIENT-ID>.apps.googleusercontent.com"
secret = "<YOUR-SECRET-ID>"
# Overrides the default auth redirectUrl.
redirect_uri = "http://localhost:54321/auth/v1/callback"
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

```

Add redirect url to google:
![sb-gc](https://github.com/supabase/supabase/assets/9890748/f242ef65-a559-46dd-982d-ef32a0d496be)

Lastly, make sure you've set the correct redirect url:

```tsx
Auth
    magicLink
    supabaseClient={supabase}
    appearance={{ theme: ThemeSupa, extend: true, className: { container: "" } }}
    providers={["google", "facebook"]}
    theme={"light"}
    redirectTo={getSupabaseAuthRedirectURL(redirectString)} // this should be "http://localhost:3000"
/>
```
 
 I use a function to handle different environments:
 
 ```ts
 export const getSupabaseAuthRedirectURL = (queryParam?: string) => {
    let url =
        process?.env?.NEXT_PUBLIC_SITE_URL ?? // Set this to your site URL in production env.
        process?.env?.NEXT_PUBLIC_VERCEL_URL ?? // Automatically set by Vercel.
        "http://localhost:3000"
    // Make sure to include `https://` when not localhost.
    url = url.includes("http") ? url : `https://${url}`
    // Make sure to including trailing `/`.
    url = url.charAt(url.length - 1) === "/" ? url : `${url}/`
    if (!queryParam) {
        return url
    }

    // add potential query params
    url = `${url}${queryParam}`

    return url

}
 ```
