### DISCUSSION TITLE
using a local development setup, change the base url in confirmation links for auth emails from http://127.0.0.1

### DISCUSSION THREAD

**Discussion by rhyek** [supabase/supabase#28232] [Questions]
How can I make it so during local development, the supabase api generates emails with a different base url? Currently all confirmation links look like `http://127.0.0.1:54321/auth/v1/verify?token...`, but I need to specify a different ip in my case for device testing.

All solutions I found here are related to self-hosted docker setups.

**Comment by rhyek** [comment]
in the config.toml i can see the following property that i've tried changing and it has no effect:

```toml
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "mylocalsite.app"
```

if i use `{{ .SiteURL }}` in a custom template, it outputs the `mylocalsite.app`, but `{{ .ConfirmationURL }}` always has the `http://127.0.0.1`
