### DISCUSSION TITLE
Enable Captcha Protection for Local Instance

### DISCUSSION THREAD

**Discussion by perostlin** [supabase/supabase#28276] [Feature Requests] [answered]
Would like to be able to enable captcha protection when running supabase locally.

Haven't been able to find a way as of today to turn this feature on.

We are currently in the works of implementing this and would be nice to be able to try it out locally.

Maybe something like:

```
# config.toml
[auth.captcha]
enabled = true
provider = hcaptcha | cloudflare
secret = secret-value
```

**Comment by xzenon** [comment]
It is possible. Following the [docs](https://github.com/supabase/auth?tab=readme-ov-file#captcha) you need to configure supabase/auth with the proper variables.
To do that define in your .env file:

```
## Captcha
SECURITY_CAPTCHA_ENABLED=true
SECURITY_CAPTCHA_PROVIDER=turnstile (or hcaptcha)
SECURITY_CAPTCHA_SECRET=<captcha secret>
SECURITY_CAPTCHA_TIMEOUT=10s
```

and then update your `docker-compose.yml` to pass them as environment variables to `auth` container:


```
auth:
    container_name: supabase-auth
    ...
    environment:
      ...
      GOTRUE_SECURITY_CAPTCHA_ENABLED: ${SECURITY_CAPTCHA_ENABLED}
      GOTRUE_SECURITY_CAPTCHA_PROVIDER: ${SECURITY_CAPTCHA_PROVIDER}
      GOTRUE_SECURITY_CAPTCHA_SECRET: ${SECURITY_CAPTCHA_SECRET}
      GOTRUE_SECURITY_CAPTCHA_TIMEOUT: ${SECURITY_CAPTCHA_TIMEOUT}
```
