### DISCUSSION TITLE
Is it possible to use the SMS Hook (Beta) in local development?

### DISCUSSION THREAD

**Discussion by diegoserranobst** [supabase/supabase#29045] [Questions]
Hello everyone,

I'm currently exploring the new SMS Hook (Beta) feature in Supabase, and I'm interested in using it within a local development environment. I understand that this feature allows us to use a custom SMS provider to send authentication messages, which is great. However, I'm unsure how to properly set this up while working locally.

Has anyone successfully implemented the SMS Hook in a local setup? If so, could you please share the steps or any configuration tips that might help?

Thank you!

**Comment by silentworks** [comment]
It's available in the latest version of the CLI. You would add this config to your `config.toml` in order to use it
```toml
[auth.hook.send_sms]
enabled = true
uri = "pg-functions://<database>/<schema>/<hook_name>"
secrets = ""
```
