### DISCUSSION TITLE
supabase start does not load environment variable

### DISCUSSION THREAD

**Discussion by LaCocoRoco** [supabase/supabase#30093] [Questions]
Hi, i tried many different solution but couldn't fix my problem. When i access supabase dashboard from supabase start with an custom domain supabase.mydomain.com, i have to change api_url in the config.toml file so it possible to create accounts, because it has to access the api url on the reverse proxy.

```toml
[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "https://api.mydomain.com"
# OpenAI API Key to use for Supabase AI in the Supabase Studio.
openai_api_key = "env(OPENAI_API_KEY)"
```

This works as it should. But when i try to use the environment variable like this:

```toml
[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "env(SUPABASE_API_URL)"
# OpenAI API Key to use for Supabase AI in the Supabase Studio.
openai_api_key = "env(OPENAI_API_KEY)"
```
it does not work anymore. In the browser console i can see it tries to use localhost. Summarized i do not know why supabase start does not load my environment variables. I tried to something like "dotenv -e .env -- supabase start" or "export SUPABASE_API_URL="https://api.mydomain.com" without success. Do i missing something? Can i somehow debug or log the start process to see why it is not working?
