### DISCUSSION TITLE
Write Edge Functions in pure JavaScript instead of using TypeScript

### DISCUSSION THREAD

**Discussion by laktek** [supabase/supabase#30307] [Changelog]
From Supabase CLI version 1.215.0 or higher you can configure a custom entrypoint to your Edge Functions. This can be used to write Edge Functions in pure JavaScript instead of TypeScript.

Save your Function as a JavaScript file (eg: `index.js`) and then update the `supabase/config.toml` as follows:

```toml
[functions.hello-world]
# other entries
entrypoint = './functions/hello-world/index.js' # path must be relative to config.toml
```

You can use any `.ts`, `.js`, `.tsx`, `.jsx` or `.mjs` file as the entrypoint for a Function.

More details: https://supabase.com/docs/guides/functions/quickstart#not-using-typescript
