### DISCUSSION TITLE
How to properly configure Supabase Docker

### DISCUSSION THREAD

**Discussion by YukiAttano** [supabase/supabase#32712] [Questions]
I would like to host multiple instances of Supabase on my Docker host but all ports are mapped towards the host system.

My idea is, that any supabase system gets it's own dedicated ip address.

For that, i already have set up a macvlan and a custom bridge network.
```
supabase docker compose.yml ...


networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/24
         gateway: 10.0.1.1
  macvlan_network:
    name: "macvlan_network"
    external: true
```

My question is now, do i just have to configure the Kong service properly to redirect all requests to the services that have open ports configured? This services would be the supabase-pooler and supabase-analytics.

Right now, if i assign an dedicated ip address to Kong, for example the supabase menu is not correctly showing the tables (does it use the supabase-pooler?). 

I would be grateful for some hints in the right direction.
