### DISCUSSION TITLE
Unknown config fields when seeding database

### DISCUSSION THREAD

**Discussion by JakenHerman** [supabase/supabase#32724] [Questions] [answered]
Howdy all,

I'm trying to seed my database following the documentation provided [here](https://supabase.com/docs/guides/local-development/seeding-your-database).

My `supabase/config.toml` has the following:
```toml
[db.seed]
enabled = true
sql_paths = ['./one.sql', './two.sql', './three.sql']
```

When I run `supabase db start`, I get the following error:

```
Unknown config fields: [db.seed db.seed.enabled db.seed.sql_paths]
```

Any ideas what's going on? Has this config field been renamed or something and the documentation has not been updated?
