### DISCUSSION TITLE
Web Server Development Verification E-Mail Problem

### DISCUSSION THREAD

**Discussion by LaCocoRoco** [supabase/supabase#33029] [Questions] [answered]
Almost all of the time i use my VPS for development. I try to test the supabase auth e-mail verification. This is my config.toml setting:
```toml
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://dev.mydomain.at"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://dev.mydomain.at"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow anonymous sign-ins to your project.
enable_anonymous_sign_ins = false
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false
```

This is the e-mail template:
```html
<h2>Confirm your signup</h2>

<p>Follow this link to confirm your user:</p>
<p><a href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=signup">Confirm your mail</a></p>
```

This is the plain text link i get into the inbucket:
```
http://127.0.0.1:54321/auth/v1/verify?token=pkce_5d559d2e62130485aea99dabeecd73ca36925eb10b662e93b68a3bac&type=signup&redirect_to=https://dev.mydomain.at 
```

Because inbucket is hosted on "inbucket.mydomain.at" i can not verify the account. The address "http://127.0.0.1:54321/" should be "http://api.mydomain.at".

My caddy setting:
```
api.mydomain.at {
        reverse_proxy localhost:54321
}
```

Does someone know the setting i have to change so the verification e-mail changes the localhost address to api.mydomain.at?
