### DISCUSSION TITLE
How to create and schedule Edge functions on self hosted Supabase (Docker)?

### DISCUSSION THREAD

**Discussion by Tom-De-Backer** [supabase/supabase#33235] [Questions] [answered]
I have self hosted Supabase via container on a VM. I would like to add some edge functions to this Supabase instance, but there seems to be an issue. I have already added the `cron` integration, where I am trying to add a new job via this screen:

![image](https://github.com/user-attachments/assets/c0d46ea5-30cc-4130-aa96-89ca7a0879f9)

The first thing that seems not right is: Supabase tells me "No edge functions created yet". However, there is a 'main' and a 'hello' function as an example in the docker github of Supabase. So I assume these functions should have been shown there. However, I try to create a new function but that does not work. The webpage shows a supabase logo that is running forever.

What is going wrong here?
This is the studio version I use: `supabase/studio:20241202-71e5240`
The functions container in `docker-compose.yml` looks like this:

```
  functions:
    container_name: supabase-edge-functions
    image: supabase/edge-runtime:v1.66.4
    restart: unless-stopped
    volumes:
      - ./volumes/functions:/home/deno/functions
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      # TODO: Allow configuring VERIFY_JWT per function. This PR might help: https://github.com/supabase/cli/pull/786
      VERIFY_JWT: "${FUNCTIONS_VERIFY_JWT}"
    command:
      [
        "start",
        "--main-service",
        "/home/deno/functions/main"
      ]
```
