### DISCUSSION TITLE
What is the correct way to handle config.toml when running the CLI in Github Actions

### DISCUSSION THREAD

**Discussion by IPJT** [supabase/supabase#33604] [Questions] [answered]
Hi, 

I'm setting up a CD-pipeline in Github actions to deploy to production using `supabase db push`. 

When doing so the cli picks up the config.toml which causes some error as it has been setup to be used for the local environment. Any ideas how to handle this? 

Thank you!

**Comment by IPJT** [comment]
Clarification: 
In order to run the send email auth hook during local development i have the below settings in my config.toml:

```toml
[auth.hook.send_email]
enabled = true
uri = "http://host.docker.internal:3000/api/auth/email-webhook" #host.docker.internal is a special DNS name used in Docker to allow a container to access the host machine's network. This allows the Auth container to reach the route handler
secrets = "env(SUPABASE_SEND_EMAIL_HOOK_SECRET)"
```

This works perfectly fine and does exactly what i want it to do when running the Supabase stack on my local machine. The SUPABASE_SEND_EMAIL_HOOK_SECRET-secret is in my .env file which is not tracked by git. So far so good. 

The problem:
In my CD-pipeline (deploy-production.yml) I do:

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link with Supabase
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Deploy Supabase migrations
        id: deploy-db
        run: |
          echo "Starting database migrations..."
          cd apps/api
          if supabase db push; then
            echo "Database migrations completed successfully"
            echo "db_success=true" >> $GITHUB_OUTPUT
          else
            echo "Database migrations failed"
            echo "db_success=false" >> $GITHUB_OUTPUT
            exit 1
          fi


The pipeline will fail with the following message:
`WARN: environment variable is unset: SUPABASE_SEND_EMAIL_HOOK_SECRET
Invalid hook config: auth.hook.send_email.secrets must be formatted as "v1,whsec_<base64_encoded_secret>" with a minimum length of 32 characters. `

The explanation:
This is due to the cli in the pipeline having access to the config.toml file but not the .env file where the secret is defined. 
When running supabase db push it only runs the migrations and shouldn't touch hooks config. However, I guess the CLI will validate the whole config file which causes the error. With that said, I guess I could work around it by overwriting the checked in config.toml file in my CD-pipeline with a temporary minimal file (could prob be empty). 

However, I kind of don't like the idea of this. It feels like there must be a better way of handling this. Seems dangerous that the production CD tries to read the configs from my file for local environment config even though I assume it wouldn't use it. 

I hope this clarified things. Thank you for wanting to help!
