### DISCUSSION TITLE
Send SMS Hook - How?

### DISCUSSION THREAD

**Discussion by abuwho** [supabase/supabase#33699] [Questions] [answered]
After following the docs instructions on https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook what are we supposed to do next? 

Do we go to Supabase's self-hosted studio and create an auth hook to send SMS? 
http://127.0.0.1:54323/project/default/auth/hooks 

```
Failed to create hook: API error happened while trying to communicate with the server.
```

Why is it happening? 

Also, the auth hook requires an HTTPS endpoint, but the self-hosted Supabase is running on HTTP, how is it handled usually?

**Comment by GaryAustin1** [comment]
As far as setting up your hook for local dev you have to modify config.toml https://supabase.com/docs/guides/auth/auth-hooks?queryGroups=language&language=sql#developing
I assume for self hosted (not clear if that is what you mean) then you would have to set it up in the appropriate .env file.

No help otherwise as I've not played with these hooks yet.

**Comment by abuwho** [comment, marked as answer]
So, after doing some checking, I finally got it to work. The steps I needed to take to get it to work are following (self-hosted)

1. Add the following to the `auth` service in `docker-compose.yml` file: 
```yaml
# ....
extra_hosts:
      - "host.docker.internal:host-gateway"
environment: 
      # ....
      GOTRUE_HOOK_SEND_SMS_ENABLED: "${GOTRUE_HOOK_SEND_SMS_ENABLED}"
      GOTRUE_HOOK_SEND_SMS_URI: "${GOTRUE_HOOK_SEND_SMS_URI}"
      GOTRUE_HOOK_SEND_SMS_SECRETS: "${GOTRUE_HOOK_SEND_SMS_SECRETS}"
      # ....
```
2. Add the following lines to the `.env` file: 
```
GOTRUE_HOOK_SEND_SMS_ENABLED=true
GOTRUE_HOOK_SEND_SMS_URI="http://host.docker.internal:8000/functions/v1/send-sms"
GOTRUE_HOOK_SEND_SMS_SECRETS="v1,whsec_.............."
```
3. While writing the edge function by following the docs, need to replace the empty object `{}` with `JSON.stringify({})` like the following: 
```TypeScript
    return new Response(
      JSON.stringify({}),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        },
      }
    )
```

Thank you @GaryAustin1 for help. :)
