### DISCUSSION TITLE
How to run pgTAP tests in a Bitbucket pipeline

### DISCUSSION THREAD

**Discussion by tedsecretsource** [supabase/supabase#34430] [Questions]
Hi.

I'm new to Supabase. We have a team of developers working on a solution. We're using pgTAP heavily and would like to make it a part of our pipeline. We've found that we can't just bring up the entire Supabase backend via `supabase start` because it consumes too much memory (and adds at least 10 minutes to the pipeline). We considered running just the Postgres image but before we do anything I thought I'd check in here to see if anyone else has confronted this problem and has any suggestions on how to handle it.

TIA

Ted Stresen-Reuter

**Comment by silentworks** [comment]
You can exclude services with `supabase start` by passing the `-x` parameter. You can see this in the reference docs https://supabase.com/docs/reference/cli/supabase-start. Also note you can also disable services from inside the `config.toml` file.

**Reply by tedsecretsource** [reply]
Excellent information. Thank you for pointing this out. I've read and re-read the docs and simply did not see this 🤷.

Also, I think I understand that I don't actually need to run supabase in the pipeline. I haven't tested this yet, but this is what I'm considering trying:

```yml
    - step: &run_pgTAP_tests
        name: Run pgTAP tests
        deployment: Test
        script:
          - apk update && apk add --no-cache git postgresql-client perl perl-app-cpanminus
          - cpanm App::pgTAP
          - echo "Waiting for PostgreSQL to be available..."
          - export PGPASSWORD="$POSTGRES_PASSWORD"
          - export SUPABASE_DB_PASSWORD="$POSTGRES_PASSWORD"
          - export POSTGRES_USER="$POSTGRES_USER"
          - export POSTGRES_DB="$POSTGRES_DB"
          - until pg_isready -h supabase -p 5432 -U "$POSTGRES_USER"; do sleep 1; done
          - echo "Running migrations..."
          - for file in migrations/*.sql; do
              echo "Applying migration ${file}";
              psql -h supabase -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f "${file}";
            done
          - echo "Running pgTAP tests..."
          - pg_prove -h supabase -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" tests/*.sql

# later on when pushing to production

    - step: &deploy_supabase
        name: Deploy to Supabase
        deployment: Production
        script:
          - apk update && apk add --no-cache git curl
          - npm install -g supabase
          - echo "Logging into Supabase CLI..."
          - supabase login "$SUPABASE_ACCESS_TOKEN"
          - echo "Pushing production changes to Supabase..."
          - supabase link --project-ref "$SUPABASE_PROJECT_REF" <<< ""
          - supabase db push

# define the supabase database service
  services:
    supabase:
      image: supabase/postgres
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD

```

I'm not really sure about the linking in and pushing bit. It feels wrong that I have to link to be able to push changes to the DB schema, but I guess it is sort like logging in, so, kind of makes sense.

Thanks for the help!

**Reply by silentworks** [reply]
If you don't want to do the whole login and linking thing you can just pass `--db-url` flag to the `supabase db push` with the connection string for the **Session pooler**.

**Reply by tedsecretsource** [reply]
There were actually a couple of issues. 

First, I think you _must_ use `postgres` as the `$POSTGRES_PASSWORD` when initializing the official Supabase postgres image (that contains all of the extensions). Either that or the service definition must use the `variables` keyword instead of the `environment` keyword. My service definition looks like this:

```yml
definitions:
  services:
    postgresdb:
      image: supabase/postgres:15.8.1.059
      variables:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
```

Once I figured that out, I ended up with this (working) bitbucket pipeline step (which is actually a named anchor, kind of like a variable, that can be calle in the pipeline as shown below):

```yml
    run_pgTAP_tests: &run_pgTAP_tests
      name: Run pgTAP tests
      services:
        - postgresdb
        - docker # docker service _might_ not be necessary
      caches:
        - docker
      environment:
        # these might not be necessary
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      script:
        - echo "Installing the supabase CLI"
        - npm install
        - echo "Running migrations..."
        - npx supabase migration up --db-url "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB?sslmode=disable"
        - echo "Running pgTAP tests..."
        # Update apk and install required packages.
        - apk update && apk add --no-cache perl perl-dev perl-utils make wget curl postgresql-client
        - psql -h localhost -U $POSTGRES_USER -d postgres -c "CREATE EXTENSION IF NOT EXISTS pgtap;"
        # Download and install cpm.
        - curl -sL --compressed https://git.io/cpm > cpm
        - chmod +x cpm
        - ./cpm install -L /usr/local TAP::Parser::SourceHandler::pgTAP
        # Set the PERL5LIB to include the installed modules.
        - export PERL5LIB=/usr/local/lib/perl5
        # Set PostgreSQL connection environment variables. Should these be in the environment above?
        - export PGHOST=localhost
        - export PGUSER=$POSTGRES_USER
        - export PGPASSWORD=$POSTGRES_PASSWORD
        - export PGDATABASE=$POSTGRES_DB
        # Change to the directory with your SQL tests.
        - cd supabase/tests/database
        # Run pg_prove over all SQL files.
        - pg_prove *.sql

pipelines:
  branches:
    '**':
      - step: *run_pgTAP_tests

```

I can confirm that the above step runs pg_prove on all the tests and seems to work perfectly. I couldn't use the official Supabase image because bitbucket doesn't use standard Docker networking. Instead, it does some sort of networking where each service is actually identified by port number so everything runs on `localhost` (note the localhost in the --db-url string). I tried using the service name, `postgresdb`, in the URL but that didn't work, networking error.

Thanks for your help!

I sincerely hope this helps other people facing the same issue.
