### DISCUSSION TITLE
Local instance with TLS enabled does not work with Edge Functions due to insecure certs.

### DISCUSSION THREAD

**Discussion by DreamwareDevelopment** [supabase/supabase#34977] [Troubleshooting]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I run my next app locally like so: `NODE_TLS_REJECT_UNAUTHORIZED=0 next dev`. There doesn't seem to be a way to do this with Deno, so when I call an edge function from a trigger it silently fails. 

## To Reproduce

1. Enable TLS in config.toml
2. Write an edge function
3. Test it with curl, note the need for the -k flag
4. Setup a webhook to point at the function
5. See that the webhook doesn't run and in the net.http_responses table you'll see that it fails to connect and that there are no logs anywhere.

## Expected behavior

We should be able to run edge functions against a TLS enabled local instance.

**Comment by DreamwareDevelopment** [comment]
If anyone needs a workaround, you can use ngrok to tunnel multiple ports and call the edge function via the ngrok domain, my ngrok config looks like this:
```
version: "3"
agent:
    authtoken: <your-ngrok-token>
tunnels:
  next:
    addr: 3000
    proto: http
    domain: <ngrok-domain>
  supabase:
    addr: https://localhost:54321
    proto: http
    domain: <ngrok-domain>
```
This works because deno finds a valid certificate via ngrok. This sucks though and makes me have to pay extra to ngrok if I want a second static domain. It's not so horrible if you write your own SQL functions and pull out the functions endpoint via vault though, that way you can just change the url in the dashboard instead of hardcoding it.

If I'm just being a deno noob and there's some easy way to force it to accept untrusted certs, please tell me.
