### DISCUSSION TITLE
Supabase-analystic service(logflare) 502 error when use postgresql as backend

### DISCUSSION THREAD

**Discussion by ShermanTsang** [supabase/supabase#35520] [Questions]
# Enviroment
I'm using self-hosted supabase with docker compose and using postgresql as logflare backend.
When I config and run the services, I catch the error with supabase-analystic.

My supabase-analystic service:
```
  analytics:
    # container_name: supabase-analytics
    image: supabase/logflare:1.12.0
    restart: unless-stopped
    ports:
      - 4000:4000
    # Uncomment to use Big Query backend for analytics
    # volumes:
    #   - type: bind
    #     source: ${PWD}/gcloud.json
    #     target: /opt/app/rel/logflare/bin/gcloud.json
    #     read_only: "true"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "http://localhost:4000/health"
        ]
      timeout: 5s
      interval: 5s
      retries: 10
    depends_on:
      - db
    environment:
      LOGFLARE_NODE_HOST: 127.0.0.1
      DB_USERNAME: supabase_admin
      DB_DATABASE: _supabase
      DB_HOSTNAME: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: _analytics
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_PUBLIC_ACCESS_TOKEN: ${LOGFLARE_API_KEY} 
      LOGFLARE_SINGLE_TENANT: "true"
      LOGFLARE_SUPABASE_MODE: "true"
      LOGFLARE_MIN_CLUSTER_SIZE: 1

      # Comment variables to use Big Query backend for analytics
      POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/_supabase
      POSTGRES_BACKEND_SCHEMA: _analytics
      # LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=false
      # Uncomment to use Big Query backend for analytics
      # GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      # GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}
```

# Error details

## Supabase-analystic container error logs
```
[warning] Failed to connect to https://bigquery.googleapis.com:443: timeout
```
![image](https://github.com/user-attachments/assets/104fb622-464a-4fce-8da2-3c32e52195de)

## The disfunctionality of supabse studio logs
- All preset log collection return nothing
![image](https://github.com/user-attachments/assets/cd76e639-1b47-4dda-ab81-20d6c5f8d74b)
- All new query on logs return 502 error
![image](https://github.com/user-attachments/assets/6ed6974c-dbd1-4fe7-a2e0-fc5db9ea5c9c)
```
{"code": 502,"errors": [],"message": "Something went wrong! Unknown error. If this continues please contact support.","status": "UNKNOWN"}
```

# My guessing
Due to the blockout of my nework enviroment, my server can't access bigquery.googleapis.com:443.
However, I think if I use postgresql as backend, the service should have nothing to do with google bigquery service. Am I right?
And I don't know the error if caused by this reason?

So I sincerely hope anyone had the same experience or who knows how to solve this question(or bug) can help me.
Thanks a lot!
