### DISCUSSION TITLE
ERROR: permission denied for sequence key_key_id_seq (SQLSTATE 42501) in GitHub action

### DISCUSSION THREAD

**Discussion by thomas-woehrle** [supabase/supabase#35602] [Questions]
Hi, 

I created this GitHub action to check the sanity/integrity of my mutations:
```yml

on:
  pull_request:
    branches:
      - main

jobs:
  check-migrations-replay:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Start local supabase
        run: supabase start
      - name: Replay supabase migrations
        run: supabase db reset
```

When the "Start local supabase" step runs, I get this error:

```
Status: Downloaded newer image for ghcr.io/supabase/gotrue:v2.171.0
Seeding globals from roles.sql...
Applying migration 20250502065942_remote_schema.sql...
Applying migration 20250502080126_remote_schema.sql...
Applying migration 20250503174720_add_test_table.sql...
NOTICE (42P06): schema "supabase_migrations" already exists, skipping
Seeding data from supabase/seed.sql...
Stopping containers...
failed to send batch: ERROR: permission denied for sequence key_key_id_seq (SQLSTATE 42501)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

The --debug flag does not help in troubleshooting the error afaict

I looked for similar errors, and tried the advice in #21450, but that didn't work. 

What I want to do seems to be pretty standard, so no idea why it is not working
