### DISCUSSION TITLE
Setting up frontend together with supabase-docker in a single compose-file

### DISCUSSION THREAD

**Discussion by TheLexoPlexx** [supabase/supabase#36296] [Questions]
I already posted this on reddit but I just got downvoted once with no answers, maybe I am a dumbo after all but somebody please tell me if that's the case. I added some more info in the meantime. Anyways:

---

Hi there,

I am trying to set up my nextjs-application together with supabase in a single docker-compose-file.

I have setup docker just like in this guide: [https://supabase.com/docs/guides/self-hosting/docker](https://supabase.com/docs/guides/self-hosting/docker)  
And Auth is set up through this guide: [https://supabase.com/docs/guides/auth/server-side/nextjs](https://supabase.com/docs/guides/auth/server-side/nextjs)

Everything works if I just use the docker-compose provided by supabase and if I run the nextjs-server seperately with next-start.

So this would be ideal setup:
```yaml
include:
  - path: supabase/docker-compose.yml
    env_file:
      - .env.production

services:
  nextjs:
    container_name: senator-prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 15s
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      auth:
        condition: service_healthy
      supavisor:
        condition: service_healthy
      analytics:
        condition: service_healthy
      realtime:
        condition: service_healthy
```

but as of right now, to get it working, it's just:
```yaml
include:
  - path: supabase/docker-compose.yml
    env_file:
      - .env.production
```

Which means, once i move the project into the same docker-compose (and network) everyhing loses it's mind and I end up with an infinite middleware-redirect-loop. Gemini suggested this might be due to cookies not being properly set due to the URL's being different from the ones required within a docker-network.

The .env-File with the corresponding URLs can also be found in the gist. I changed the URL to localhost, 0.0.0.0, kong or whatever and never succeeded.

My middleware-File (which is identical to the example with added debug-messages): [https://gist.github.com/TheLexoPlexx/968f01dffb387a5d05003e0c5ceadb41](https://gist.github.com/TheLexoPlexx/968f01dffb387a5d05003e0c5ceadb41)

And the corresponding output-log when trying to access the nextjs-server:

    [DEBUG] updateSession
    [DEBUG] supabase_url: "http://localhost:8000"
    [DEBUG] supabase_anon_key: "true"
    [DEBUG] getAll
    [DEBUG] getAll
    [DEBUG] getAll
    [DEBUG] middleware: user
    [DEBUG] updateSession
    [DEBUG] ...

...which then repeats over and over again until firefox stops.

I have been struggling with this for the past entire day and I can't figure it out. Does someone maybe have an example-compose with working setup or did I miss something?
