### DISCUSSION TITLE
Errors with self-hosting

### DISCUSSION THREAD

**Discussion by IzMichael** [supabase/supabase#3949] [Questions] [answered]
I'm attempting to self-host an instance of Supabase for a project, but I'm having some issues with it. I've followed the steps outlined [on this page](https://supabase.io/docs/guides/hosting/docker), but when I attempt to run it, I get the error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'auth'
```
I haven't changed anything in that file aside from setting the JWT tokens as requested

I'm quite confused here

**Comment by louiscklaw** [comment, marked as answer]
adding ```version: '3'``` at the beginning of docker-compose.yml solves the problems for me.

modifiy the docker-compose.yml
```
version: '3'
services:
  kong:
    container_name: supabase-kong
    image: kong:2.1
    restart: unless-stopped

...
```


my configuration:
```
➜ uname -a      
Linux logic-OptiPlex-9020 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

➜ docker-compose --version
docker-compose version 1.26.2, build eefe0d31
```
