### DISCUSSION TITLE
How to setup Google OAuth in Self Hosted Supabase?

### DISCUSSION THREAD

**Discussion by ElectronLabsIndia** [supabase/supabase#4885] [Questions] [answered]
I am trying to set up Google OAuth with Supabase Self Hosted Setup but I couldn't see the parameters for Google Authentication in docker-compose.yml. How to proceed for Google Authentication?

**Comment by johnbabu021** [comment]
i think https://supabase.com/docs/guides/auth/auth-google this will help you

**Reply by sinameraji** [reply]
this isn't for self-hosted instances.

**Comment by bhagavan44** [comment, marked as answer]
I am able to achieve this functionality by changing the docker-compose.yml file

```
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${ENABLE_GOOGLE_SIGNUP}
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:8000/auth/v1/callback
```

**Reply by thimiraonline** [reply]
> To where did you add this. in .yml file?

**Reply by bhagavan44** [reply]
It is available here https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml. We need to add to Auth Service

**Reply by thimiraonline** [reply]
To where should I add Client ID and secrets?

**Reply by bhagavan44** [reply]
You can add after this line https://github.com/supabase/supabase/blob/0bdfe8589cdf847d01c615bae369c1301f311972/docker/docker-compose.yml#L114 as mentioned in my previous comment.

**Reply by thimiraonline** [reply]
I added it and re composed up docker. What is the next step.

**Reply by ghost** [reply]
I have added the lines to the docker-compose.yml and inserted the keys and values into my .env file. After running 'docker-compose up' and visiting [http://localhost:8000/project/default/auth/providers](http://localhost:8000/project/default/auth/providers), Google authentication is still disabled.

**Reply by UdaraWanasinghe** [reply]
Do not edit the `docker-compose.yml` file directly.
Create a file named `docker-compose.override.yml` and add the following to override existing configs. `docker-compose.override.yml` is already in the `.gitignore` list, so you can update Supabase later without modifying files.
```
services:
  auth:
    environment:
     GOTRUE_EXTERNAL_GOOGLE_ENABLED: ${ENABLE_GOOGLE_SIGNUP}
     GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
     GOTRUE_EXTERNAL_GOOGLE_SECRET: ${GOOGLE_CLIENT_SECRET}
     GOTRUE_EXTERNAL_GOOGLE_SKIP_NONCE_CHECK: false
     GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
```

Then run `docker compose up -d` to update container configs.
You can check if the environment variables are properly applied using `docker exec supabase-auth printenv` command.
