### DISCUSSION TITLE
How to run all edge functions in local development

### DISCUSSION THREAD

**Discussion by ghost** [supabase/supabase#6786] [Show and tell]
Please note: Since [CLI v1.38.6](https://github.com/supabase/cli/releases/tag/v1.38.6) this has been added natively when running `supabase functions serve` without any function name: https://supabase.com/docs/reference/cli/supabase-functions-serve

---

Hello, just wanted to share how I've been running all of my edge functions at once in local development.

I create one single edge function that imports all the others and acts as a proxy for them. Then, I run:

```sh
supabase functions serve localdev
```

Here's an example from my project file at `supabase/functions/localdev/index.ts`:

```ts
import {
  ConnInfo,
  Handler,
  serve,
} from "https://deno.land/std@0.131.0/http/server.ts";
// Local
import { corsHeaders } from "../_shared/cors.ts";

console.log("Setting up localdev function...");

const handlers = {
  hello: await import("../hello/handler.ts").then((it) => it.handler),
  "invite-user": await import("../invite-user/handler.ts").then((it) =>
    it.handler
  ),
  "make-me-admin": await import("../make-me-admin/handler.ts").then((it) =>
    it.handler
  ),
} as Record<string, Handler>;

function localdevHandler(req: Request, connInfo: ConnInfo) {
  // This is needed if you're planning to invoke your function from a browser.
  if (req.method === "OPTIONS") {
    return new Response("OK", { headers: corsHeaders });
  }
  console.log(`${req.method} ${req.url}`);
  const url = new URL(req.url);
  const urlParts = url.pathname.split("/");
  const handlerName = urlParts[urlParts.length - 1];
  const handler = handlers[handlerName];
  try {
    return handler(req, connInfo);
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      },
    );
  }
}

serve(localdevHandler);

console.log("OK");
```

**Comment by c0de-intention** [comment]
@waynebloss thanks for your solution. I was wondering if you use the js api to invoke the functions?

e.g.
```js
await supabase.functions.invoke('my_function')
```

I cannot find a way to set this url. But maybe i might have to settle for making my own fetch calls for now, still helps a lot thanks for sharing

**Reply by ghost** [reply]
@crushingCodes I think you need to put something in your `config.toml` file. I have this:

```toml

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:48801"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  "https://app.mydomain.com",
  "https://localhost:48801",
  "http://192.168.X.X:48801",
]
```
