### DISCUSSION TITLE
Datadog integration

### DISCUSSION THREAD

**Discussion by rbkayz** [supabase/supabase#8801] [Questions] [answered]
Hi folks. Any way to configure datadog monitoring for the postgres db?

**Comment by mcmadafly** [comment]
Bump

**Comment by encima** [comment, marked as answer]
As of now, there is no direct integration. 

You can use the [metrics](https://supabase.com/docs/guides/platform/metrics) with the Datadog agent's [prometheus endpoint](https://docs.datadoghq.com/api/latest/metrics/). 

You would need to have the agent running somewhere to do this and we have a guide for doing something similar (for Grafana) [here](https://github.com/supabase/grafana-agent-fly-example/)

**Comment by saulhoward** [comment]
Hi,

I need the Datadog agent to be connected to the DB. I believe this gives much more than the prometheus metrics.

https://docs.datadoghq.com/database_monitoring/setup_postgres/selfhosted/?tab=postgres15

Could you let me know if this is on the roadmap? I need explain plans etc.

**Reply by encima** [reply]
Hi, it is possible to do this now. As the comment above states, you would need to have the agent running on a compute instance somewhere and connect it to the database using the settings of your project. There is no plan to include the agent on the database instances as far as I am aware

**Reply by danielehrhardt** [reply]
@encima do you have some instructions we can follow?

**Reply by encima** [reply]
> @encima do you have some instructions we can follow?

The link in the question is the best docs link. It covers installing the agent and configuring the database.

**Reply by farah-u** [reply]
Hi @encima - trying to follow this guide. Datadog involves configuring the yaml. However it's not clear to me what the Supabase appropriate values are. 
```
init_config:
instances:
  - dbm: true
    host: localhost
    port: 5432
    username: datadog
    password: 'ENC[datadog_user_database_password]'
    ## Optional: Connect to a different database if needed for `custom_queries`
    # dbname: '<DB_NAME>'
```

Is the localhost the aws host? e.g. aws-0-us-east-1.pooler.supabase.com
Do we need to set up a separate datadog role? Because otherwise we need to set the project context in `username` right? e.g. `postgres.[project-ref]`. Not 100% sure how we can map into this fields with Supabase's config.
