### DISCUSSION TITLE
Integrating with Non-AWS S3 Object Storage

### DISCUSSION THREAD

**Discussion by nasanos** [supabase/supabase#8837] [Questions]
What are the steps needed to integrate a self-hosted Supabase instance with a non-AWS S3-compatible service? I have been through the Supabase documentation and GitHub, and can't find anything explicitly giving the variables to set and where. Unless I missed something, I haven't seen any discussions here specifically dealing with this either.

I'm actually currently writing an article on integrating my company's S3-compatible object storage with Supabase. My hope is that the article would also go a long way to documenting the steps for connecting any S3-compatible storage.

Here is what I have so far.

- Based on the default `docker-compose.yml` and additional variables I've seen discussed in the GitHub, I have the following in my `docker-compose.yml`. Of course,  the access key information has been replaced with placeholders here, and I did the same with `example-object-storage.com`:
    ```
    storage:
      # [...]
      environment:
        # [...]
        STORAGE_BACKEND: s3
        FILE_STORAGE_BACKEND_PATH: ./data
        REGION: us-southeast-1
        GLOBAL_S3_ENDPOINT: [example-supabase-bucket.us-southeast-1.example-object-storage.com](http://example-supabase-bucket.us-southeast-1.example-object-storage.com/)
        GLOBAL_S3_BUCKET: example-supabase-bucket
        AWS_ACCESS_KEY_ID: replace-with-actual-access-key-id
        AWS_SECRET_ACCESS_KEY: replace-with-actual-access-key-secret
    ```
- In my instance's Supabase Studio, I executed the following SQL to create a bucket and give it public permissions for testing purposes:
    ```
    insert into storage.buckets (id,name)
    values ('examplebucket','examplebucket');

    create policy "ReadAccessToEveryone"
    on storage.buckets
    for select using (true);

    create policy "InsertAccessToEveryone"
    on storage.buckets
    for insert with check (true);

    create policy "ReadObjectsAll"
    on storage.objects
    for select using (true);

    create policy "InsertObjectsAll"
    on storage.objects
    for insert with check (true);
    ```
- I created an application with the Supabase client SDK for testing file upload functionality. It was my attempt to have a hard verification for the bucket connection and get feedback should the connection not work. I get an error related to a method called on null. My application is able to connect to the instance, however, because it is able to make CRUD-related calls successfully.

Should it be helpful, I can provide the full contents of my configuration files and the code for my client application on request. I thought I shouldn't clutter this already long post with that right out of the gate, however.
