### DISCUSSION TITLE
Using Non-AWS S3 Object Storage for a Self-hosted Instance

### DISCUSSION THREAD

**Discussion by nasanos** [supabase/supabase#9009] [Questions]
## Question

Is it possible to use an S3-compatible object storage other than AWS with a self-hosted Supabase instance?

There isn't anything that I can find in the documentation about this, but some GitHub issues/PRs suggest that it is possible through the API, like [this one](https://github.com/supabase/supabase/issues/4440).

If it is possible, how do you set it up?

## Steps Taken

Through another series of GitHub issues I found these variables for the `docker-compose.yml`:
```
storage:
  # [...]
  environment:
    # [...]
    STORAGE_BACKEND: s3
    FILE_STORAGE_BACKEND_PATH: ./data
    TENANT_ID: stub
    REGION: us-southeast-1
    GLOBAL_S3_ENDPOINT: [example-supabase-bucket.us-southeast-1.example-object-storage.com](http://example-supabase-bucket.us-southeast-1.example-object-storage.com/)
    GLOBAL_S3_BUCKET: example-supabase-bucket
    AWS_ACCESS_KEY_ID: replace-with-actual-access-key-id
    AWS_SECRET_ACCESS_KEY: replace-with-actual-access-key-secret
```

However, it's unclear how these get used by `storage-api` backend and whether they would actually enable a connection to a non-AWS S3 endpoint.

I have tried this configuration, only for the bucket API to provide nothing in response. I attempted to create a bucket (`POST /bucket/`) and subsequently to fetch a list of buckets (`GET /bucket/`), but both calls had empty responses.

## Additional Context

A short while back I did post [a similar question](https://github.com/supabase/supabase/discussions/8837) in this discussion board. However, it was concerned more with specifics. This new discussion I mean to focus more on the general question of how to connect to a non-AWS S3 and documenting the process.
