### DISCUSSION TITLE
Using another volume with Storage API.

### DISCUSSION THREAD

**Discussion by rgfx** [supabase/supabase#9273] [Questions] [answered]
Self hosting, I don't know much about servers or docker, and need a little assistance in using a different volume for storage. My hosting plan requires that upgrade CPU and MEM every time I need more space.  They do however offer a resizable storage volume.  

The storage volume is mounted at `/mnt/volume-ash-1#`

Can I simply change the YML file to point to this volume?

```yml
      # FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      FILE_STORAGE_BACKEND_PATH: /mnt/volume-ash-1#  <----change here?
      TENANT_ID: stub
      # TODO: https://github.com/supabase/storage-api/issues/55
      REGION: stub
      GLOBAL_S3_BUCKET: stub
    volumes:
      ## - ./volumes/storage:/var/lib/storage
     ./volumes/storage:/mnt/volume-ash-1# <---- change here?
```

Just wonder if this even possible, or what other solution I could do and continue using Supabase's Storage API?
