### DISCUSSION TITLE
How do I restart my Supabase server without losing data? (self-hosted)

### DISCUSSION THREAD

**Discussion by globemediaofficial** [supabase/supabase#9597] [Questions]
I am self-hosting Supabase on my Debian computer. For some reason, today the server stopped working in my app. I went to the host computer and opened the Supabase studio to see that nothing (auth, db, realtime, etc) would load in the project. It didn't even say that it was loading, it explicitly said that something was wrong and said to talk to support. I assumed that the drive went to sleep and the containers stop so I ran `docker-compose down`, then ran `docker-compose up -d`. Everything started working again, but the data was gone, including all database tables and RLS policies. It was like a fresh project. I think my mistake was the commands I used because they created new containers instead of just restarting what already existed. Luckily, I'm just testing, so there was very little data and it won't be missed. How can I restart the containers without losing data in the future?

**Comment by SamMakesThings** [comment]
Also trying to figure this one out, not seeing a good answer yet

**Reply by globemediaofficial** [reply]
It turned out to be quite easy. Other answers were misleading, talking about copying data and stuff, but if you are just starting and don't already have data, none of that is necessary. You just need to create a directory to a folder called `postgres-data` and add a line with `/<path to location>/postgres-data:/var/lib/postgresql/data` under `db volumes`. Now the data stays the same whenever you use `docker compose down/up`. The first time you start it this way, the necessary files are automatically created in `postgres-data` and you are done. Side note... I recommend making the directory outside of your Supabase folder, so you can easily use it on updated versions instead of copying/moving data.

Here is what you need to do in `docker-compose.yml`:
```
  db:
    container_name: supabase-db
    image: supabase/postgres:14.1.0.89
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db/roles.sql:/docker-entrypoint-initdb.d/roles.sql
      - /<path to location>/postgres-data:/var/lib/postgresql/data ### This is the added line
 ```
