### ISSUE TITLE
Supa sudio bug: connecting fails / docker container supabase-auth restarting fails

### ISSUE THREAD

**Issue by timcouchoud** [supabase/supabase#10541]
# Bug report

## Describe the bug
Connecting not successful...
![image](https://user-images.githubusercontent.com/67595921/204084023-3dd7888f-507d-4c0e-ae89-4a6075a931a6.png)

Container supabase-auth restarting fails....
![image](https://user-images.githubusercontent.com/67595921/204083957-39ae87f3-bb22-4598-aa9b-798c5857dceb.png)

Logs from supabase-auth container
![image](https://user-images.githubusercontent.com/67595921/204084130-24c108ca-390c-4491-bafe-43e558ecdf78.png)

## To Reproduce

1. install Supabase with docker on Ubuntu 20.04.5 LTS
2. open browser on port 3000

**Comment by bnbc** [comment]
I have the same error and i follow Generate API Keys on https://supabase.com/docs/guides/hosting/docker and it was ok.

**Comment by mateusm09** [comment]
I'm having this issue too. It appears that none of the services that depend on the database are able to connect to postgres. I also couldn't get it to work with an external database. 

Logs from supabase-realtime
![image](https://user-images.githubusercontent.com/9003360/206235781-d56b8b5b-1a0d-4004-a76a-4f491946a802.png)

Logs from supabase-rest
![image](https://user-images.githubusercontent.com/9003360/206235915-336ece0b-3159-44c5-a274-9d608bf6e8d2.png)

Logs from supabase-storage
![image](https://user-images.githubusercontent.com/9003360/206236059-a2a6d9ef-3258-4167-92bf-e5a65cfb5e5e.png)


Though the containers can't connect through Docker's network, an external connection is accepted. I'm able to connect with my database management software with all the users that were created by Supabase.

I'm using Docker 20.10.12 running in Ubuntu 20.04.3 LTS

**Comment by mateusm09** [comment]
> I'm having this issue too. It appears that none of the services that depend on the database are able to connect to postgres.
> 
> Logs from supabase-realtime ![image](https://user-images.githubusercontent.com/9003360/206235781-d56b8b5b-1a0d-4004-a76a-4f491946a802.png)
> 
> Logs from supabase-rest ![image](https://user-images.githubusercontent.com/9003360/206235915-336ece0b-3159-44c5-a274-9d608bf6e8d2.png)
> 
> Logs from supabase-storage ![image](https://user-images.githubusercontent.com/9003360/206236059-a2a6d9ef-3258-4167-92bf-e5a65cfb5e5e.png)
> 
> Though the containers can't connect through Docker's network, an external connection is accepted. I'm able to connect with my database management software with all the users that were created by Supabase.
> 
> I'm using Docker 20.10.12 running in Ubuntu 20.04.3 LTS

So I got it working by splitting the docker-compose file in two. One is for Supabase services, and the other is only for the database. 

This is the supabase services compose file: 
```yml
# Usage
#   Start:          docker-compose up
#   With helpers:   docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker-compose down
#   Destroy:        docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

version: "3.8"

services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:0.22.08
    restart: unless-stopped
    ports:
      - ${STUDIO_PORT}:3000/tcp
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      DEFAULT_ORGANIZATION: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT: ${STUDIO_DEFAULT_PROJECT}

      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      # Kept for backwards compatibility with studio:0.22.08
      SUPABASE_REST_URL: ${API_EXTERNAL_URL}/rest/v1/
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}

  kong:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./volumes/api:/var/lib/kong:ro

  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.31.0
    # depends_on:
    #   db: # Disable this if you are using an external Postgres database
    #     condition: service_healthy
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}

      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      # GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: true
      # GOTRUE_SMTP_MAX_FREQUENCY: 1s
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE}

      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
      MFA_ENABLED: ${MFA_ENABLED}

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v9.0.1.20220717
    # depends_on:
    #   db: # Disable this if you are using an external Postgres database
    #     condition: service_healthy
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"

  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v0.25.1
    # depends_on:
    #   db: # Disable this if you are using an external Postgres database
    #     condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v0.21.4
    depends_on:
      # db: # Disable this if you are using an external Postgres database
      #   condition: service_healthy
      rest:
        condition: service_started
    restart: unless-stopped
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      # TODO: https://github.com/supabase/storage-api/issues/55
      REGION: stub
      GLOBAL_S3_BUCKET: stub
    volumes:
      - ./volumes/storage:/var/lib/storage

  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.52.1
    # depends_on:
    #   db: # Disable this if you are using an external Postgres database
    #     condition: service_healthy
    restart: unless-stopped
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: ${POSTGRES_HOST}
      PG_META_DB_PORT: ${POSTGRES_PORT}
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  # Comment out everything below this point if you are using an external Postgres database
  # db:
  #   container_name: supabase-db
  #   image: supabase/postgres:14.1.0.89
  #   healthcheck:
  #     test: pg_isready -U postgres -h localhost
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   command:
  #     - postgres
  #     - -c
  #     - config_file=/etc/postgresql/postgresql.conf
  #     - -c
  #     - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
  #   restart: unless-stopped
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   environment:
  #     POSTGRES_HOST: /var/run/postgresql
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - ./volumes/db/roles.sql:/docker-entrypoint-initdb.d/roles.sql
```

Then I copied the db service to another file in the same folder, and named it db-docker-compose.yml: 
```yml
version: "3.8"

services: 
  db:
    container_name: supabase-db
    image: supabase/postgres:14.1.0.89
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db/roles.sql:/docker-entrypoint-initdb.d/roles.sql
      - ./supabase/db:/var/lib/postgresql/data
 ```

Then just run `docker-compose -f db-docker-compose.yml up -d` and after `docker-compose up -d`
