### ISSUE TITLE
 password authentication failed for user "supabase_auth_admin" - Docker Sefl Hosting

### ISSUE THREAD

**Issue by campioncino** [supabase/supabase#11957]
# Bug report
Can't start Docker 

## Describe the bug
I Followed the guide, and I changed the JWT, ANON and SERVICE values both in .env and kong
When I try to run docker compose up, I see those errors :

supabase_auth_admin@postgres FATAL:  password authentication failed for user "supabase_auth_admin"
authenticator@postgres DETAIL:  User "authenticator" has no password assigned.
 User "supabase_auth_admin" has no password assigned.

I also tried to change DB_USER: ${POSTGRES_USER}  to  DB_USER: supabase_admin in the docker-compose.yml, but I got the same results

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1 Follow the giude
2 docker compose up

## System information

- OS: macOs
- Browser (if applies) [chrome/mozilla]
- Version of Docker: [Docker version 20.10.22, build 3a2c30b]

**Comment by MatiasLGonzalez** [comment]
I am also facing the the same issue.
- OS: Windows 11
- Browser: Mozilla
- Version of Docker: Docker (Desktop with WSL backend) version 20.10.22, build 3a2c30b
The supabase `supabase-auth` container spits the following error:
```
2023-01-30 21:26:58 {"level":"info","msg":"Go runtime metrics collection started","time":"2023-01-31T00:26:58Z"}
2023-01-30 21:26:58 {"args":[0.014355398],"component":"pop","level":"info","msg":"%.4f seconds","time":"2023-01-31T00:26:58Z"}
2023-01-30 21:26:58 {"level":"fatal","msg":"running db migrations: Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to `host=db user=supabase_auth_admin database=postgres`: failed SASL auth (FATAL: password authentication failed for user \"supabase_auth_admin\" (SQLSTATE 28P01))","time":"2023-01-31T00:26:58Z"}
```
if the default `POSTGRES_PASSWORD` in the `.env` file is changed to anything else other than `your-super-secret-and-long-postgres-password`

**Comment by campioncino** [comment]
docker version : 
Using the default parameters (without any changes) this is what I see : 
`WARN[0000] The "MFA_ENABLED" variable is not set. Defaulting to a blank string. 
[+] Running 11/11
 ⠿ studio Pulled                                                                                                                                                         12.0s
   ⠿ 548fcab5fe88 Already exists                                                                                                                                          0.0s
   ⠿ cc40c8ff9db0 Already exists                                                                                                                                          0.0s
   ⠿ 3f8487d8d1dc Already exists                                                                                                                                          0.0s
   ⠿ 5619421d892a Already exists                                                                                                                                          0.0s
   ⠿ 15658185d04a Already exists                                                                                                                                          0.0s
   ⠿ 9ff9fd951310 Pull complete                                                                                                                                           0.6s
   ⠿ 6bbf1858a5f7 Pull complete                                                                                                                                           9.4s
   ⠿ 94f414cb81bb Pull complete                                                                                                                                           9.6s
   ⠿ 6b13fc5c8a10 Pull complete                                                                                                                                           9.8s
   ⠿ 4f4fb700ef54 Pull complete                                                                                                                                           9.9s
[+] Running 10/10
 ⠿ Network docker_default                    Created                                                                                                                      0.1s
 ⠿ Container supabase-studio                 Started                                                                                                                      4.0s
 ⠿ Container supabase-kong                   Started                                                                                                                      4.0s
 ⠿ Container supabase-imgproxy               Started                                                                                                                      3.9s
 ⠿ Container supabase-db                     Healthy                                                                                                                     10.8s
 ⠿ Container supabase-meta                   Started                                                                                                                      8.9s
 ⠿ Container supabase-auth                   Started                                                                                                                      7.4s
 ⠿ Container supabase-rest                   Started                                                                                                                      9.0s
 ⠿ Container realtime-dev.supabase-realtime  Started                                                                                                                      7.0s
 ⠿ Container supabase-storage                Started                                                                                                                      9.2s`

logs : 
`supabase-db  | 
supabase-db  | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db  | 
supabase-db  | 192.168.0.7 2023-02-02 09:13:42.850 UTC [53] supabase_auth_admin@postgres FATAL:  password authentication failed for user "supabase_auth_admin"
supabase-db  | 192.168.0.7 2023-02-02 09:13:42.850 UTC [53] supabase_auth_admin@postgres DETAIL:  User "supabase_auth_admin" has no password assigned.
`

What's wrong?

**Comment by nezzard** [comment]
Have same error, changed jwt anon and service keys, and getting an error  password authentication failed for user "postgres"
But if I read env file from container, password the same as in .env

**Comment by kjetilk-kontali** [comment]
Getting the same error as @nezzard 
> {"code":"PGRST000","details":"connection to server at \"supabase-db\" (172.31.0.4), port 5432 failed: FATAL:  password authentication failed for user \"authenticator\"\n","hint":null,"message":"Database connection error. Retrying the connection."}

With the following in `.env`:
```
POSTGRES_HOST=supabase-db
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_PASSWORD=*********
JWT_SECRET=*********
ANON_KEY=*********
SERVICE_ROLE_KEY=*********
PGRST_DB_SCHEMAS=public,storage,graphql_public
KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443
```

Docker compose:
```
  supabase-api-gateway:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./volumes/api:/var/lib/kong:ro

  supabase-rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v9.0.1.20220717
    depends_on:
      supabase-db: # Disable this if you are using an external Postgres database
        condition: service_healthy
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"

  supabase-storage:
    container_name: supabase-storage
    image: supabase/storage-api:v0.26.1
    depends_on:
      supabase-db: # Disable this if you are using an external Postgres database
        condition: service_healthy
      supabase-rest:
        condition: service_started
      # imgproxy:
      #   condition: service_started
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/status" ]
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      # TODO: https://github.com/supabase/storage-api/issues/55
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "false"
      # IMGPROXY_URL: http://imgproxy:5001
    volumes:
      - ./volumes/storage:/var/lib/storage

  # Comment out everything below this point if you are using an external Postgres database
  supabase-db:
    container_name: supabase-db
    image: supabase/postgres:14.1.0.106
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: unless-stopped
    ports:
      # Pass down internal port because it's set dynamically by other services
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db/realtime.sql:/docker-entrypoint-initdb.d/realtime.sql
      - ./volumes/db/roles.sql:/docker-entrypoint-initdb.d/roles.sql
      # Must be superuser to enable pg_net extension
      - ./volumes/db/webhooks.sql:/etc/postgresql.schema.sql
      - ./volumes/db/data:/var/lib/postgresql/data
```
