### ISSUE TITLE
Can't send invite email on custom SMTP host

### ISSUE THREAD

**Issue by 0x111** [supabase/supabase#12614]
# Bug report

## Describe the bug

I have issues inviting a new user to the instance by using the invite function on the supabase studio panel. I am using the latest compose file from this repo.

I am using my own SMTP server to send the email, on a previous docker-compose file version this works today without issues but not with the newest ones. For some reason it is using my residential IP address to send an email? (As if it would ignore my SMTP settings in the ENV file)

personal@email.com -> being my personal email which I would like to invite

This is the error message: (redacted details)
```
supabase-auth| {"component":"api","level":"info","method":"POST","msg":"request started","path":"/invite","referer":"","remote_addr":"178.143.xx.xx","time":"2023-02-22T23:32:45Z","timestamp":"2023-02-22T23:32:45Z"}
supabase-auth| {"auth_event":{"action":"user_invited","actor_id":"00000000-0000-0000-0000-000000000000","actor_username":"service_role","log_type":"team","traits":{"user_email":"personal@email.com","user_id":"f2ddd654-8f6e-4491-b7b5-29ce37439aca"}},"component":"api","error":"Error sending invite email: gomail: could not send email 1: 554 5.7.1 Service unavailable; Client host [178.143.xx.xx] blocked using zen.spamhaus.org; https://www.spamhaus.org/query/ip/178.143.xx.xx","level":"error","method":"POST","msg":"500: Error inviting user","path":"/invite","referer":"","remote_addr":"178.143.xx.xx","time":"2023-02-22T23:32:46Z","timestamp":"2023-02-22T23:32:45Z"}
supabase-auth| {"auth_event":{"action":"user_invited","actor_id":"00000000-0000-0000-0000-000000000000","actor_username":"service_role","log_type":"team","traits":{"user_email":"personal@email.com","user_id":"f2ddd654-8f6e-4491-b7b5-29ce37439aca"}},"component":"api","duration":296283650,"level":"info","method":"POST","msg":"request completed","path":"/invite","referer":"","remote_addr":"178.143.xx.xx","status":500,"time":"2023-02-22T23:32:46Z","timestamp":"2023-02-22T23:32:45Z"}
```

Current config
```
# Usage
#   Start:          docker-compose up
#   With helpers:   docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker-compose down
#   Destroy:        docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

version: "3.8"

services:
    ....
  auth:
    container_name: supabase-auth
    image: supabase/gotrue:v2.25.1
    depends_on:
      - db # Disable this if you are using an external Postgres database
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}

      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?search_path=auth

      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}

      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_MAILER_URLPATHS_INVITE: ${MAILER_URLPATHS_INVITE}
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: ${MAILER_URLPATHS_CONFIRMATION}
      GOTRUE_MAILER_URLPATHS_RECOVERY: ${MAILER_URLPATHS_RECOVERY}
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: ${MAILER_URLPATHS_EMAIL_CHANGE}

      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
```

I've kept relevant bits, for me the compose files look similar though, except of the gotrue version obviously.

The SMTP config taken from the .env file
```
## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=mysmtpemail@domain.com
SMTP_HOST=mxhost
SMTP_PORT=465
SMTP_USER=mysmtpuser
SMTP_PASS=mysmtppassword
SMTP_SENDER_NAME=smysmtpuser
```
I have the same SMTP config in both.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

If I take the new docker-compose.yml and start up the container with this command:
```
docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up -d
```

I get the error mentioned above. Could you point me in the right direction please?

## Expected behavior

An email invite is being sent.

## System information

- OS: linux
- Browser (if applies) n/a
- Version of supabase-js: n/a
- Version of Node.js: n/a
- 
## Additional context

I tested both versions today, the older one sends the email as expected and the new docker-compose file does not. I could play around with the versions, but in the meanwhile I try my luck here too, maybe someone can help.

My mailing service is also working as expected with other software/scripts/apps, no changes there. So I don't think the issue relies on that part, that is why I am also posting here, since that does not need to be evaluated at this point.

Thanks in advance!
