### ISSUE TITLE
Realtime DB user policy

### ISSUE THREAD

**Issue by Linbreux** [supabase/supabase#1466]
# Bug report

## Describe the bug

When I use my DB in realtime I got a problem. The realtime subscription returns all changes and not only the one that the policy specifies. 

my table:
|id |adres               |private_phone     |user_id                             |
|---|--------------------|------------------|------------------------------------|
|1  |newstreet          |+34 234 352 222 33|24eaa6af-042b-4d10-a4b3-81e3e3da697b|
|2  |street of other user|+00 XX XXXX XXXX  |4c2f2b9f-b100-417c-a536-631f6f570465|

On my DB I have a policy:
```
only user can view changes  
(uid() = user_id)
```

When I try to make a subscription I only would like to receive the changes made from the logged-in user lets say I'm connected as user `24eaa6af-042b-4d10-a4b3-81e3e3da697b`:
```
const mySubscription = supabase
  .from('testtable')
  .on('*', payload => {
    console.log('Change received!', payload)
  })
  .subscribe()

```

When I change data in the DB of the other user (not from the logged in user), the data is shown in the session.

|id |adres               |private_phone     |user_id                             |
|---|--------------------|------------------|------------------------------------|
|2  |street of other user **changed**|+00 XX XXXX XXXX  |4c2f2b9f-b100-417c-a536-631f6f570465|

```
Change received! 
new:
    adres: "street of other user changed"
    id: 2
    private_phone: "+00 XX XXXX XXXX"
    user_id: "4c2f2b9f-b100-417c-a536-631f6f570465"
```
This should not show up

Is there a way to solve this problem? 
Nice project btw!
