### ISSUE TITLE
Email registration behaviour different between local and hosted versions

### ISSUE THREAD

**Issue by aaronzhongg** [supabase/supabase#18195]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With email verification enabled, the response of the auth.signUp() is different when pointing to local development environment and hosted Supabase.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enable 'Confirm email' for Email Auth Provider 
<img width="1152" alt="image" src="https://github.com/supabase/supabase/assets/14045995/7808156e-f7f3-4711-897a-6e4846ba80d1">
2. Run the following jest tests, first with hosted Supabase configurations

``` js
import dotenv from 'dotenv';
import path from 'path';
import { faker } from '@faker-js/faker';
import {
  AuthApiError,
  SupabaseClient,
  createClient,
} from '@supabase/supabase-js';

// Since this is a test project, it's okay to expose both the public anon key and private admin service key
let supabasePublicClient: SupabaseClient;
let supabaseAdminClient: SupabaseClient;

beforeAll(() => {
  const envPath = path.resolve(__dirname, '.env.test');
  const env = dotenv.config({ path: envPath }).parsed!;

  supabasePublicClient = createClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY);
  supabaseAdminClient = createClient(
    env.SUPABASE_URL,
    env.SUPABASE_SERVICE_KEY,
  );
});

describe('Supabase - User Sign Up', () => {
  let response;
  let secondResponse;
  let email = faker.internet.email();

  beforeAll(async () => {
    // Explicitly using the admin client to create a user to bypass email verification
    response = await supabaseAdminClient.auth.admin.createUser({
      email: email,
      password: 'password',
      email_confirm: true,
    });

    await new Promise((resolve) => setTimeout(resolve, 1000)); // Wait for 1 second required by Supabase

    secondResponse = await supabasePublicClient.auth.signUp({
      email: email,
      password: 'different-password',
    });
  });

  test('should return error if email already registered and verified - PASSES ON LOCAL', async () => {
    expect(secondResponse.error).toStrictEqual(
      new AuthApiError('User already registered', 0), // The number is irrelevant
    );
  });

  test('should return fake user data with empty identities - PASSES ON HOSTED', async () => {
    expect(secondResponse.data.user).not.toBeNull();
    expect(secondResponse.data.user?.email).toBe(email.toLowerCase());
    expect(secondResponse.data.user?.identities).not.toBeNull();
    expect(secondResponse.data.user?.identities?.length).toBe(0);
    expect(secondResponse.data.session).toBeNull();
  });
});

```
3. The second test marked as PASSES ON HOSTED, passes, the PASSES ON LOCAL test fails.
4. Run Supabase locally with the following `config.toml`
```toml
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "teachlyapp"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialise the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = false
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Use pre-defined map of phone number to OTP for testing.
[auth.sms.test_otp]
# 4152127777 = "123456"

# Configure one of the supported SMS providers: `twilio`, `twilio_verify`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
# DO NOT commit your OAuth provider secret to git. Use environment variable substitution instead:
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"
```
5. Run the tests again, the reverse set of tests pass/fail

## Expected behavior

The local environment should behave the same as the hosted environment. 

I don't care as much as either specific behaviour but it is CRUCIAL that I am confident that the local environment behaves exactly the same as the hosted version. The reason being that, in order to use this is in production, I will want to run tests against local supabase containers prior to deployment.

## System information

- OS: macOS
- Supabase versions:
    "@supabase/auth-helpers-nextjs": "^0.8.1",
    "@supabase/supabase-js": "^2.37.0",
    "supabase": "^1.99.5",
- Version of Node.js: v20.6.1
