### ISSUE TITLE
Can not start kong container

### ISSUE THREAD

**Issue by hiepvq** [supabase/supabase#18847]
# Bug report

## Describe the bug

2023-11-09 14:38:00 2023/11/09 07:38:00 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2023-11-09 14:38:00 nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2023-11-09 14:38:00 2023/11/09 07:38:00 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
2023-11-09 14:38:00 in 'basicauth_credentials':
2023-11-09 14:38:00   - in entry 1 of 'basicauth_credentials':
2023-11-09 14:38:00     in 'password': expected a string
2023-11-09 14:38:00 stack traceback:
2023-11-09 14:38:00     [C]: in function 'error'
2023-11-09 14:38:00     /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
2023-11-09 14:38:00     init_by_lua:3: in main chunk
2023-11-09 14:38:00 nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
2023-11-09 14:38:00 in 'basicauth_credentials':
2023-11-09 14:38:00   - in entry 1 of 'basicauth_credentials':
2023-11-09 14:38:00     in 'password': expected a string
2023-11-09 14:38:00 stack traceback:
2023-11-09 14:38:00     [C]: in function 'error'
2023-11-09 14:38:00     /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
2023-11-09 14:38:00     init_by_lua:3: in main chunk

## Screenshots
![2023-11-09_14-35-32](https://github.com/supabase/supabase/assets/36187674/ed4e3421-c9d5-4a39-b890-155fd6a78e54)

## System information

- OS: Window 11
- Version of supabase-js: 
git clone --depth 1 https://github.com/supabase/supabase
- Version of Node.js: v20.8.0

**Comment by hiepvq** [comment]
the same on ubuntu 23

![2023-11-10_17-47-56](https://github.com/supabase/supabase/assets/36187674/3cacd9af-8bde-43b3-89c2-803d84e67ecf)
====
- running but can not assign ip address for container, empty map port
![2023-11-10_17-42-37](https://github.com/supabase/supabase/assets/36187674/7e6cc811-0007-4311-b25a-321963e92fa4)

**Comment by exilhanseat** [comment]
I encountered the same issue, any solution or workaround yet?

**Comment by hiepvq** [comment]
@exilhanseat i dont have any solution right now. pls wait

**Comment by exilhanseat** [comment]
don't ask me why, but if I change the Kong section in docker-compose to this, it works:
```
kong:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    # https://unix.stackexchange.com/a/294837
    entrypoint: bash -c 'eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      KONG_LOG_LEVEL: debug
    volumes:
      # https://github.com/supabase/supabase/issues/12661
      - ./volumes/api:/var/lib/kong:ro
```
