### ISSUE TITLE
Can't update files after migration

### ISSUE THREAD

**Issue by RichiB20** [supabase/supabase#20515]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I can't update files in storage after migration from versions:

```
  studio:
    image: supabase/studio:20230216-e731b77
  kong:
    image: kong:2.8.1
  auth:
    image: supabase/gotrue:v2.47.0
  rest:
    image: postgrest/postgrest:v10.1.2
  realtime:
    image: supabase/realtime:v2.5.1
  storage:
    image: supabase/storage-api:v0.30.1
  imgproxy:
    image: darthsim/imgproxy:v3.13
  meta:
    image: supabase/postgres-meta:v0.60.7
  db:
    image: supabase/postgres:15.1.0.42-rc2
```

 to versions:
 
```
studio:
    image: supabase/studio:20231123-64a766a
  kong:
    image: kong:2.8.1
  auth:
    image: supabase/gotrue:v2.125.1
  rest:
    image: postgrest/postgrest:v12.0.1
  realtime:
    image: supabase/realtime:v2.25.35
  storage:
    image: supabase/storage-api:v0.43.11
  imgproxy:
    image: darthsim/imgproxy:v3.8.0
  meta:
    image: supabase/postgres-meta:v0.75.0
  functions:
    image: supabase/edge-runtime:v1.29.1
  analytics:
    image: supabase/logflare:1.4.0
  db:
    image: supabase/postgres:15.1.0.147
  vector:
    image: timberio/vector:0.28.1-alpine
```

## To Reproduce

1. Install the old verions.
2. Upload a new file to storage.
3. Upgrade to the new versions.
4. Upload a file with the same name on the same path.

## Expected behavior

Overwrite the file without error.

## Screenshots

The error appears in docker storage and is the following:

`{"level":50,"time":"2024-01-16T08:23:19.589Z","pid":1,"hostname":"c1868c129091","error":{"raw":"{\"errno\":-20,\"code\":\"ENOTDIR\",\"syscall\":\"lstat\",\"path\":\"/var/lib/storage/stub/path/to/old/file/810562ed-e82c-4cdf-9e15-30d29dcef23f\"}","name":"Error","message":"ENOTDIR: not a directory, lstat '/var/lib/storage/stub/path/to/old/file/810562ed-e82c-4cdf-9e15-30d29dcef23f'","stack":"Error: ENOTDIR: not a directory, lstat '/var/lib/storage/stub/path/to/old/file/810562ed-e82c-4cdf-9e15-30d29dcef23f'"},"jodId":"","type":"event","event":"ObjectAdminDelete","payload":"{\"name\":\"file/path/to/old/file\",\"bucketId\":\"default\",\"tenant\":{\"ref\":\"stub\",\"host\":\"host-name\"},\"version\":\"810562ed-e82c-4cdf-9e15-30d29dcef23f\",\"reqId\":\"req-3dya\",\"$version\":\"v1\"}","objectPath":"path/to/old/file","tenantId":"stub","project":"stub","reqId":"req-3dya","msg":"[Admin]: ObjectAdminDelete path/to/old/file - FAILED"}`

## System information

- OS: Ubuntu 22.04.3 LTS
- Version of supabase-flutter: 2.0.2
- Version of Flutter: 3.13.1

## Additional context

I use the self-hosted version of Supabase.
