### ISSUE TITLE
supabase api 404

### ISSUE THREAD

**Issue by LazerJesus** [supabase/supabase#20979]
i get a bunch of 404 and the interface cant load certain information.
 
<img width="869" alt="Screenshot 2024-02-03 at 20 47 58" src="https://github.com/supabase/supabase/assets/11148454/38b9853d-bbda-4954-a63b-215cb178a86c">
<img width="700" alt="Screenshot 2024-02-03 at 20 51 36" src="https://github.com/supabase/supabase/assets/11148454/fb8ab3d3-9da4-4eca-a626-13f72fd2d7b2">
<img width="690" alt="Screenshot 2024-02-03 at 20 51 49" src="https://github.com/supabase/supabase/assets/11148454/991e36c6-0eb0-4328-bf69-6a71dd255318">

i have setup supabase using the docker compose file in the repo.
.env:
```
SITE_URL=https://mydomain.com
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
API_EXTERNAL_URL=http://localhost:8000

STUDIO_PORT=3000
SUPABASE_PUBLIC_URL=https://mydomain.com:8443
```

the kong.yml has a few modifications to get ssl working (horrible experience)
```
  - name: dashboard
    _comment: 'Studio: /* -> http://studio:3000/*'
    url: http://studio:3000/
    routes:
      - name: dashboard-all
        strip_path: true
        paths:
          - /
        protocols:
          - https
    plugins:
      - name: cors
      - name: basic-auth
        config:
          hide_credentials: true

certificates:
  - snis:
      - name: mydomain.com
      - name: www.mydomain.com
    cert: |- 
        xyz
```
i added certificates and set the protocol to https on all routes.

## System information
- OS: Linux Docker
- Version of supabase-js:    supabase/studio:20240101-8e4a094
