### ISSUE TITLE
Can't connected to supabase in Github Action by direct connection url for postgresql

### ISSUE THREAD

**Issue by Crayon-ShinChan** [supabase/supabase#21338]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In Feb 2024, my github action, suddenly can't connect to supabase with the error:

```
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.ntljbbsmvemwdchumrku.supabase.co:5432"

Error: P[10](https://github.com/Crayon-ShinChan/feelio/actions/runs/7940893515/job/21682900574#step:7:11)01: Can't reach database server at `db.ntljbbsmvemwdchumrku.supabase.co`:`5432`

Please make sure your database server is running at `db.ntljbbsmvemwdchumrku.supabase.co`:`5432`.
```

The github action is:
```yml
name: Migrate Preview Database

on:
  push:
    branches:
      - "preview/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      # - name: Install dependencies
      #   run: npm install
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies with pnpm
        run: pnpm i
      - run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          # this DATABASE_URL will not be used
          DATABASE_URL: ${{ secrets.PREVIEW_DIRECT_URL }}
          DIRECT_URL: ${{ secrets.PREVIEW_DIRECT_URL }}
```

With the prisma schema:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

...
```

My DIRECT_URL is `postgresql://postgres:[password]@db.ntljbbsmvemwdchumrku.supabase.co:5432/postgres`.

With this DIRECT_URL, I could run `npx prisma migrate deploy` in my local successfully. Also, I could connect to database with DataGrip.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Supabase project
2. Create github action for migration with the DIRECT_URL (like the format showed above)
3. Trigger github action

## Expected behavior

successful migration
