### ISSUE TITLE
Supabase Link DNS resolve failure Github Actions

### ISSUE THREAD

**Issue by eduardosanzb** [supabase/supabase#21384]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running supabase link in CI (github action) I'm getting a DNS failuer

failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: hostname resolving error 

I have tried with both dns resolution strategies:

```
supabase link --project-ref $SUPABASE_PROJECT_ID --dns-resolver https
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
    SUPABASE_PROJECT_ID: ***
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: hostname resolving error (failed to locate valid IP for db.***.supabase.co; resolves to []utils.dnsAnswer(nil))
```

```
 supabase link --project-ref $SUPABASE_PROJECT_ID
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
    SUPABASE_PROJECT_ID: ***
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2a05:d014:1c06:5f01:76ce:536:de44:42af]:5432: connect: network is unreachable)
```

## To Reproduce

1. Try to link a supabase in github action
2. run action

```
name: Migrate Supabase DB
description: "Migrate Supabase DB"
inputs:
  supabase_access_token:
    required: true
    description: "Supabase access token"
  supabase_project_id:
    required: true
    description: "Supabase project ID"
  db_password:
    required: true
    description: "DB password"

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Link Supabase Project
      shell: bash
      env:
        SUPABASE_PROJECT_ID: ${{ inputs.supabase_project_id }}
        SUPABASE_ACCESS_TOKEN: ${{ inputs.supabase_access_token }}
        SUPABASE_DB_PASSWORD: ${{ inputs.db_password }}
      run: supabase link --project-ref $SUPABASE_PROJECT_ID --dns-resolver https

    - name: Migrate DB
      shell: bash
      env:
        SUPABASE_PROJECT_ID: ${{ inputs.supabase_project_id }}
        SUPABASE_ACCESS_TOKEN: ${{ inputs.supabase_access_token }}
        SUPABASE_DB_PASSWORD: ${{ inputs.db_password }}
      run: supabase db push --debug
```

## Expected behavior

link to db
