### ISSUE TITLE
CI/CD for Edge functions in GitHub

### ISSUE THREAD

**Issue by anton-kirschhock** [supabase/supabase#27147]
# Bug report

- [x] I confirm this is a bug with Supabase (CLI?), not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I am trying to setup an automated CI/CD pipeline for edge functions in GH and have followed the documentation pages from you guys (https://supabase.com/docs/guides/functions/cicd-workflow) but the command `supabase functions deploy` failes in the GitHub Agents: 
```txt
v1.53.3: Pulling from supabase/edge-runtime
09f376ebb190: Pulling fs layer
....
Status: Downloaded newer image for ghcr.io/supabase/edge-runtime:v1.53.3
failed to start docker container: Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp 127.0.0.1:54328: connect: connection refused
Try rerunning the command with --debug to troubleshoot the error.
```

Any clue on what could be wrong in my pipeline or maybe I am missing something?
It looks like that the docker daemon in GH agents is somehow limited to what they can do: while docker pull works, docker run doesn't.

Our current CI/CD pipeline:
```yml
name: "Deploy Supabase"

on:
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ACCESSTOKEN HERE
      SUPABASE_DB_PASSWORD: DB PASSWORD HERE
      PROJECT_ID:  PROJECT ID HERE
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link  --project-ref $PROJECT_ID
      - run: supabase db push --include-all
      - run: supabase functions deploy --project-ref $PROJECT_ID

```
## To Reproduce

Try deploy edgefunctions using the pipeline above

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]
