### ISSUE TITLE
Self-hosted no postgres log available

### ISSUE THREAD

**Issue by castortech** [supabase/supabase#27329]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I am completely unable to get any logs out of Postgresql. This is a self-hosted environment running with docker-compose (and fronted with nginx)

I have enabled the pgAudit and tried many variation. In studio. I only ever get this one log message that is recorded at startup:
PostgreSQL Database directory appears to contain a database; Skipping initialization 

My studio version is: supabase/studio:20240422-5cf8f30 and supabase/postgres:15.1.1.41 and timberio/vector:0.28.1-alpine

## Expected behavior

Expecting logs to show up. I do get logs under Kong, a bit under PostgREST (doesn't seem to be very complete), Auth & Storage. Nothing in Realtime (but seem to remember seeing something there before)

## Additional context
Outputting the docker logs for vector I get what seems to be a hint as to what is happening but nothing to really solve the issue for me, seeming to indicate some DNS issue :

```
WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: dns error: failed to lookup address information: Try again error_type="request_failed" stage="processing" internal_log_rate_limit=true
WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}: vector::sinks::util::retries: Retrying after error. error=Failed to make HTTP(S) request: error trying to connect: dns error: failed to lookup address information: Try again internal_log_rate_limit=true
WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}:http: vector::internal_events::http_client: Internal log [HTTP error.] is being rate limited.
WARN sink{component_kind="sink" component_id=logflare_db component_type=http component_name=logflare_db}:request{request_id=0}: vector::sinks::util::retries: Internal log [Retrying after error.] is being rate limited.
```

**Comment by castortech** [comment]
Any idea someone, I'm going crazy here.

**Comment by encima** [comment]
Can you see logs within the database container?

Also, are the network names for each unchanged (or any other modifications to the Compose file)?

**Comment by castortech** [comment]
I can't see the logs within the database container.

But hitting a major wall and needing to find a solution right then, I kept digging and found a [post](https://github.com/supabase/realtime/issues/231) that was reporting the opposite, too many logs.

When I checked I saw this, which seemed to be configured to only log panic messages:
```
db:
    container_name: supabase-db
    image: supabase/postgres:15.1.1.41
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      vector:
        condition: service_healthy
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: unless-stopped
    ports:
      # Pass down internal port because it's set dynamically by other services
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

```

I had finally found the postgres log file with: 
```
SELECT pg_current_logfile();
```
and found it under volumes/db/data/log and I knew it did exist somewhere.

Finally I changed the compose file to:
```
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=log # prevents Realtime polling queries from appearing in logs
#      - -c
#      - pg_stat_statements.track=all
      - -c
      - log_statement=ddl
#      - -c
#      - log_error_verbosity=verbose
#      - -c
#      - log_min_error_statement=debug5
```

After that I was able to get log messages in the postgres log directory/files. I have also started to get some logs in the Supabase studio log section for Postgres, but it is still unclear to me what is being picked up and what isn't. Also any attempt to change the Severity option in the UI return this error:
![image](https://github.com/supabase/supabase/assets/85858/8e812b8e-0b0c-4e40-84ec-ab4f04a731c3)

So now I have standard Postgres logs and still struggling a bit to control what I'm getting, but at least I'm not driving in the dark with no dials on the dashboard.
