### ISSUE TITLE
Running `Deno Test` on Supabase Edge Functions in GitHub Actions

### ISSUE THREAD

**Issue by adityamookerjee** [supabase/supabase#28068]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've written `deno tests` that work fine locally (per the Supabase guide), however running this in GitHub Actions doesn't seem to work. 

My GitHub Action file matches that of the Guide

```
name: 'functions-tests'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start
      - run: deno test --allow-all deno-test.ts --env-file .env.local

```

However, I continually see non-200 response errors
