### ISSUE TITLE
using a local development setup, auth.site_url in config.toml is not used in ConfirmationURL

### ISSUE THREAD

**Issue by rhyek** [supabase/supabase#28240]
in the config.toml i can see the following property that i've tried changing and it has no effect:
```toml
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "mylocalsite.app"
```

if i use `{{ .SiteURL }}` in a custom template, it outputs the mylocalsite.app, but `{{ .ConfirmationURL }}` always has the `http://127.0.0.1`
