### ISSUE TITLE
[Selfhost][Logs] 404 error on all Logs pages, Analytics creates the bigquery tables but looks for wrong table name in studio?

### ISSUE THREAD

**Issue by ErwinAI** [supabase/supabase#28309]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've followed the guide at https://supabase.com/docs/reference/self-hosting-analytics/list-endpoints and configured the .env and docker-compose.yml properly. I've commented and uncommented what was required.

What I notice is that in bigquery, five tables are made (automatically by supabase/analytics I'm assuming) and three of them actually receive data. But supabase studio seems to try and fetch a different table that doesn't exist.

Supabase Studio logs error in UI:
```
{
  "code": 404,
  "errors": [
    {
      "domain": "global",
      "message": "Not found: Table project-431009:1_default.0d6c3d43_194e_4e1e_8a58_9c371ea43c26 was not found in location US",
      "reason": "notFound"
    }
  ],
  "message": "Not found: Table project-431009:1_default.0d6c3d43_194e_4e1e_8a58_9c371ea43c26 was not found in location US",
  "status": "NOT_FOUND"
}
```

My bigquery in Google Cloud looks as follows:
<img width="753" alt="image" src="https://github.com/user-attachments/assets/b83588e3-f197-4edc-bab4-29e69a38c502">

As you can see, the table name does not exist but five others were made automatically. Also, the location is US so that seems correct.

Using `docker compose down` and `docker compose up -d` again doesn't fix the problem.

The only thing of interest I found that I'm not sure matters: the `LOGFLARE_API_KEY` env var is still set to the default placeholder. I did not see anything in the Supabase documentation about this, though.

It might very well be a mistake on my side, but I am unsure how to fix this and couldn't find any other issue related to this.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow the guide at https://supabase.com/docs/reference/self-hosting-analytics/introduction
2. This error should occur.

## Expected behavior

The logs pages work properly.

## System information

- OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-116-generic x86_64)
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Full docker-compose.yml:

```
name: supabase
version: "3.8"

services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:20240701-05dfbec
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/profile', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}

      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}

      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_URL: http://analytics:4000
      NEXT_PUBLIC_ENABLE_LOGS: "true"
      # Comment to use Big Query backend for analytics
      # NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
      # Uncomment to use Big Query backend for analytics
      NEXT_ANALYTICS_BACKEND_PROVIDER: bigquery

(... other configuration ...)

  analytics:
    container_name: supabase-analytics
    image: supabase/logflare:1.5.6 # I've tried 1.4.0 like the example, 1.5.6 and 1.7.14 (latest)
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4000/health" ]
      timeout: 5s
      interval: 5s
      retries: 10
    restart: unless-stopped
    depends_on:
      db:
        # Disable this if you are using an external Postgres database
        condition: service_healthy
    # Uncomment to use Big Query backend for analytics
    volumes:
      - type: bind
        source: ${PWD}/gcloud.json
        target: /opt/app/rel/logflare/bin/gcloud.json
        read_only: true
    environment:
      LOGFLARE_NODE_HOST: 127.0.0.1
      DB_USERNAME: supabase_admin
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOSTNAME: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: _analytics
      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_SINGLE_TENANT: "true"
      LOGFLARE_SUPABASE_MODE: "true"
      LOGFLARE_MIN_CLUSTER_SIZE: 1

      # Comment variables to use Big Query backend for analytics
      # POSTGRES_BACKEND_URL: postgresql://supabase_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      # POSTGRES_BACKEND_SCHEMA: _analytics
      # LOGFLARE_FEATURE_FLAG_OVERRIDE: multibackend=true
      # Uncomment to use Big Query backend for analytics
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_PROJECT_NUMBER: ${GOOGLE_PROJECT_NUMBER}
    ports:
      - 4000:4000

```
