### ISSUE TITLE
send_email auth hook emai_change does not contain token

### ISSUE THREAD

**Issue by florian-lefebvre** [supabase/supabase#28808]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I don't know if it's a local only bug, but when using a custom auth hook for `send_email` and when `email_data.email_action_type` is `email_change`, `email_data.token` is an empty string.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. [Setup a HTTP send_email auth hook](https://supabase.com/docs/guides/auth/auth-hooks/send-email-hook?queryGroups=language&language=http)
2. Make sure a user is logged in
3. Update the email (`supabase.auth.updateUser({ email })`)
4. In the custom auth hook, log the data received. Here is an example:

```json
{
  user: {
    id: '0386027a-a39a-45a3-a75e-473c3c888360',
    aud: 'authenticated',
    role: 'authenticated',
    email: 'test@test.com',
    email_confirmed_at: '2024-08-22T07:27:11.394655Z',
    phone: '',
    confirmation_sent_at: '2024-08-22T07:26:55.521605Z',
    confirmed_at: '2024-08-22T07:27:11.394655Z',
    new_email: 'foo@bar.com',
    email_change_sent_at: '2024-08-22T07:36:24.467158Z',
    last_sign_in_at: '2024-08-22T07:27:11.399789Z',
    app_metadata: { provider: 'email', providers: [ 'email' ] },
    user_metadata: {
      email: 'test@test.com',
      email_verified: false,
      phone_verified: false,
      sub: '0386027a-a39a-45a3-a75e-473c3c888360'
    },
    identities: [
      {
        identity_id: 'a2433b21-80f8-4c2b-8425-49076082f2fc',
        id: '0386027a-a39a-45a3-a75e-473c3c888360',
        user_id: '0386027a-a39a-45a3-a75e-473c3c888360',
        identity_data: {
          email: 'test@test.com',
          email_verified: false,
          phone_verified: false,
          sub: '0386027a-a39a-45a3-a75e-473c3c888360'
        },
        provider: 'email',
        last_sign_in_at: '2024-08-22T07:26:55.51048Z',
        created_at: '2024-08-22T07:26:55.510545Z',
        updated_at: '2024-08-22T07:26:55.510545Z',
        email: 'test@test.com'
      }
    ],
    created_at: '2024-08-22T07:26:55.501756Z',
    updated_at: '2024-08-22T07:36:24.991146Z',
    is_anonymous: false
  },
  email_data: {
    token: '',
    token_hash: 'pkce_7f5214d4e090e25816b5b073f7638aa4ca747ab1de65b7c5174a62bf',
    redirect_to: 'http://localhost:8888',
    email_action_type: 'email_change',
    site_url: 'http://127.0.0.1',
    token_new: '',
    token_hash_new: ''
  }
}
```

## Expected behavior

`email_data.token` should contain a value. It works when using an email template instead of an auth hook.

## System information

- OS: Windows 11
- Version of supabase: 1.190.0
- Version of supabase-js: 2.45.1
- Version of Node.js: 20.11.1

**Comment by florian-lefebvre** [comment]
Looking at the auth repo, I think this condition may not be run, leaving the token empty: https://github.com/supabase/auth/blob/2d519569d7b8540886d0a64bf3e561ef5f91eb63/internal/api/mail.go#L500-L509

My supabase auth email config:

```toml
[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = false
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true
```
