### ISSUE TITLE
Optimize visual management panel logic

### ISSUE THREAD

**Issue by renjiali** [supabase/supabase#29526]
**Sometimes we want to hide the panel, we can comment it out, as shown below**
```
  - name: dashboard
    _comment: 'Studio: /* -> http://studio:3000/*'
    url: http://studio:3000/
    routes:
      - name: dashboard-all
        strip_path: true
        paths:
          - /
    plugins:
      - name: cors
      - name: basic-auth
        config:
          hide_credentials: true
```

**To improve safety**

However, sometimes you need to use a panel to facilitate processing if the user sees it`https://192.168.24.3:8443/storage/v1/object/public/video/play/qu-wei-nong-chang/video.mp4?t=2024-09-26T01%3A17%3A42.381Z`

When he tries to access it **https://192.168.24.3:8443**, a panel is displayed, prompting him to enter his account password; This is a little bit insecure, and I would like to do a separation, that is, the administrative panel and the external access url separation, to improve security
