### ISSUE TITLE
SQL Editor file not persisting in self-hosted Supabase instance

### ISSUE THREAD

**Issue by Oksitaine** [supabase/supabase#29574]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the video below, you'll see the issue I'm encountering. 
I have self-hosted the latest version of Supabase using Docker and can access the Supabase localhost without problems. However, when I try to create a new file using the SQL Editor, it doesn't persist after refreshing the page. Is this expected behavior or a current issue with Supabase?

https://github.com/user-attachments/assets/b73258bc-3c00-4000-bb14-64c4af417ad4

## To Reproduce

I think you can see all in this video.

## System information

- OS: MacOS
- Browser Chrome
- Version of supabase-js: 1.93
- Version of Node.js: 20.9

Thanks by advance for your help ^^

**Comment by saltcod** [comment]
Hey there — not a bug but definitely a pain. We're hoping to support saving snippets in self-hosted soon.

**Comment by F0rgenet** [comment]
Issue can be reproduced at the moment, please reopen

**Comment by 3DPrinterArt** [comment]
I have the same issue. Did you find a solution?

**Comment by Oksitaine** [comment]
> I have the same issue. Did you find a solution?

No, i use directly my IDE connect to the database and no more the code editor in supabase.

**Comment by andresvidal** [comment]
Is this still being worked on? Is this a paid/managed only feature? I'm surprised such a simple feature isn't being worked on.

**Comment by aantti** [comment]
@andresvidal It's been just implemented :) I'll update the Docker Compose configuration soon. Ref. PR #41112, #41557

**Comment by andresvidal** [comment]
@aantti that’s great news! I was having trouble getting it to work using my docker-based installation. I had to update the studio service in docker-compose.yml with the following and it worked:

Edit your docker-compose.yml

Find the studio service (usually supabase-studio).

Add both the `env` var and a `volume`:

```
supabase-studio:
  image: supabase/studio:2025.12.17-sha-43f4f7f
  container_name: supabase-studio
  restart: unless-stopped
  environment:
    < ... other variables ... >
    SNIPPETS_MANAGEMENT_FOLDER: /var/lib/supabase/snippets
  volumes:
    - supabase-snippets:/var/lib/supabase/snippets
```

Add the volume (bottom of file)
```
volumes:
  supabase-snippets:
```
