### ISSUE TITLE
[Sefl-hosted] Unable to connect to Supabase DB via psql

### ISSUE THREAD

**Issue by Tejaswgupta** [supabase/supabase#29892]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After the most recent update which broke the server and following steps from [this discussion](https://github.com/supabase/cli/issues/2737) to fix it. I'm unable to connect to Postgres directly anymore.

## To Reproduce

1. Set Port to 5433.
```
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5433
```
2. Start the service using `docker compose up -d`
3. Run `psql -h 127.0.0.1 -p 5433 -d postgres -U postgres`

## Expected behavior
After starting the service, I was able to connect to the db using 
```
psql -h 127.0.0.1 -p 5433 -d postgres -U postgres
```

## System information

- OS: Ubuntu 20.02

**Comment by avallete** [comment]
Hey !

Sorry to hear about this. And thank's for reporting this !

It's likely due to the introduction of the "pooler" within the self-hosted stack. The new connection should use the pooler session mode:

https://supabase.com/docs/guides/database/connecting-to-postgres#supavisor-session-mode-port-5432

So the command to connect would look something like:

```
psql  'postgres://postgres.<tenant-id>:<postgres-password>@localhost:<PG_PORT>/postgres'

# With the default parameters:
psql 'postgres://postgres.your-tenant-id:your-super-secret-and-long-postgres-password@localhost:5432/postgres'
```

Note that the tenant id is configurable here: https://github.com/supabase/supabase/blob/12692d52c56afeef2795dc49c50e9a0d6d033b1c/docker/docker-compose.yml#L473

If you still cannot connect to the pooler, a solution to unblock you could be to just disable it from the self hosted stack by removing this section:

```yaml
  # Update the DATABASE_URL if you are using an external Postgres database
  supavisor:
    container_name: supabase-pooler
    image: supabase/supavisor:1.1.56
    healthcheck:
      test: curl -sSfL --head -o /dev/null "http://127.0.0.1:4000/api/health"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      analytics:
        condition: service_healthy
    command:
      - /bin/sh
      - -c
      - /app/bin/migrate && /app/bin/supavisor eval "$$(cat /etc/pooler/pooler.exs)" && /app/bin/server
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
      - ${POOLER_PROXY_PORT_TRANSACTION}:${POOLER_PROXY_PORT_TRANSACTION}
    environment:
      - PORT=4000
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/_supabase
      - CLUSTER_POSTGRES=true
      - SECRET_KEY_BASE=UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
      - VAULT_ENC_KEY=your-encryption-key-32-chars-min
      - API_JWT_SECRET=${JWT_SECRET}
      - METRICS_JWT_SECRET=${JWT_SECRET}
      - REGION=local
      - ERL_AFLAGS=-proto_dist inet_tcp
      - POOLER_TENANT_ID=your-tenant-id
      - POOLER_DEFAULT_POOL_SIZE=${POOLER_DEFAULT_POOL_SIZE}
      - POOLER_MAX_CLIENT_CONN=${POOLER_MAX_CLIENT_CONN}
      - POOLER_POOL_MODE=transaction
    volumes:
      - ./volumes/pooler/pooler.exs:/etc/pooler/pooler.exs:ro
```

And re-exposing the port for your postgres database directly by changing the `docker-compose.yml` to:

```yaml

  # Comment out everything below this point if you are using an external Postgres database
  db:
    container_name: supabase-db
    image: supabase/postgres:15.1.1.78
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      vector:
        condition: service_healthy
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} # re-expose directly the database port
    ...rest of the db config

```
