### ISSUE TITLE
Supabase CLI Config: `auth.email.smtp` fields are not being expanded 

### ISSUE THREAD

**Issue by woojiahao** [supabase/supabase#32714]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Similar to #30318 , the other fields of the `auth.email.smtp` are not being expanded when using `env()`.

```toml
[auth.email.smtp]
enabled = true
host = "env(LOCAL_SUPABASE_SMTP_HOST)"
port = 587
user = "env(LOCAL_SUPABASE_SMTP_AUTH_USERNAME)"
pass = "env(LOCAL_SUPABASE_SMTP_AUTH_PASSWORD)"
admin_email = "env(LOCAL_SUPABASE_SMTP_ADMIN_EMAIL)"
sender_name = "env(LOCAL_SUPABASE_SMTP_SENDER_NAME)"
```

This makes it hard to setup local development testing that the email sending it working.

## To Reproduce

1. Set the fields of `auth.email.smtp` to use `env()`
2. Send a magic link
3. Get 500s for the various SMTP server fields

## Expected behavior

Using `env()` in the `auth.email.smtp` component should properly expand the environment variables.

## System information

- OS: MacOS 14.5
- Version of supabase-js: `^2.43.5`
- Version of Node.js: `v23.1.0`
