### ISSUE TITLE
Storage Page in Supabase Studio Uses Incorrect API Endpoint (/api/storage//buckets/...), Causing 404 Errors [Regression]

### ISSUE THREAD

**Issue by franciscomfcmaia** [supabase/supabase#33218]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When accessing the **Storage** tab in my self-hosted **Supabase Studio**, the application incorrectly requests bucket objects using an invalid API endpoint, resulting in a **404 Not Found** error. 

This issue is not present when downgrading to **20241021-9f9b083_amd64**. This is a **regression bug**; see [issue 30227](https://github.com/supabase/supabase/issues/30227).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Navigate to the Storage tab in Supabase Studio.
2. Observe the initial request to fetch all buckets:

```
http GET https://supabase.xyz.com/api/storage/default/buckets \
  Authorization:'Basic YXN...' \
  User-Agent:insomnia/10.0.0
```

3. Observe the subsequent request to list objects within the selected bucket:

```
http POST https://supabase.xyz.com/api/storage//buckets/documents/objects/list \
  Authorization:'Basic YXN...' \
  User-Agent:insomnia/10.0.0
```

4. Notice the **404 Not Found** error response that will inevitably result from using the incorrect URL.
5. Manually modify the request URL to include v1:

```
http POST https://supabase.xyz.com/api/storage/v1/buckets/documents/objects/list \
  Authorization:'Basic YXN...' \
  User-Agent:insomnia/10.0.0
```

7. Observe that the modified request successfully returns the list of objects.

Kong is configured as suggested:
```yaml      
- name: storage-v1
        _comment: "Storage: /storage/v1/* -> http://supabase-supabase-storage:5000/*"
        url: http://supabase-supabase-storage:5000/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors
```

## Expected behavior

When selecting a bucket in Supabase Studio's Storage tab, the application should correctly form the API request to list objects using the **/v1** endpoint, such as:

```
http POST https://supabase.xyz.com/api/storage/v1/buckets/documents/objects/list
Authorization:'Basic YXN...'
User-Agent
/10.0.0
```

## Screenshots

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/f91aea55-e190-40d2-a33a-22191becbb86" />

## System information

- Version of Supabase Studio: [20250130-b048539](https://hub.docker.com/layers/supabase/studio/20250130-b048539/images/sha256-6802d1c6b15de3262a0633b5d0b6eeb139a062ff21eee5d674ddd3b5737da43e)
- Version of Node.js: 14.2.21 (from docker image)
