### ISSUE TITLE
External Database (AWS RDS) Not Working with Supabase

### ISSUE THREAD

**Issue by Lovepreetlavi** [supabase/supabase#33616]
I am trying to use an external AWS RDS database with Supabase, but I am encountering issues during migrations. The database schema is set to public, and permissions have been granted, but migrations fail with the following error:

I am using Helm and Deploying Supabase on Eks with external Database Aws Rds

ERROR: no schema has been selected to create in (SQLSTATE 3F000)

{"level":"fatal","msg":"running db migrations: Migrator: problem creating schema migrations: could not execute CREATE TABLE \"schema_migrations\" (\n\"version\" VARCHAR (14) NOT NULL,\nPRIMARY KEY(\"version\")\n);\nCREATE UNIQUE INDEX \"schema_migrations_version_idx\" ON \"schema_migrations\" (version);: ERROR: no schema has been selected to create in (SQLSTATE 3F000)

**Comment by Lovepreetlavi** [comment]
- Hi Team, do we have any updates on this

**Comment by encima** [comment]
Hi there,

I am afraid we do not have official support for external databases or deployments to k8s. If [this](https://github.com/supabase-community/supabase-kubernetes) is the deployment method you are using, please open aniissue in their repository.

It does look like the default schema has not been set and you can try setting the `search_path` but this may be a bigger issue

**Comment by johndpope** [comment]
it's not specific to k8 - im doing a vanilla ec2 setup with external rds  
while you dont support - these docker containers should have a hard fail if they dont have appropriate vars setup - 

+ echo 'Running migrations'
realtime-dev.supabase-realtime  | + sudo -E -u nobody /app/bin/migrate
realtime-dev.supabase-realtime  | 07:23:35.052 [error] Could not create schema migrations table. This error usually happens due to the following:
realtime-dev.supabase-realtime  |
realtime-dev.supabase-realtime  |   * The database does not exist
realtime-dev.supabase-realtime  |   * The "schema_migrations" table, which Ecto uses for managing
realtime-dev.supabase-realtime  |     migrations, was defined by another library
realtime-dev.supabase-realtime  |   * There is a deadlock while migrating (such as using concurrent
realtime-dev.supabase-realtime  |     indexes with a migration_lock)
realtime-dev.supabase-realtime  |
realtime-dev.supabase-realtime  | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
realtime-dev.supabase-realtime  |
realtime-dev.supabase-realtime  | To address the second, you can run "mix ecto.drop" followed by
realtime-dev.supabase-realtime  | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
realtime-dev.supabase-realtime  | configure Ecto to use another table and/or repository for managing
realtime-dev.supabase-realtime  | migrations:
realtime-dev.supabase-realtime  |
realtime-dev.supabase-realtime  |     config :realtime, Realtime.Repo,
realtime-dev.supabase-realtime  |       migration_source: "some_other_table_for_schema_migrations",
realtime-dev.supabase-realtime  |       migration_repo: AnotherRepoForSchemaMigrations


somebody has hardcoded a POSTGRES_DB into realtime that's _supabase

maybe i redo with this hardcoded and see
IF that is the case -  it should be not optional to specify POSTGRES_DB

let me see 


FAILING WITH EXTERNAL RDS
```yaml


realtime:
    container_name: realtime-dev.supabase-realtime
    image: supabase/realtime:v2.34.31
    restart: unless-stopped
    depends_on:
    #   db:
    #     # Disable this if you are using an external Postgres database
    #     condition: service_healthy
      analytics:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-sSfL",
          "--head",
          "-o",
          "/dev/null",
          "-H",
          "Authorization: Bearer ${ANON_KEY}",
          "http://localhost:4000/api/tenants/realtime-dev/health"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      PORT: 4000
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: supabase_admin
      DB_PASSWORD: your-super-secret-and-long-postgres-password 
      DB_NAME: ${POSTGRES_DB} # will be mailopolyapp
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ERL_AFLAGS: -proto_dist inet_tcp
      DNS_NODES: "''"
      RLIMIT_NOFILE: "10000"
      APP_NAME: realtime
      SEED_SELF_HOST: true
      RUN_JANITOR: true
      REALTIME_DB_SCHEMA: _realtime
      REALTIME_MIGRATION_SCHEMA: _realtime


```
