### ISSUE TITLE
over_email_send_rate_limit -running local dev - only 2 emails sent in past hour

### ISSUE THREAD

**Issue by magick93** [supabase/supabase#34222]
# Bug report
this is clearly a bug that has been introduced in a recent upgrade. 

I've been running this project locally for over a year now and have never had this issue. I decided to update the supabase cli, and now get this error. 

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When performing a `supabase.auth.signUp()` invocation I now get:

```
supabase.error: {
      "__isAuthError": true,
      "name": "AuthApiError",
      "status": 429,
      "code": "over_email_send_rate_limit"
    }
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. In Typescript / Javascript, peform a `signUp()` action, eg:

```ts
return await supabase.auth.signUp({
      email: form.data.email,
      password: form.data.password,
      options: {
        emailRedirectTo: `${url.origin}/auth/callback?next=/auth/onboarding`,
        data: userData(),
      }
    });
```
3. This is now fails with error

```js
supabase.error: {
      "__isAuthError": true,
      "name": "AuthApiError",
      "status": 429,
      "code": "over_email_send_rate_limit"
    }
```

## System information

- OS: Ubuntu 24.04.2 LTS
-  `"@supabase/ssr": "^0.5.2"`
-  `"@supabase/supabase-js": "^2.47.10"`

## Additional context

I notice that the dev email appliation has also changed. I discovered this bug after running cypress tests that usually pass without any issue. The first failed. I noticed that the dev email client had changed. I adjusted the test, it still failed. And at this point it had sent 2 emails. 

And this is running completely locally, so I dont see why any email limit would even make sense.

**Comment by catcoon33** [comment]
Are you using your own SMTP server or theirs'?

**Comment by magick93** [comment]
I know the email send limits have been in place in production - that is, running on supabase.com - for a long time. But they were never applied to development. Why would they?

And as such I've routinely been able to develop and run countless tests, creating users etc, without any issue. 

![Image](https://github.com/user-attachments/assets/58f6bd13-53f5-4cd3-b9b0-c53776882b88)

A recent change has applied the supabase.com hosted limits to when running `supabase start` development environments.

**Comment by Hallidayo** [comment]
Hi @magick93 - It seems that the email rate limit was applied around one/two weeks ago. If you take a look these prs this will show changes in the config:

[PR 1](https://github.com/supabase/cli/pull/3206)
[PR 2](https://github.com/supabase/supabase/pull/33830/files)
[PR deployed](https://github.com/supabase/cli/pull/3244)

**Comment by magick93** [comment]
I've now added the following to my `config.toml`

```toml

[auth.email.smtp]
enabled = true

[auth.rate_limit]
# Number of emails that can be sent per hour. Requires auth.email.smtp to be enabled.
email_sent = 2000000
# Number of SMS messages that can be sent per hour. Requires auth.sms to be enabled.
sms_sent = 30
# Number of anonymous sign-ins that can be made per hour per IP address. Requires enable_anonymous_sign_ins = true.
anonymous_users = 30
# Number of sessions that can be refreshed in a 5 minute interval per IP address.
token_refresh = 150
# Number of sign up and sign-in requests that can be made in a 5 minute interval per IP address (excludes anonymous users).
sign_in_sign_ups = 30
# Number of OTP / Magic link verifications that can be made in a 5 minute interval per IP address.
token_verifications = 30
```

But I'm still getting:

```json
supabase.error: {
      "__isAuthError": true,
      "name": "AuthApiError",
      "status": 429,
      "code": "over_email_send_rate_limit"
    }
```

**Comment by magick93** [comment]
To make this situation more complicated, I've installed supabase using brew, and it seems that brew, at least for supabase, does not have a way to revert to a specific version.

**Comment by magick93** [comment]
I've also tried with the following:

```toml
[auth.email.smtp]
enabled = false
```

But still get the same error.
