### ISSUE TITLE
--no-seed flag shouldn't load storage files.

### ISSUE THREAD

**Issue by helalsoft** [supabase/supabase#35508]
## Current Behavior

When running `supabase db reset --no-seed` in a local development environment, Supabase still initializes storage buckets defined in the config (e.g., [storage.buckets.*] entries).

## Desired Behavior

I want to prevent Supabase from loading storage items during a reset. It would be helpful to have a flag such as `--no-seed-buckets` (or similar) to allow more fine-grained control over what gets initialized during a `db reset`.

## Example Config

```toml
[storage.buckets.asset]
public = true
file_size_limit = "5MiB"
allowed_mime_types = ["image/png", "image/jpeg"]
objects_path = "./.buckets/asset"

[storage.buckets.activity]
public = true
file_size_limit = "5MiB"
allowed_mime_types = ["image/png", "image/jpeg"]
objects_path = "./.buckets/activity"

[storage.buckets.avatar]
public = true
file_size_limit = "2MiB"
allowed_mime_types = ["image/png", "image/jpeg"]
objects_path = "./.buckets/avatar"
```
