### ISSUE TITLE
Error while connecting to inbucket mail server for local testing using docker compose

### ISSUE THREAD

**Issue by bhvngt** [supabase/supabase#4656]
# Bug report

## Describe the bug

I am trying to use [inbucket/inbucket:latest](https://hub.docker.com/layers/inbucket/inbucket/latest/images/sha256-1f10a0efea694592c06799c729aee1d6d71c9a4f72b73031d4a426ef5f26dfc1?context=explore) docker image as part of [supabase docker compose](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml). While doing so I get following error when I signup for a user by calling `http://<gotrue>/auth/v1/signup`.

```
supabase-auth | time="2021-12-24T15:22:54Z" level=error msg="500: Error sending confirmation mail" component=api error="Error sending confirmation email: unencrypted connection" method=POST path=/signup
```

Setup is working fine with [inbucket/inbucket:stable](https://hub.docker.com/layers/inbucket/inbucket/stable/images/sha256-96a4dc11f4c898db73c2413381bba2b75ed181199af2a31b12809a9436787ca2?context=explore) which is pointing to an old `release candidate` version whereas the `latest` tag is pointing to the released `v3` version. Hence I am raising this issue.

While going through the `supabase/gotrue` code trail leading to golang's net/smtp [implementation](https://go.dev/src/net/smtp/auth.go?s=1820:1882#L68) I realised that it is expecting `TLS` connection unless host is `localhost`. 

I was wondering if there is a way to bypass the `TLS` requirement in `supabase/gotrue`∑.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add following to `docker-compose.yml`
```
  mail:
    container_name: inbucket
    image: inbucket/inbucket:latest
    ports:
      - "9000:9000"
```
2. docker compose up -d -V --force-recreate
3. curl -X POST -H "Content-Type: application/json" \
                            -H "apikey: <supabase_service_key>" \
                            -H "Authorization: Bearer <supabase_service_key>" \
                            -d '{"email": "user@example.com","password": "Abcd@1234s"}' http://localhost:8000/auth/v1/signup
4. docker compose logs auth
5. see following error
```
supabase-auth  | time="2021-12-24T15:22:54Z" level=error msg="500: Error sending confirmation mail" component=api error="Error sending confirmation email: unencrypted connection" method=POST path=/signup
```

## Expected behavior
it should send signup mail to inbucket.

## System information

- OS: [e.g. macOS, Windows] MacOS
- Docker Desktop `4.3.2`

**Comment by bhvngt** [comment]
While digging deeper I figured out a workaround. We just need to pass empty `SMTP_USER` and `SMTP_USER` env variables to `gotrue`. With that everything works out fine. 

Closing this issue.

**Comment by ARMATAV** [comment]
So I magically ran into this exact problem, and this is the first issue.

`brew upgrade supabase` to get the CLI version where it's fixed - the CLI is actually responsible for generating the `GOTRUE` envars. 

omg

**Comment by reza-sadeghzadeh** [comment]
Anyone facing this issue, solved using Mailhog locally.
Replace the dev compose file for mailhog:
```
mailhog:
    container_name: supabase-mailhog
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web interface
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
    volumes:
      - mailhog-data:/maildir
```
Also add the maildir volume at the end of compose file.

 .env with:
```
# ## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
# ----> Comment the following
# SMTP_ADMIN_EMAIL=admin@example.com 
# SMTP_HOST=supabase-mail
# SMTP_PORT=2500
# SMTP_USER=fake_mail_user
# SMTP_PASS=fake_mail_password
# SMTP_SENDER_NAME=fake_sender
ENABLE_ANONYMOUS_USERS=false

# ----> Add the followings:
# LOCAL EMAIL CONFIGURATION (MailHog)
SMTP_ADMIN_EMAIL=admin@localhost
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=Supabase Local
```
