### ISSUE TITLE
Allow passing build arg for assetPrefix to studio next.config.js via docker-compose/Dockerfile

### ISSUE THREAD

**Issue by humphd** [supabase/supabase#5471]
# Feature request

## Is your feature request related to a problem? Please describe.

The URLs for static assets loaded by the studio container assume that the site is hosted at `/`, which breaks when you put it behind a proxy and change the URL.   For example, the way that fonts are loaded in https://github.com/supabase/supabase/blob/03eed357949495a8cd769a2f302e7f738adfdaa6/studio/pages/_app.tsx#L45

## Describe the solution you'd like

It would be great if we could define an environment variable in `docker-compose.yml` that specified an [`assetPrefix` to give to next.js](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix) in the [next.config.js](https://github.com/supabase/supabase/blob/03eed357949495a8cd769a2f302e7f738adfdaa6/studio/next.config.js).  For example, it could work like so:

```
  studio:
    container_name: supabase-studio
    image: supabase/studio:latest
    ...
    environment:
      SUPABASE_URL: http://kong:8000
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      # Define an assetPrefix to pass to next.config.js
      SUPABASE_STUDIO_ASSET_PREFIX: https://custom.domain.com/supabase
```

Now in `next.config.js`:

```js
module.exports = {
  // If defined, use the supplied prefix
  assetPrefix: process.env.SUPABASE_STUDIO_ASSET_PREFIX : '',
  ...
}
```

## Describe alternatives you've considered

Our current approach is to mount a volume and override `/usr/src/app/next.config.js` with our own version of the config, but this means we have to maintain a forked version.
