### ISSUE TITLE
Support *_FILE for environment variable Docker Secrets in Supabase containers

### ISSUE THREAD

**Issue by humphd** [supabase/supabase#6014]
# Feature request

## Is your feature request related to a problem? Please describe.

We're self-hosting Supabase via Docker (it's amazing, thank you!) and one of the issues we have to deal with is safely storing/passing secrets to the containers.  It would be great if Supabase supported [Docker Secrets](https://docs.docker.com/engine/swarm/secrets), and `*_FILE` versions of the variables that hold secrets, so that we can pass a secrets file vs. the raw value:

```yml
services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:latest
    restart: unless-stopped
    ports:
      - ${STUDIO_PORT}:3000/tcp
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

      SUPABASE_URL: http://kong:8000
      SUPABASE_REST_URL: ${PUBLIC_REST_URL}
      SUPABASE_ANON_KEY_FILE: /run/secrets/anon_key
      SUPABASE_SERVICE_KEY_FILE: /run/secrets/service_key
    secrets:
      - postgres_password
      - anon_key
      - service_key
  ...
```

The current `SUPABASE_SERVICE_KEY` variable could still be supported alongside `SUPABASE_SERVICE_KEY_FILE`, and the same for all of the secrets.  This would let current code continue to work, but migrate to a more secure method of injecting secrets.

## Describe the solution you'd like

[Docker really wants users](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images) to use `FOO_FILE` vs. `FOO`, and have the app read the value from `FOO_FILE` at runtime.  This file is then provided to the container safely as a secret, mounted securely at `/run/secrets/foo` by the Docker engine.

Some people to tricks to read these files and export to environment variables, but it's not recommended:

> Docker secrets do not set environment variables directly. This was a conscious decision, because environment variables can unintentionally be leaked between containers (for instance, if you use --link).

## Describe alternatives you've considered

The typical work-around is to use the `ENTRYPOINT` to run a shell script that reads the files and exports them into the environment, using the given variable name.  It can work.  But it would be better to use the suggested approach.

## Additional context

In terms of prior-art, [postgres already does this for their image](https://hub.docker.com/_/postgres):

> Docker Secrets
>
> As an alternative to passing sensitive information via environment variables, _FILE may be appended to some of the previously listed environment variables, causing the initialization script to load the values for those variables from files present in the container. In particular, this can be used to load passwords from Docker secrets stored in /run/secrets/<secret_name> files. For example:
>
> `$ docker run --name some-postgres -e POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd -d postgres`
>
> Currently, this is only supported for POSTGRES_INITDB_ARGS, POSTGRES_PASSWORD, POSTGRES_USER, and POSTGRES_DB.

I think this same pattern could be extended to all the `supabase/*` images.
