### ISSUE TITLE
CI/CD: Testing RLS Policies

### ISSUE THREAD

**Issue by MentalGear** [supabase/supabase#9576]
# Improve documentation

## Describe the problem

DB security is crucial for any serious project, and only solid if also it testable. Currently, the docs don't show any way how RLS polices can be tested, for example in a CI/CD automated test environment.

## Describe the improvement
It'd be great if we had a guide showing how we can
a) check whether queries are allowed/denied (maybe using supabase API)
b) how to test these as (mocked) authenticated users, with different roles
Maybe using something like Vitest with API calls.

**Comment by sagi-gamago** [comment]
For those who need help starting.

reference for what you can do with your new power -> [basejump](https://github.com/usebasejump/supabase-test-helpers/tree/main)

create a file in supabase named: test-util
```SQL
create extension if not exists http with schema extensions;
CREATE EXTENSION IF NOT EXISTS pg_tle;
drop extension if exists "supabase-dbdev";
select pgtle.uninstall_extension_if_exists('supabase-dbdev');
select
    pgtle.install_extension(
        'supabase-dbdev',
        resp.contents ->> 'version',
        'PostgreSQL package manager',
        resp.contents ->> 'sql'
    )
from http(
    (
        'GET',
        'https://api.database.dev/rest/v1/'
        || 'package_versions?select=sql,version'
        || '&package_name=eq.supabase-dbdev'
        || '&order=version.desc'
        || '&limit=1',
        array[
            ('apiKey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdXB0cHBsZnZpaWZyYndtbXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODAxMDczNzIsImV4cCI6MTk5NTY4MzM3Mn0.z2CN0mvO2No8wSi46Gw59DFGCTJrzM0AQKsu_5k134s')::http_header
        ],
        null,
        null
    )
) x,
lateral (
    select
        ((row_to_json(x) -> 'content') #>> '{}')::json -> 0
) resp(contents);
CREATE EXTENSION "supabase-dbdev";
select dbdev.install('supabase-dbdev');
drop extension if exists "supabase-dbdev";
create extension "supabase-dbdev";
select dbdev.install('basejump-supabase_test_helpers');
CREATE EXTENSION if not exists "basejump-supabase_test_helpers";
```

add to the .github CI.yaml file:
```yaml
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: |
          cp supabase/test-util.sql supabase/migrations/`date +%Y%m%d%H%M%S`_testutil.sql
          supabase db start
          supabase migration up
          supabase db lint
          supabase test db

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
```

enjoy!
